:PROPERTIES:
:ID:       8cfffaf9-50bb-486d-b3db-98065c9de49e
:END:
#+title: Nonguix
#+filetags: :package_management:lisp:operating_systems:computer_science:

A repository for [[id:9af45692-b2f1-4d4e-a9b3-03d355ffacd0][Guix]] that includes non-free software.
* (gitlab.com) Nonguix / nonguix · GitLab                           :website:
:PROPERTIES:
:ID:       fe0619fe-da1f-440e-9c8b-13b2119b9bfe
:ROAM_REFS: https://gitlab.com/nonguix/nonguix
:END:

#+begin_quote
  * Nonguix

  Nonguix is a software repository for the [[https://www.gnu.org/software/guix/][GNU Guix]] package manager, which packages some software which cannot be included in the official distribution for ethical or policy-related reasons.

  Please do NOT promote this repository on any official Guix communication channels, such as their mailing lists or IRC channel, even in response to support requests!  This is to show respect for the Guix project's [[http://www.gnu.org/distros/free-system-distribution-guidelines.html][strict policy]] against recommending nonfree software, and to avoid any unnecessary hostility.

  Before using this channel, you should understand the implications of using nonfree software.  Read [[https://www.gnu.org/philosophy/free-sw.en.html][What is free software?]] for more information.

  (Check out the [[https://gitlab.com/guix-gaming-channels][Guix Gaming Channels]] if you're interested in nonfree games too!)
#+end_quote
* See Also
 - [[id:949d306c-36bc-4f39-ab4e-c855f4924432][GNU Guix System]]
