:PROPERTIES:
:ID:       e0244168-484c-470f-b4e9-906079d4ef80
:END:
#+title: Machine Learning (ML)
#+filetags: :machine_learning:artificial_intelligence:

Machine learning, a sub-discipline of [[id:b10990c2-d056-42f5-a4e7-145a405d9550][Artificial Intelligence]], is the study and practice of using statistical algorithms to learn from and generalize data.
* (en.wikipedia.org) Machine learning - Wikipedia                   :website:
:PROPERTIES:
:ID:       e812abcb-d91a-46fc-acbe-84efaa4e25e2
:ROAM_REFS: https://en.wikipedia.org/wiki/Machine_learning
:END:

#+begin_quote
  Machine learning (ML) is a field of study in artificial intelligence concerned with the development and study of statistical algorithms that can learn from data and generalize to unseen data, and thus perform tasks without explicit instructions.  Advances in the field of deep learning have allowed neural networks to surpass many previous approaches in performance.
  ML finds application in many fields, including natural language processing, computer vision, speech recognition, email filtering, agriculture, and medicine.  The application of ML to business problems is known as predictive analytics.
  Statistics and mathematical optimization (mathematical programming) methods comprise the foundations of machine learning.  Data mining is a related field of study, focusing on exploratory data analysis (EDA) via unsupervised learning.
  From a theoretical viewpoint, probably approximately correct (PAC) learning provides a framework for describing machine learning.
#+end_quote
