:PROPERTIES:
:ID:       95665463-a8fa-4262-bf6b-ca38650e1faa
:END:
#+title: Organice
#+filetags: :open_source:emacs:information_management:software:

[[id:a3c19488-876c-4b17-81c0-67b9c7fc64ee][Open-source]], [[id:05f2a17c-4ceb-42fa-bcc8-16d61473804b][web]]-based, mobile-first interface to [[id:5ab4a0b0-95e2-40cf-b924-709db3115d48][Org-mode]].
* (organice.200ok.ch) organice - keep your life nicely organized    :website:
:PROPERTIES:
:ID:       9caec5b8-cfdf-4b5c-b03f-893e490b231b
:ROAM_REFS: https://organice.200ok.ch/
:END:

#+begin_quote
  * organice is the best way to get stuff done

  Whether you're planning multiple work projects, sharing a shopping list with your partner or you're planing a holiday, organice is here to help you complete all your personal and professional tasks.

  organice is Free and Open Source software that works on top of Org mode files.

  *** Plan for anything

  Organize and share your to-do, work, grocery, movies and household lists.  No matter what you're planning, how big or small the task may be, organice makes it super easy to get stuff done.

  *** See your agenda anytime

  Set schedules and deadlines on to-dos.  No matter whether your tasks are work related or just for fun, you will never miss a deadline again with organice in charge.

  *** Privacy and freedom first

  organice is Free and Open Source software protecting your freedom to run, copy, distribute, study, change and improve the software.  Your most important data should never be in a closed silo.

  We also never see your data - only you and your personal storage provider does.  organice saves your files in the free format Org mode, so you can always access it with any tool at any time!

  * Access from anywhere

  *Available on iPhone, Android, and the Web, organice works seamlessly across all major devices.*

  ** Remember all the things

  Succeed with every project

  ****** Work anywhere

  organice works on all major platforms, so you can access your information wherever you are.

  ****** Find your content quickly

  Thanks to a flexible query language and a bookmarking system, you can find your important content quickly and reliably.

  * What our users say

  "This is a SPECTACULAR project and I am glad that I found it.  organice takes the extreme power of org mode and makes it simple to use.  When combined with the option to self-host your own data rganice has created an extremely flexible and secure option to help fulfill everyone's organizational needs."

  [[https://github.com/dmorlitz][@dmorlitz]]

  Contributor

  "Been using organice for years.  To me, it's by far the most usable solution for interacting with org files on a mobile device."

  [[https://github.com/jcpst][@jcpst]]

  User

  --------------

  ***** Intro video

  If you are interested into the 'why did we get started with organice', we have got you covered.  For [[https://emacsconf.org/2019/][EmacsConf 2019]], we have created a 10 minute introductory video into the rationale and usability of organice.

  ** Get started

  organice is [[https://www.gnu.org/philosophy/free-sw.en.html][free software]] and will stay this way.  Leave the closed silos behind and let your knowledge roam free.  Start with the live demo - you don't even need to sign up.  Check it out first and sign up later.

  **** Do you have further questions?

  Join the inclusive and friendly community chat, and let's have a talk.
#+end_quote
