:PROPERTIES:
:ID:       d928ffee-5f03-429d-8ad2-1efe8d195472
:END:
#+title: Natural Language Processing (NLP)

NLP, a sub-discipline of Computer Science and [[id:b10990c2-d056-42f5-a4e7-145a405d9550][Artificial Intelligence]], is the study and practice of processing, parsing, and generating natural human language using computers.  Frequently makes use of [[id:e0244168-484c-470f-b4e9-906079d4ef80][Machine Learning]].
* (en.wikipedia.org) Natural language processing - Wikipedia        :website:
:PROPERTIES:
:ID:       1e9a8544-a729-4088-a84c-b7127b140d98
:ROAM_REFS: https://en.wikipedia.org/wiki/Natural_language_processing
:END:

#+begin_quote
  Natural language processing (NLP) is a subfield of computer science and especially artificial intelligence.  It is primarily concerned with providing computers with the ability to process data encoded in natural language and is thus closely related to information retrieval, knowledge representation and computational linguistics, a subfield of linguistics.  Typically data is collected in text corpora, using either rule-based, statistical or neural-based approaches in machine learning and deep learning.
  Major tasks in natural language processing are speech recognition, text classification, natural-language understanding, and natural-language generation.
#+end_quote
