:PROPERTIES:
:ID:       73e3d83c-ece6-4f88-8045-d46e6eaa530f
:END:
#+title: PlantUML
#+filetags: :open_source:diagramming:software:

[[id:a3c19488-876c-4b17-81c0-67b9c7fc64ee][Open-source]] [[id:d305645c-9440-454e-bfd1-d5d4e25027b0][diagram]] software for making [[id:fab53e34-ce16-4d92-acfb-225d47dbbef7][UML]] diagrams via a description language or visually with a builder tool.
* Open-source tool that uses simple textual descriptions to draw beautiful [[id:fab53e34-ce16-4d92-acfb-225d47dbbef7][UML]] diagrams. :website:
:PROPERTIES:
:ID:       ff889383-1dae-4f11-b9cc-3d0edef05683
:ROAM_REFS: https://plantuml.com/
:END:

#+begin_quote
  PlantUML is a highly versatile tool that facilitates the rapid and straightforward creation of a wide array of [[id:d305645c-9440-454e-bfd1-d5d4e25027b0][diagrams]].
  Utilizing a simple and intuitive language, users can effortlessly draft various types of diagrams.  For a detailed exploration of the language's capabilities and syntax, please refer to the PlantUML Language Reference Guide.
  If you are new to PlantUML, we recommend starting with our quick start page to get up and running quickly.  Should you have any questions, our F.A.Q. page is a valuable resource.  Additionally, PlantUML can be seamlessly integrated with a variety of other tools to enhance your workflow.
#+end_quote
