:PROPERTIES:
:ID:       768060b9-d3f6-4b23-8b4b-e956dd40f6d2
:END:
#+title: The Deleterious Effect Capitalism Without Robust Social Safety Nets Has on Society
#+filetags: :social:navel_gazing:

Not having good social safety nets in place in a capitalistic society has profound deleterious effects on society as a whole via the impact on how people on an individual level make decisions.  Since people's survival hinges on having stable employment, every decision that can impact that employment his tainted by the need for survival which supplants other decision criteria.

People won't become whistle-blowers for corruption or illegal activities because of the impact on their ability to be employed.  People won't work towards shaping the [[id:4b177854-1711-41a2-8ef0-7a2208174234][company]] they work at because they only have the job to earn a paycheck because they didn't have the time to find a job they actually care about.  The list goes on.

This results in society stagnating and allows corruption to grow largely unchecked since people care more for their own survival before the needs of society.  Not that putting one's own survival first is wrong in any way.
