:PROPERTIES:
:ID:       e5a582e4-16fb-4fd3-b182-07abf5720ee1
:END:
#+title: Vannevar Bush
#+filetags: :person:biographic:

American inventor, engineer, and science administrator.  During World War II headed the U.S. Office of Scientific Research and Development (OSRD) and through which oversaw early stages of the Manhattan Project.  Was partially responsible for the movement that led to the founding of the National Science Foundation (NSF) which is a partial successor agency to the OSRD.  Invented the concept of the [[id:b78b21dc-3632-4ab1-8f48-d35e0c87b6d5][Memex]], which led directly to [[id:a0ac6689-ad9b-4a28-b630-0dd12f15cff1][hypertext]], in his 1945 essay "As We May Think".
* (en.wikipedia.org) Vannevar Bush - Wikipedia                      :website:
:PROPERTIES:
:ID:       e495051c-5943-4d92-94a3-e542503cd202
:ROAM_REFS: https://en.wikipedia.org/wiki/Vannevar_Bush
:END:

#+begin_quote
  *Vannevar Bush* ([[https://en.wikipedia.org/wiki/Help:IPA/English][/væˈniːvɑːr/]] [[https://en.wikipedia.org/wiki/Help:Pronunciation_respelling_key][/van-NEE-var/]]; March 11, 1890 -- June 28, 1974) was an American engineer, inventor and science administrator, who during [[https://en.wikipedia.org/wiki/World_War_II][World War II]] headed the U.S. [[https://en.wikipedia.org/wiki/Office_of_Scientific_Research_and_Development][Office of Scientific Research and Development]] (OSRD), through which almost all wartime military [[https://en.wikipedia.org/wiki/Research_and_development][R&D]] was carried out, including important developments in [[https://en.wikipedia.org/wiki/Radar][radar]] and the initiation and early administration of the [[https://en.wikipedia.org/wiki/Manhattan_Project][Manhattan Project]].  He emphasized the importance of scientific research to national security and economic well-being, and was chiefly responsible for the movement that led to the creation of the [[https://en.wikipedia.org/wiki/National_Science_Foundation][National Science Foundation]].

  Bush joined the Department of Electrical Engineering at [[https://en.wikipedia.org/wiki/Massachusetts_Institute_of_Technology][Massachusetts Institute of Technology]] (MIT) in 1919, and founded the company that became [[https://en.wikipedia.org/wiki/Raytheon_Company][Raytheon]] in 1922.  Bush became vice president of MIT and dean of the [[https://en.wikipedia.org/wiki/MIT_School_of_Engineering][MIT School of Engineering]] in 1932, and president of the [[https://en.wikipedia.org/wiki/Carnegie_Institution_of_Washington][Carnegie Institution of Washington]] in 1938.

  During his career, Bush patented a string of his own inventions.  He is known particularly for his engineering work on [[https://en.wikipedia.org/wiki/Analog_computer][analog computers]], and for the [[https://en.wikipedia.org/wiki/Memex][memex]].  Starting in 1927, Bush constructed a [[https://en.wikipedia.org/wiki/Differential_analyser][differential analyzer]], a mechanical analog computer with some digital components that could solve [[https://en.wikipedia.org/wiki/Differential_equation][differential equations]] with as many as 18 independent variables.  An offshoot of the work at MIT by Bush and others was the beginning of [[https://en.wikipedia.org/wiki/Digital_circuit][digital circuit]] design theory.  The memex, which he began developing in the 1930s (heavily influenced by [[https://en.wikipedia.org/wiki/Emanuel_Goldberg][Emanuel Goldberg]]'s "Statistical Machine" from 1928) was a hypothetical adjustable [[https://en.wikipedia.org/wiki/Microfilm][microfilm]] viewer with a structure analogous to that of [[https://en.wikipedia.org/wiki/Hypertext][hypertext]].  The memex and Bush's 1945 essay "[[https://en.wikipedia.org/wiki/As_We_May_Think][As We May Think]]" influenced generations of computer scientists, who drew inspiration from his vision of the future.

  Bush was appointed to the [[https://en.wikipedia.org/wiki/National_Advisory_Committee_for_Aeronautics][National Advisory Committee for Aeronautics]] (NACA) in 1938, and soon became its chairman.  As chairman of the [[https://en.wikipedia.org/wiki/National_Defense_Research_Committee][National Defense Research Committee]] (NDRC), and later director of OSRD, Bush coordinated the activities of some six thousand leading American scientists in the application of science to warfare.  Bush was a well-known policymaker and public intellectual during World War II, when he was in effect the first presidential [[https://en.wikipedia.org/wiki/Office_of_Scientific_Research_and_Development][science advisor]].  As head of NDRC and OSRD, he initiated the Manhattan Project, and ensured that it received top priority from the highest levels of government.  In /Science, The Endless Frontier/, his 1945 report to the president of the United States, Bush called for an expansion of government support for science, and he pressed for the creation of the [[https://en.wikipedia.org/wiki/National_Science_Foundation][National Science Foundation]].
#+end_quote
