:PROPERTIES:
:ID:       a4653a35-1d90-4001-8147-8a2897ea1256
:END:
#+title: Simply Scheme: Introducting Computer Science
#+filetags: :education_resource:scheme:lisp:computer_science:textbooks:books:

* (people.eecs.berkeley.edu) Simply Scheme: Introducing Computer Science :website:
:PROPERTIES:
:ID:       36cc076e-e5dd-435d-ac6a-f1a9fa4b04b0
:ROAM_REFS: https://people.eecs.berkeley.edu/~bh/ss-toc2.html
:END:

#+begin_quote
  * /Simply Scheme: Introducing Computer Science/

  2/e Copyright (C) 1999 MIT

  * Table of Contents

  Brian Harvey
  University of California, Berkeley
  Matthew Wright
  Stanford University

  --------------

  Below this short table of contents is an expanded table of contents including sections within each chapter.  Click on the chapter name to jump down.  You can also download the complete text of each chapter in PDF format for elegant printing, or browse the HTML version.  Part introductions are included in the PDF of the following chapter.  Projects are included in the PDF of the preceding chapter.

  /Note: This book is still in copyright, and in print.  It is posted here for your personal use, not for resale or redistribution.  Thanks!/
#+end_quote
* (www.amazon.com) Simply Scheme - 2nd Edition: Introducing Computer Science: 9780262082815: Computer Science Books @ Amazon.com :website:
:PROPERTIES:
:ID:       6b7cbcdb-ee28-408a-8181-9fb9d27d1716
:ROAM_REFS: https://www.amazon.com/dp/0262082810
:END:

#+begin_quote
  This lively introduction to computer science and computer programming in Scheme is for non-computer science majors with a strong interest in the subject and for computer science majors who lack prior programming experience.  The text allows the student to experience the computer as a tool for expressing ideas, not as a frustrating set of mathematical obstacles.  This goal is supported by the use of Scheme, a modern dialect of Lisp, designed to emphasize symbolic programming.
#+end_quote
