:PROPERTIES:
:ID:       e4639006-f52c-4fcd-9a26-2d806dd3ea1e
:END:
#+title: IBM
#+filetags: :ibm_corp:organization:

International Business Machines Corporation, more commonly known as IBM, or, occasionally, Big Blue.
* (en.wikipedia.org) IBM - Wikipedia                                :website:
:PROPERTIES:
:ID:       277dbc10-86ff-406d-9a2c-00a3cebc9dcf
:ROAM_REFS: https://en.wikipedia.org/wiki/IBM
:END:

#+begin_quote
  *International Business Machines Corporation* (using the [[https://en.wikipedia.org/wiki/Trademark][trademark]] *IBM*), nicknamed *Big Blue*, is an American [[https://en.wikipedia.org/wiki/Multinational_corporation][multinational]] [[https://en.wikipedia.org/wiki/Technology_company][technology company]] headquartered in [[https://en.wikipedia.org/wiki/Armonk,_New_York][Armonk, New York]] and present in over 175 countries.  It is a [[https://en.wikipedia.org/wiki/Publicly-traded_company][publicly traded company]] and one of the 30 companies in the [[https://en.wikipedia.org/wiki/Dow_Jones_Industrial_Average][Dow Jones Industrial Average]].  IBM is the largest industrial research organization in the world, with 19 research facilities across a dozen countries, having held the record for most annual [[https://en.wikipedia.org/wiki/United_States][U.S.]] [[https://en.wikipedia.org/wiki/Patent][patents]] generated by a business for 29 consecutive years from 1993 to 2021.

  IBM was founded in 1911 as the [[https://en.wikipedia.org/wiki/Computing-Tabulating-Recording_Company][Computing-Tabulating-Recording Company]] (CTR), a [[https://en.wikipedia.org/wiki/Holding_company][holding company]] of manufacturers of record-keeping and measuring systems.  It was renamed "International Business Machines" in 1924 and soon became the leading manufacturer of [[https://en.wikipedia.org/wiki/Tabulating_machine][punch-card tabulating systems]].  During the 1960s and 1970s, the [[https://en.wikipedia.org/wiki/IBM_mainframe][IBM mainframe]], exemplified by the [[https://en.wikipedia.org/wiki/IBM_System/360][System/360]], was the world's dominant [[https://en.wikipedia.org/wiki/Computing_platform][computing platform]], with the company producing 80 percent of computers in the U.S. and 70 percent of computers worldwide.

  IBM debuted in the [[https://en.wikipedia.org/wiki/Microcomputer][microcomputer]] market in 1981 with the [[https://en.wikipedia.org/wiki/IBM_Personal_Computer][IBM Personal Computer]], --- its [[https://en.wikipedia.org/wiki/DOS][DOS]] software provided by [[https://en.wikipedia.org/wiki/Microsoft][Microsoft]], which became the basis for the majority of [[https://en.wikipedia.org/wiki/Personal_computers][personal computers]] to the present day.  The company later also found success in the [[https://en.wikipedia.org/wiki/Portable_computer][portable]] space with the [[https://en.wikipedia.org/wiki/ThinkPad][ThinkPad]].  Since the 1990s, IBM has concentrated on [[https://en.wikipedia.org/wiki/Information_technology][computer services]], [[https://en.wikipedia.org/wiki/Software][software]], [[https://en.wikipedia.org/wiki/Supercomputer][supercomputers]], and [[https://en.wikipedia.org/wiki/Scientific_method#Scientific_inquiry][scientific research]]; it sold its microcomputer division to [[https://en.wikipedia.org/wiki/Lenovo][Lenovo]] in 2005.  IBM continues to develop mainframes, and its supercomputers have [[https://en.wikipedia.org/wiki/TOP500][consistently ranked]] among the most powerful in the world in the 21st century.  In 2018, IBM along with 91 additional [[https://en.wikipedia.org/wiki/Fortune_500][/Fortune/ 500]] companies had "paid an effective federal tax rate of 0% or less" as a result of Donald Trump´s [[https://en.wikipedia.org/wiki/Tax_Cuts_and_Jobs_Act_of_2017][Tax Cuts and Jobs Act of 2017]].

  As one of the world's oldest and largest technology companies, IBM has been responsible for several [[https://en.wikipedia.org/wiki/Technological_innovation][technological innovations]], including the [[https://en.wikipedia.org/wiki/Automated_Teller_Machine][Automated Teller Machine]] (ATM), [[https://en.wikipedia.org/wiki/Dynamic_random-access_memory][Dynamic Random-Access Memory]] (DRAM), the [[https://en.wikipedia.org/wiki/Floppy_disk][floppy disk]], the [[https://en.wikipedia.org/wiki/Hard_disk_drive][hard disk drive]], the [[https://en.wikipedia.org/wiki/Magnetic_stripe_card][magnetic stripe card]], the [[https://en.wikipedia.org/wiki/Relational_model][relational database]], the [[https://en.wikipedia.org/wiki/SQL][SQL programming language]], and the [[https://en.wikipedia.org/wiki/Universal_Product_Code][Universal Product Code]] (UPC) barcode.  The company has made inroads in advanced [[https://en.wikipedia.org/wiki/Integrated_circuit][computer chips]], [[https://en.wikipedia.org/wiki/Quantum_computing][quantum computing]], [[https://en.wikipedia.org/wiki/Artificial_intelligence][artificial intelligence]], and [[https://en.wikipedia.org/wiki/Data_infrastructure][data infrastructure]].  IBM employees and alumni have won various recognitions for their scientific research and inventions, including six [[https://en.wikipedia.org/wiki/Nobel_Prize][Nobel Prizes]] and six [[https://en.wikipedia.org/wiki/Turing_Award][Turing Awards]].
#+end_quote
