:PROPERTIES:
:ID:       d548e7db-0a88-4a2f-a2a7-ac90f4676046
:END:
#+title: OpenRISC
#+filetags: :open_source:electronics:processor:microprocessor:computer_architecture:computer_science:

An entirely [[id:a3c19488-876c-4b17-81c0-67b9c7fc64ee][open-source]] hardware [[id:321ba3cc-d73a-4620-88f7-2527cbae1aac][RISC]] [[id:c980a340-2564-437e-a79f-388122a206ad][ISA]] and microprocessor.
* (en.wikipedia.org) OpenRISC - Wikipedia                           :website:
:PROPERTIES:
:ID:       5ce68a9a-e673-4a42-91b6-891003dc52ea
:ROAM_REFS: https://en.wikipedia.org/wiki/OpenRISC
:END:

#+begin_quote
  *OpenRISC* is a project to develop a series of [[https://en.wikipedia.org/wiki/Open-source_hardware][open-source hardware]] based [[https://en.wikipedia.org/wiki/Central_processing_unit][central processing units]] (CPUs) on established [[https://en.wikipedia.org/wiki/Reduced_instruction_set_computer][reduced instruction set computer]] (RISC) principles.  It includes an [[https://en.wikipedia.org/wiki/Instruction_set_architecture][instruction set architecture]] (ISA) using an [[https://en.wikipedia.org/wiki/Open-source_license][open-source license]].  It is the original flagship project of the [[https://en.wikipedia.org/wiki/OpenCores][OpenCores]] community.

  The first (and as of 2019 only) architectural description is for the OpenRISC 1000 ("OR1k"), describing a family of [[https://en.wikipedia.org/wiki/32-bit][32-bit]] and [[https://en.wikipedia.org/wiki/64-bit][64-bit]] processors with optional [[https://en.wikipedia.org/wiki/Floating-point_arithmetic][floating-point arithmetic]] and [[https://en.wikipedia.org/wiki/Vector_processor][vector processing]] support.  The [[https://en.wikipedia.org/wiki/OpenRISC_1200][OpenRISC 1200]] implementation of this specification was designed by Damjan Lampret in 2000, written in the [[https://en.wikipedia.org/wiki/Verilog][Verilog]] [[https://en.wikipedia.org/wiki/Hardware_description_language][hardware description language]] (HDL).  The later mor1kx implementation, which has some advantages compared to the OR 1200, was designed by Julius Baxter and is also written in Verilog.  Software simulators also exist which implement the OR1k specification.

  The hardware design was released under the [[https://en.wikipedia.org/wiki/GNU_Lesser_General_Public_License][GNU Lesser General Public License]] (LGPL), while the models and firmware were released under the [[https://en.wikipedia.org/wiki/GNU_General_Public_License][GNU General Public License]] (GPL).

  A reference [[https://en.wikipedia.org/wiki/System_on_a_chip][system on a chip]] (SoC) implementation based on the OpenRISC 1200 was developed, named the /OpenRISC Reference Platform System-on-Chip/ (ORPSoC).  Several groups have demonstrated ORPSoC and other OR1200 based designs running on [[https://en.wikipedia.org/wiki/Field-programmable_gate_array][field-programmable gate arrays]] (FPGAs), and there have been several commercial derivatives produced.

  Later SoC designs, also based on an OpenRisc 1000 CPU implementation, are minSoC, OpTiMSoC and MiSoC.
#+end_quote
