:PROPERTIES:
:ID:       bda7a980-3a6c-4007-b46d-16afdc818a19
:END:
#+title: The Cathedral and the Bazaar: Musings on Linux and Open Source by an Accidental Revolutionary (CatB) by Eric S. Raymond
#+filetags: :opinion:philosophy:essay:software_development:open_source:books:

Book—and included essay by the same name—on the [[id:a3c19488-876c-4b17-81c0-67b9c7fc64ee][open-source]] movement, software development model, and societal role and impact by [[id:cece95ac-f1fe-4837-929c-9c21ef7f6f6c][Eric S. Raymond]].
* (www.catb.org) The Cathedral and the Bazaar                       :website:
:PROPERTIES:
:ID:       ad5e6f91-3140-4b30-9cdc-739f5056a297
:ROAM_REFS: http://www.catb.org/esr/writings/cathedral-bazaar/
:END:
#+begin_quote
  * The Cathedral and the Bazaar

  This directory gives you access to almost all of the contents of my evolving book, The Cathedral and the Bazaar.  Enjoy --- but be aware that I have sold O'Reilly the exclusive commercial printing rights.

  The papers composing this book (like their topic) are still evolving as I get more feedback.  I made extensive revisions and additions for the first edition of the book The Cathedral and the Bazaar, and expect to continue adding and revising in future editions.  Even if you've heard me do the stand-up version, you may want to reread it.

  These papers are not `finished', and may never be.  Publishing a theory should not be the end of one's conversation with the universe, but the beginning.  I welcome feedback, suggestions, and corrections and will incorporate them into future versions.

  If you like these papers, you will probably also enjoy my [[http://www.catb.org/~esr/faqs/hacker-howto.html][How To Become A Hacker]] FAQ (also in the book).
#+end_quote
** (www.catb.org) Why You Should Care
:PROPERTIES:
:ID:       21868ece-82db-4336-b491-7750b47a4647
:ROAM_REFS: http://www.catb.org/esr/writings/cathedral-bazaar/introduction/
:END:

#+begin_quote
  The book in your hands is about the behavior and culture of computer hackers.  It collects a series of essays originally meant for programmers and technical managers.  The obvious (and entirely fair) question for you, the potential reader, to ask is: ``Why should I care?''
#+end_quote
** (www.catb.org) A Brief History of Hackerdom
:PROPERTIES:
:ID:       f5523f4a-31f5-4d3e-a577-cb131cbeac7c
:ROAM_REFS: http://www.catb.org/esr/writings/cathedral-bazaar/hacker-history/
:END:

#+begin_quote
  *Abstract*

  I explore the origins of the hacker culture, including prehistory among the Real Programmers, the glory days of the MIT hackers, and how the early ARPAnet nurtured the first network nation.  I describe the early rise and eventual stagnation of Unix, the new hope from Finland, and how `the last true hacker' became the next generation's patriarch.  I sketch the way Linux and the mainstreaming of the Internet brought the hacker culture from the fringes of public consciousness to its current prominence.
#+end_quote
** (www.catb.org) Homesteading the Noosphere
:PROPERTIES:
:ID:       e8f27afa-2046-42fd-9fe3-19472e8df7ba
:ROAM_REFS: http://www.catb.org/esr/writings/cathedral-bazaar/homesteading/
:END:

#+begin_quote
  *Abstract*

  After observing a contradiction between the official ideology defined by open-source licenses and the actual behavior of hackers, I examine the actual customs that regulate the ownership and control of open-source software.  I show that they imply an underlying theory of property rights homologous to the Lockean theory of land tenure.  I then relate that to an analysis of the hacker culture as a `gift culture' in which participants compete for prestige by giving time, energy, and creativity away.  Finally, I examine the consequences of this analysis for conflict resolution in the culture, and develop some prescriptive implications.
#+end_quote
** (www.catb.org) The Magic Cauldron
:PROPERTIES:
:ID:       b95c138e-1b8f-4e39-be32-19953d7e9ad1
:ROAM_REFS: http://www.catb.org/esr/writings/cathedral-bazaar/magic-cauldron/
:END:

#+begin_quote
  *Abstract*

  This essay analyzes the evolving economic substrate of the open-source phenomenon.  I first explode some prevalent myths about the funding of program development and the price structure of software.  I then present a game-theory analysis of the stability of open-source cooperation.  I present nine models for sustainable funding of open-source development; two non-profit, seven for-profit.  I then continue to develop a qualitative theory of when it is economically rational for software to be closed.  I then examine some novel additional mechanisms the market is now inventing to fund for-profit open-source development, including the reinvention of the patronage system and task markets.  I conclude with some tentative predictions of the future.
#+end_quote
*** (www.catb.org) Open Source and Strategic Business Risk
:PROPERTIES:
:ID:       7574a75f-9a93-43fb-b812-5c39525dcf2b
:ROAM_REFS: http://www.catb.org/esr/writings/cathedral-bazaar/magic-cauldron/ar01s12.html
:END:

Quite possibly the most important, and yet overlooked, parts of the entire [[id:bda7a980-3a6c-4007-b46d-16afdc818a19][CatB]] book.  It deals with the interactions between [[id:a3c19488-876c-4b17-81c0-67b9c7fc64ee][open-source]] and strategic-risk, due to vendor lock-in, in [[id:4b177854-1711-41a2-8ef0-7a2208174234][business]]; though, it applies to anyone who cares about being locked into a position where they lack control over software they depend on and are invested in using; whether that investment is from resources tied up in a single platform or from personal investment in learning to use a platform—either of which introduce a [[id:6868109a-df4e-47db-8776-d5d897018f76][switching cost]] through an exit cost or entrance cost, respectively.

#+begin_quote
  ** Open Source and Strategic Business Risk

  Ultimately, the reasons open source seems destined to become a widespread practice have more to do with customer demand and market pressures than with supply-side efficiencies for vendors.  I have already discussed, from the vendor's point of view, the effects of customer demand for reliability and for infrastructure with no single dominant player, and how these have played out historically in the evolution of networking.  There is more to be said, though, about the behavior of customers in a market where open source is a factor.

  Put yourself for the moment in the position of a CTO at a Fortune 500 corporation contemplating a build or upgrade of your firm's IT infrastructure.  Perhaps you need to choose a network operating system to be deployed enterprise-wide; perhaps your concerns involve 24/7 web service and e-commerce; perhaps your business depends on being able to field high-volume, high-reliability transaction databases.

  Suppose you go the conventional closed-source route.  If you do, then you put your firm at the mercy of a supplier monopoly—because by definition, there is only one place you can go for support, bug fixes, and enhancements.  If the supplier doesn't perform, you will have no effective recourse because you are effectively locked in by your initial investment and training costs.  Your supplier knows this.  Under these circumstances, do you suppose the software will change to meet /your/ needs and /your/ business plan...or your /supplier's/ needs and your /supplier's/ business plan?

  The brutal truth is this: when your key business processes are executed by opaque blocks of bits that you can't even see inside (let alone modify) /you have lost control of your business/.  You need your supplier more than your supplier needs you—and you will pay, and pay, and pay again for that power imbalance.  You'll pay in higher prices, you'll pay in lost opportunities, and you'll pay in lock-in that grows worse over time as the supplier (who has refined its game on a lot of previous victims) tightens its hold.

  Contrast this with the open-source choice.  If you go that route, /you have the source code/, and no one can take it away from you.  Instead of a supplier monopoly with a chokehold on your business, you now have multiple service companies bidding for your business—and you not only get to play them against each other, you have the option of building your own captive support organization if that looks less expensive than contracting out.  The market works for /you/.

  The logic is compelling; depending on closed source code is an unacceptable strategic business risk.  So much so that I believe it will not be very long until closed-source single-vendor acquisitions when there is an open-source alternative available will be viewed as actual fiduciary irresponsibility, and rightly grounds for a shareholder lawsuit.
#+end_quote
** (www.catb.org) Revenge of the Hackers
:PROPERTIES:
:ID:       91b745ce-f50a-4b08-aff3-cdeeefcc1130
:ROAM_REFS: http://www.catb.org/esr/writings/cathedral-bazaar/hacker-revenge/
:END:

#+begin_quote
  *Abstract*

  The eruption of open-source software into the mainstream in 1998 was the revenge of the hackers after 20 years of marginalization.  I found myself semi-accidentally cast as chief rabble-rouser and propagandist.  In this essay, I describe the tumultuous year that followed, focusing on the media stategy and language we used to break through to the Fortune 500.  I finish with a look at where the trend curves are going.
#+end_quote
** (www.catb.org) Afterword: Beyond Software?
:PROPERTIES:
:ID:       e7863b6a-41f7-4318-a7b7-efa6191374f9
:ROAM_REFS: http://www.catb.org/esr/writings/cathedral-bazaar/afterword/
:END:

#+begin_quote
  The essays in this book were a beginning, but they are not an end.  There are many questions not yet resolved about open-source software.  And there are many questions about other kinds of creative work and intellectual property that the open-source phenomenon raises, but does not really suggest a good answer for.
#+end_quote
* (en.wikipedia.org) The Cathedral and the Bazaar - Wikipedia       :website:
:PROPERTIES:
:ID:       e5f4effa-4e43-407c-838e-f56dae0e41e6
:ROAM_REFS: https://en.wikipedia.org/wiki/The_Cathedral_and_the_Bazaar
:END:

#+begin_quote
  /*The Cathedral and the Bazaar: Musings on Linux and Open Source by an Accidental Revolutionary*/ (abbreviated /*CatB*/) is an essay, and later a book, by [[https://en.wikipedia.org/wiki/Eric_S._Raymond][Eric S. Raymond]] on [[https://en.wikipedia.org/wiki/Software_engineering][software engineering]] methods, based on his observations of the [[https://en.wikipedia.org/wiki/Linux_kernel][Linux kernel]] development process and his experiences managing an [[https://en.wikipedia.org/wiki/Open-source_model][open source]] project, [[https://en.wikipedia.org/wiki/Fetchmail][fetchmail]].  It examines the struggle between [[https://en.wikipedia.org/wiki/Top-down_and_bottom-up_design][top-down and bottom-up design]].  The essay was first presented by Raymond at the [[https://en.wikipedia.org/wiki/Linux_Kongress][Linux Kongress]] on May 27, 1997, in [[https://en.wikipedia.org/wiki/Würzburg,_Germany][Würzburg, Germany]], and was published as the second chapter of the same‑titled book in 1999.

  The illustration on the cover of the book is a 1913 painting by [[https://en.wikipedia.org/wiki/Lyubov_Popova#Development_of_style:_Cubo-Futurism][Lyubov Popova]] titled /Composition with Figures/ and belongs to the collection of the [[https://en.wikipedia.org/wiki/State_Tretyakov_Gallery][State Tretyakov Gallery]].  The book was released under the [[https://en.wikipedia.org/wiki/Open_Publication_License][Open Publication License]] v2.0 in 1999.
#+end_quote
* (www.goodreads.com) The Cathedral & the Bazaar : Musings on Linux and Open Source by an Accidental Revolutionary by Eric S. Raymond | Goodreads :website:
:PROPERTIES:
:ID:       418b9497-f2a8-4ec5-b676-324c4cad8d20
:ROAM_REFS: https://www.goodreads.com/book/show/33053
:END:

#+begin_quote
  * The Cathedral & the Bazaar : Musings on Linux and Open Source by an Accidental Revolutionary

  Open source provides the competitive advantage in the Internet Age.  According to the August Forrester Report, 56 percent of IT managers interviewed at Global 2,500 companies are already using some type of open source software in their infrastructure and another 6 percent will install it in the next two years.  This revolutionary model for collaborative software development is being embraced and studied by many of the biggest players in the high-tech industry, from Sun Microsystems to IBM to Intel.  The Cathedral & the Bazaar is a must for anyone who cares about the future of the computer industry or the dynamics of the information economy.  Already, billions of dollars have been made and lost based on the ideas in this book.  Its conclusions will be studied, debated, and implemented for years to come.  According to Bob Young, "This is Eric Raymond's great contribution to the success of the open source revolution, to the adoption of Linux-based operating systems, and to the success of open source users and the companies that supply them."The interest in open source software development has grown enormously in the past year.  This revised and expanded hardback edition includes new material on open source developments in 1999 and 2000.  Raymond's clear and effective writing style accurately describing the benefits of open source software has been key to its success.  With major vendors creating acceptance for open source within companies, independent vendors will become the open source story in 2001.
#+end_quote
* (books.google.com) The Cathedral & the Bazaar: Musings on Linux and Open Source by an ... - Eric S. Raymond - Google Books :website:
:PROPERTIES:
:ID:       c9f6a393-a466-438b-8ae6-35c385afb276
:ROAM_REFS: https://books.google.com/books?id=F6qgFtLwpJgC
:END:

#+begin_quote
  * The Cathedral & the Bazaar: Musings on Linux and Open Source by an Accidental Revolutionary

  Eric S. Raymond

  "O'Reilly Media, Inc.", Feb 1, 2001 - Computers - 258 pages

  Open source provides the competitive advantage in the Internet Age.  According to the August Forrester Report, 56 percent of IT managers interviewed at Global 2,500 companies are already using some type of open source software in their infrastructure and another 6 percent will install it in the next two years.  This revolutionary model for collaborative software development is being embraced and studied by many of the biggest players in the high-tech industry, from Sun Microsystems to IBM to Intel.The Cathedral & the Bazaar is a must for anyone who cares about the future of the computer industry or the dynamics of the information economy.  Already, billions of dollars have been made and lost based on the ideas in this book.  Its conclusions will be studied, debated, and implemented for years to come.  According to Bob Young, "This is Eric Raymond's great contribution to the success of the open source revolution, to the adoption of Linux-based operating systems, and to the success of open source users and the companies that supply them."The interest in open source software development has grown enormously in the past year.  This revised and expanded paperback edition includes new material on open source developments in 1999 and 2000.  Raymond's clear and effective writing style accurately describing the benefits of open source software has been key to its success.  With major vendors creating acceptance for open source within companies, independent vendors will become the open source story in 2001.

  ** Bibliographic information

  Title: The Cathedral & the Bazaar: Musings on Linux and Open Source by an Accidental Revolutionary

  Author: Eric S. Raymond

  Edition: revised

  Publisher: "O'Reilly Media, Inc.", 2001

  ISBN: 059655396X, 9780596553968

  Length: 258 pages

  Subjects: Computers › Internet › General

  - Computers / General
  - Computers / Human-Computer Interaction (HCI)
  - Computers / Information Technology
  - Computers / Information Theory
  - Computers / Internet / General
  - Computers / Operating Systems / Linux
  - Computers / Operating Systems / UNIX
  - Computers / Programming / General
  - Computers / Social Aspects
#+end_quote
