:PROPERTIES:
:ID:       c46eea5e-e2d2-4a21-bafe-74b6751292d2
:END:
#+title: C (Programming Language)
#+filetags: :c_lang:programming:programming_language:computer_science:

The C [[id:b24601aa-09df-41e1-aa7e-25ead342db34][programming language]] designed by [[id:42a22d7b-4dfd-46a8-9e7d-0ee2bb4a52ec][Dennis M. Ritchie]] for the [[id:b7ffa33f-6da2-4918-9ced-6afd0fbdb0fe][Unix]] [[id:412bbcad-6c00-4f13-b748-d1ffde0588e1][operating system]].  Formed the basis of the [[id:5c1e66dd-65de-4e8d-9f7d-077a352af8ab][C++ (Programming Language)]].
* (en.wikipedia.org) C (programming language) - Wikipedia           :website:
:PROPERTIES:
:ID:       8e1fdf54-d7a1-459e-b995-b173f8214106
:ROAM_REFS: https://en.wikipedia.org/wiki/C_(programming_language)
:END:

#+begin_quote
  *C* (/pronounced/ [[https://en.wikipedia.org/wiki/Help:IPA/English][/ˈsiː/]] /-- like the letter [[https://en.wikipedia.org/wiki/C][c]]/) is a [[https://en.wikipedia.org/wiki/General-purpose_programming_language][general-purpose programming language]].  It was created in the 1970s by [[https://en.wikipedia.org/wiki/Dennis_Ritchie][Dennis Ritchie]] and remains very widely used and influential.  By design, C's features cleanly reflect the capabilities of the targeted [[https://en.wikipedia.org/wiki/Central_processing_unit][CPUs]].  It has found lasting use in [[https://en.wikipedia.org/wiki/Operating_system][operating systems]] code (especially in [[https://en.wikipedia.org/wiki/Kernel_(operating_system)][kernels]]), [[https://en.wikipedia.org/wiki/Device_driver][device drivers]], and [[https://en.wikipedia.org/wiki/Protocol_stack][protocol stacks]], but its use in [[https://en.wikipedia.org/wiki/Application_software][application software]] has been decreasing.  C is commonly used on computer architectures that range from the largest [[https://en.wikipedia.org/wiki/Supercomputer][supercomputers]] to the smallest [[https://en.wikipedia.org/wiki/Microcontroller][microcontrollers]] and [[https://en.wikipedia.org/wiki/Embedded_system][embedded systems]].

  A successor to the programming language [[https://en.wikipedia.org/wiki/B_(programming_language)][B]], C was originally developed at [[https://en.wikipedia.org/wiki/Bell_Labs][Bell Labs]] by Ritchie between 1972 and 1973 to construct utilities running on [[https://en.wikipedia.org/wiki/Unix][Unix]].  It was applied to re-implementing the kernel of the Unix operating system.  During the 1980s, C gradually gained popularity.  It has become one of the most widely used [[https://en.wikipedia.org/wiki/Programming_language][programming languages]], with C [[https://en.wikipedia.org/wiki/Compiler][compilers]] available for practically all modern [[https://en.wikipedia.org/wiki/Computer_architecture][computer architectures]] and [[https://en.wikipedia.org/wiki/Operating_system][operating systems]].  The book /[[https://en.wikipedia.org/wiki/The_C_Programming_Language][The C Programming Language]]/, co-authored by the original language designer, served for many years as the /de facto/ standard for the language.  C has been standardized since 1989 by the [[https://en.wikipedia.org/wiki/American_National_Standards_Institute][American National Standards Institute]] (ANSI) and, subsequently, jointly by the [[https://en.wikipedia.org/wiki/International_Organization_for_Standardization][International Organization for Standardization]] (ISO) and the [[https://en.wikipedia.org/wiki/International_Electrotechnical_Commission][International Electrotechnical Commission]] (IEC).

  C is an [[https://en.wikipedia.org/wiki/Imperative_programming][imperative]] [[https://en.wikipedia.org/wiki/Procedural_programming][procedural]] language, supporting [[https://en.wikipedia.org/wiki/Structured_programming][structured programming]], [[https://en.wikipedia.org/wiki/Lexical_variable_scope][lexical variable scope]], and [[https://en.wikipedia.org/wiki/Recursion_(computer_science)][recursion]], with a [[https://en.wikipedia.org/wiki/Static_type_system][static type system]].  It was designed to be [[https://en.wikipedia.org/wiki/Compiled][compiled]] to provide [[https://en.wikipedia.org/wiki/Low-level_programming_language][low-level]] access to [[https://en.wikipedia.org/wiki/Computer_memory][memory]] and language constructs that map efficiently to [[https://en.wikipedia.org/wiki/Machine_instructions][machine instructions]], all with minimal [[https://en.wikipedia.org/wiki/Runtime_system][runtime support]].  Despite its low-level capabilities, the language was designed to encourage cross-platform programming.  A [[https://en.wikipedia.org/wiki/Specification_(technical_standard)][standards]]-compliant C program written with [[https://en.wikipedia.org/wiki/Software_portability][portability]] in mind can be compiled for a wide variety of computer platforms and operating systems with few changes to its source code.

  Since 2000, C has consistently ranked among the top four languages in the [[https://en.wikipedia.org/wiki/TIOBE_index][TIOBE index]], a measure of the popularity of programming languages.
#+end_quote
