:PROPERTIES:
:ID:       0f3ffe6d-ecc8-4b64-acd1-bcbf02159f53
:END:
#+title: SGML (Standard Generalized Markup Language)
#+filetags: :file_formats:markup:

A standardized data markup language.  Most commonly used in the form of [[id:fe3afedb-9d76-4c36-a529-3dfc6709f995][HTML]] and [[id:17fb5de5-dedc-46ce-a5ed-dd67f3ce9f27][XML]].
* (en.wikipedia.org) Standard Generalized Markup Language - Wikipedia :website:
:PROPERTIES:
:ID:       7266b31f-0f99-48c2-b61b-fd0364ab9f9e
:ROAM_REFS: https://en.wikipedia.org/wiki/Standard_Generalized_Markup_Language
:END:

#+begin_quote
  The *Standard Generalized Markup Language* (*SGML*; [[https://en.wikipedia.org/wiki/International_Organization_for_Standardization][ISO]] 8879:1986) is a standard for defining generalized [[https://en.wikipedia.org/wiki/Markup_language][markup languages]] for documents.  ISO 8879 Annex A.1 states that generalized markup is "based on two [[https://en.wikipedia.org/wiki/Postulate][postulates]]":

  - Declarative: Markup should describe a document's structure and other attributes rather than specify the processing that needs to be performed, because it is less likely to conflict with future developments.
  - Rigorous: In order to allow markup to take advantage of the techniques available for processing, markup should rigorously define objects like programs and [[https://en.wikipedia.org/wiki/Database][databases]].

  [[https://en.wikipedia.org/wiki/DocBook][DocBook]] SGML and [[https://en.wikipedia.org/wiki/LinuxDoc][LinuxDoc]] are examples which used SGML tools.
#+end_quote
