:PROPERTIES:
:ID:       6959fcfb-f0c3-422f-bce0-9e9103888602
:END:
#+title: The Garbage Collection Handbook
#+filetags: :programming_language_design:programming:computer_science:books:

Popular book on [[id:f21c5506-6fef-4e8c-8116-162f1864d4d8][garbage collection]] techniques and algorithms.
* (gchandbook.org) The Garbage Collection Handbook                  :website:
:PROPERTIES:
:ID:       85daf22a-694b-400a-9457-bdfff47c90ec
:ROAM_REFS: https://gchandbook.org/
:END:

#+begin_quote
  * Second edition

  Richard Jones's [[http://www.cs.kent.ac.uk/~rej/gcbook][/Garbage Collection/]] (Wiley, 1996) was a milestone book in the area of automatic memory management.  Its widely acclaimed successor, [[http://www.amazon.com/gp/offer-listing/1420082795/ref=as_li_tf_til?tag=richardjones&camp=14573&creative=327641&linkCode=am1&creativeASIN=1420082795&adid=1Z2BCHD02FFZWC0TK9CQ][/The Garbage Collection Handbook: The Art of Automatic Memory Management/]] captured the state of the field in 2012.  However, technology developments have made memory management more challenging, interesting and important than ever.  This second edition updates the handbook, bringing together a wealth of knowledge gathered by automatic memory management researchers and developers over the past sixty years.  The authors compare the most important approaches and state-of-the-art techniques in a single, accessible framework.

  The book addresses new challenges to garbage collection made by recent advances in hardware and software, and the environments in which programs are executed.  It explores the consequences of these changes for designers and implementers of high performance garbage collectors.  Along with simple and traditional algorithms, the book covers state-of-the-art parallel, incremental, concurrent and real-time garbage collection.  Algorithms and concepts are often described with pseudocode and illustrations.

  The nearly universal adoption of garbage collection by modern programming languages makes a thorough understanding of this topic essential for any programmer.  This authoritative handbook gives expert insight on how different collectors work as well as the various issues currently facing garbage collectors.  Armed with this knowledge, programmers can confidently select and configure the many choices of garbage collectors.

  ** Features of the book

  - Provides a complete, up-to-date, and authoritative sequel to the 1996 and 2012 books
  - Offers thorough coverage of parallel, concurrent and real-time garbage collection algorithms
  - Discusses in detail modern, high-performance commercial collectors
  - Explains some of the tricky aspects of garbage collection, including the interface to the run-time system
  - Over 90 more pages, including new chapters on persistence and energy-aware garbage collection
  - Backed by a comprehensive online database of nearly 3,400 garbage collection-related publications

  ** e-book and translations

  The [[https://gchandbook.org/editions.html][e-book]] enhances the print versions with a rich collection of over 37,000 hyperlinks to chapters, sections, algorithms, figures, glossary entries, index items, original research papers and much more.

  [[https://gchandbook.org/editions.html][Chinese and Japanese translations]] of the first edition were published in 2016.  We thank the translators for their work in bringing our book to a wider audience.

  ** Web Resources

  The [[http://www.cs.kent.ac.uk/~rej/gcbib][online bibliographic database]] includes nearly 3,400 garbage collection-related publications.  It contains abstracts for some entries and URLs or DOIs for most of the electronically available ones, and is continually being updated.  The database can be searched online, or downloaded as [[http://www.cs.kent.ac.uk/~rej/gcbib/gcbib.bib.gz][BibTeX]], [[http://www.cs.kent.ac.uk/~rej/gcbib/gcbib.ps.gz][PostScript]] or [[http://www.cs.kent.ac.uk/~rej/gcbib/gcbib.pdf][PDF]].
#+end_quote
