:PROPERTIES:
:ID:       66359bb4-b600-4bd5-b979-e248585c5691
:END:
#+title: Steganography
#+filetags: :steganography:
* (en.wikipedia.org) Steganography - Wikipedia                      :website:
:PROPERTIES:
:ID:       6c287e10-b769-4ed5-9320-52cbc0821610
:ROAM_REFS: https://en.wikipedia.org/wiki/Steganography
:END:

#+begin_quote
  *Steganography* (/ˌstɛɡəˈnɒɡrəfi/) is the practice of representing information within another message or physical object, in such a manner that the presence of the concealed information would not be evident to an unsuspecting person's examination.  In computing/electronic contexts, a [[https://en.wikipedia.org/wiki/Computer_file][computer file]], message, image, or video is concealed within another file, message, image, or video.  The word /steganography/ comes from [[https://en.wikipedia.org/wiki/Greek_language][Greek]] /steganographia/, which combines the words /steganós/ ([[https://en.wiktionary.org/wiki/στεγανός#Greek][στεγανός]]), meaning "covered or concealed", and /-graphia/ ([[https://en.wiktionary.org/wiki/γραφή#Greek][γραφή]]) meaning "writing".

  The first recorded use of the term was in 1499 by [[https://en.wikipedia.org/wiki/Johannes_Trithemius][Johannes Trithemius]] in his /[[https://en.wikipedia.org/wiki/Steganographia][Steganographia]]/, a treatise on [[https://en.wikipedia.org/wiki/Cryptography][cryptography]] and steganography, disguised as a book on magic.  Generally, the hidden messages appear to be (or to be part of) something else: images, articles, shopping lists, or some other cover text.  For example, the hidden message may be in [[https://en.wikipedia.org/wiki/Invisible_ink][invisible ink]] between the visible lines of a private letter.  Some implementations of steganography that lack a formal [[https://en.wikipedia.org/wiki/Shared_secret][shared secret]] are forms of [[https://en.wikipedia.org/wiki/Security_through_obscurity][security through obscurity]], while key-dependent steganographic schemes try to adhere to [[https://en.wikipedia.org/wiki/Kerckhoffs's_principle][Kerckhoffs's principle]].

  The advantage of steganography over cryptography alone is that the intended secret message does not attract attention to itself as an object of scrutiny.  Plainly visible [[https://en.wikipedia.org/wiki/Encrypted][encrypted]] messages, no matter how unbreakable they are, arouse interest and may in themselves be incriminating in countries in which encryption is illegal.  Whereas cryptography is the practice of protecting the contents of a message alone, steganography is concerned with concealing both the fact that a secret message is being sent /and/ its contents.

  Steganography includes the concealment of information within computer files.  In digital steganography, electronic communications may include steganographic coding inside of a transport layer, such as a document file, image file, program, or protocol.  Media files are ideal for steganographic transmission because of their large size.  For example, a sender might start with an innocuous image file and adjust the color of every hundredth [[https://en.wikipedia.org/wiki/Pixel][pixel]] to correspond to a letter in the alphabet.  The change is so subtle that someone who is not specifically looking for it is unlikely to notice the change.
#+end_quote
