:PROPERTIES:
:ID:       dcd7f214-ab27-4a85-931d-68151fdf019f
:END:
#+title: ditaa
#+filetags: :open_source:diagramming:software:

[[id:a3c19488-876c-4b17-81c0-67b9c7fc64ee][Open-source]], CLI ASCII art to image [[id:d305645c-9440-454e-bfd1-d5d4e25027b0][diagram]] tool.
* (ditaa.sourceforge.net) ditaa                                     :website:
:PROPERTIES:
:ID:       a0d60a88-82cc-439c-b754-d4bf3260dc18
:ROAM_REFS: https://ditaa.sourceforge.net/
:END:

#+begin_quote
  [[https://ditaa.sourceforge.net/null][*DIagrams Through Ascii Art*]]

  [[https://ditaa.sourceforge.net/null][*by Stathis Sideris*]]

  (((-[[https://ditaa.sourceforge.net/#intro][intro]]-))) (((-[[https://ditaa.sourceforge.net/#download][download]]-))) (((-[[https://ditaa.sourceforge.net/#usage][usage and syntax]]-))) (((-[[https://ditaa.sourceforge.net/#friends][friends]]-))) (((-[[https://ditaa.sourceforge.net/#contact][contact]]-)))

  ditaa is a small command-line utility written in Java, that can convert diagrams drawn using ascii art ('drawings' that contain characters that resemble lines like =| / - =), into proper bitmap graphics.  This is best illustrated by the following example -- which also illustrates the benefits of using ditaa in comparison to other methods :)

  #+name: first
  #+begin_example
      +--------+   +-------+    +-------+
      |        | --+ ditaa +--> |       |
      |  Text  |   +-------+    |diagram|
      |Document|   |!magic!|    |       |
      |     {d}|   |       |    |       |
      +---+----+   +-------+    +-------+
          :                         ^
          |       Lots of work      |
          +-------------------------+
  #+end_example
  After conversion using ditaa, the above file becomes:\\
  https://ditaa.sourceforge.net/images/first.png

  ditaa interprets ascci art as a series of open and closed shapes, but it also uses special markup syntax to increase the possibilities of shapes and symbols that can be rendered.

  ditaa is open source and free software (/free/ as in free speech), since it is released under the GPL license.
#+end_quote
