:PROPERTIES:
:ID:       b7fe46b5-84f5-494e-9442-b356d8a44c15
:END:
#+title: BPF (Berkeley Packet Filter)
#+filetags: :linux:networking:

[[id:bf0bc2d7-17df-413c-823b-93904faffc58][Linux]] network handling using a VM and JIT.  See also [[id:db8ba741-6ba2-4abc-9d8d-2b56cde53985][eBPF]].
* (en.wikipedia.org) Berkeley Packet Filter - Wikipedia             :website:
:PROPERTIES:
:ID:       3877b5b9-16da-403e-a4aa-4a55cc992e10
:ROAM_REFS: https://en.wikipedia.org/wiki/Berkeley_Packet_Filter
:END:

#+begin_quote
  The *Berkeley Packet Filter* (*BPF*; also *BSD Packet Filter*, *classic BPF* or *cBPF*) is a [[https://en.wikipedia.org/wiki/Network_tap][network tap]] and [[https://en.wikipedia.org/wiki/Packet_filter][packet filter]] which permits computer [[https://en.wikipedia.org/wiki/Network_packet][network packets]] to be captured and filtered at the [[https://en.wikipedia.org/wiki/Operating_system][operating system]] level.  It provides a raw interface to [[https://en.wikipedia.org/wiki/Data_link_layer][data link layers]], permitting raw link-layer packets to be sent and received,  and allows a [[https://en.wikipedia.org/wiki/Userspace][userspace]] [[https://en.wikipedia.org/wiki/Process_(computing)][process]] to supply a filter program that specifies which packets it wants to receive.  For example, a [[https://en.wikipedia.org/wiki/Tcpdump][tcpdump]] process may want to receive only packets that initiate a TCP connection.  BPF returns only packets that pass the filter that the process supplies.  This avoids copying unwanted packets from the [[https://en.wikipedia.org/wiki/Operating_system][operating system]] [[https://en.wikipedia.org/wiki/Kernel_(computer_science)][kernel]] to the process, greatly improving performance.  The filter program is in the form of instructions for a [[https://en.wikipedia.org/wiki/Virtual_machine][virtual machine]], which are interpreted, or compiled into machine code by a [[https://en.wikipedia.org/wiki/Just-in-time_compilation][just-in-time]] (JIT) mechanism and executed, in the kernel.

  BPF is used by programs that need to, among other things, analyze network traffic.  If the driver for the network interface supports [[https://en.wikipedia.org/wiki/Promiscuous_mode][promiscuous mode]], it allows the interface to be put into that mode so that all packets on the [[https://en.wikipedia.org/wiki/Computer_network][network]] can be received, even those destined to other hosts.

  The BPF filtering mechanism is available on most [[https://en.wikipedia.org/wiki/Unix-like][Unix-like]] operating systems.  BPF is sometimes used to refer to just the filtering mechanism, rather than to the entire interface.  Some systems, such as [[https://en.wikipedia.org/wiki/Linux][Linux]] and [[https://en.wikipedia.org/wiki/Tru64_UNIX][Tru64 UNIX]], provide a raw interface to the data link layer other than the BPF raw interface but use the BPF filtering mechanisms for that raw interface.

  The Linux kernel provides an extended version of the BPF filtering mechanism, called [[https://en.wikipedia.org/wiki/EBPF][eBPF]], which uses a JIT mechanism, and which is used for packet filtering, as well as for other purposes in the kernel.  eBPF is also available for [[https://en.wikipedia.org/wiki/Microsoft_Windows][Microsoft Windows]].
#+end_quote
