:PROPERTIES:
:ID:       afed701e-fc95-4581-9a5f-5600664c07d2
:END:
#+title: DEI (Diversity Equity and Inclusion)
#+filetags: :diversity_equity_inclusion:organizational_frameworks:management:initiatives:

Organizational framework and initiative to increase diversity and representation within organizations.
* (en.wikipedia.org) Diversity, equity, and inclusion - Wikipedia   :website:
:PROPERTIES:
:ID:       10c0e550-ddc6-41df-b5e7-4b8eba80b275
:ROAM_REFS: https://en.wikipedia.org/wiki/Diversity,_equity,_and_inclusion
:END:

#+begin_quote
  In the [[https://en.wikipedia.org/wiki/United_States][United States]], *diversity, equity, and inclusion* (*DEI*) are organizational frameworks that seek to promote the fair treatment and full participation of all people, particularly groups who have historically been underrepresented or subject to [[https://en.wikipedia.org/wiki/Discrimination][discrimination]] based on [[https://en.wikipedia.org/wiki/Identity_(social_science)][identity]] or [[https://en.wikipedia.org/wiki/Disability][disability]].  These three notions ([[https://en.wikipedia.org/wiki/Diversity_(politics)][diversity]], [[https://en.wikipedia.org/wiki/Social_equity][equity]], and [[https://en.wikipedia.org/wiki/Social_exclusion#Social_inclusion][inclusion]]) together represent "three closely linked values" which organizations seek to institutionalize through DEI frameworks.  The concepts predate this terminology and other variations sometimes include terms such as *belonging*, *justice*, and *accessibility*.  As such, frameworks such as *inclusion and diversity* (*I&D*), *diversity, equity, inclusion and belonging* (*DEIB*), *justice, equity, diversity and inclusion* (*JEDI* or *EDIJ*), or *diversity, equity, inclusion and accessibility* (*IDEA*, *DEIA* or *DEAI*) exist.  In the [[https://en.wikipedia.org/wiki/United_Kingdom][United Kingdom]], the term *equality, diversity, and inclusion* (*EDI*) is used in a similar way.

  /Diversity/ refers to the presence of variety within the organizational workforce in characteristics such as [[https://en.wikipedia.org/wiki/Gender_identity][gender]], [[https://en.wikipedia.org/wiki/Ethnicity][ethnicity]], [[https://en.wikipedia.org/wiki/Sexual_orientation][sexual orientation]], [[https://en.wikipedia.org/wiki/Disability][disability]], [[https://en.wikipedia.org/wiki/Aging][age]], [[https://en.wikipedia.org/wiki/Cultural_diversity][culture]], [[https://en.wikipedia.org/wiki/Social_class][class]], [[https://en.wikipedia.org/wiki/Veteran][veteran]] status, or [[https://en.wikipedia.org/wiki/Religious_identity][religion]]. /Equity/ refers to concepts of [[https://en.wikipedia.org/wiki/Social_justice][fairness]] and [[https://en.wikipedia.org/wiki/Justice][justice]], such as fair compensation and [[https://en.wikipedia.org/wiki/Substantive_equality][substantive equality]].  More specifically, equity usually also includes a focus on [[https://en.wikipedia.org/wiki/Social_inequality][societal disparities]] and allocating resources and "decision making authority to groups that have historically been disadvantaged", and taking "into consideration a person's unique circumstances, adjusting treatment accordingly so that the end result is equal." Finally, /inclusion/ refers to creating an organizational culture that creates an experience where "all employees feel their voices will be heard", and a sense of belonging and integration.

  DEI often describes certain training efforts, such as [[https://en.wikipedia.org/wiki/Diversity_training][diversity training]].  Although DEI is best known as a form of [[https://en.wikipedia.org/wiki/Corporate][corporate]] training, it also finds implementation within many types of organizations, such as within [[https://en.wikipedia.org/wiki/Academia][academia]], [[https://en.wikipedia.org/wiki/School][schools]], and hospitals.  Into the 2020s, DEI efforts and policies have generated criticism and controversy, some directed at the specific effectiveness of its tools, such as diversity training, and its effect on free speech and academic freedom, as well as more broadly attracting criticism on political or philosophical grounds.  In addition, the term "DEI" has gained traction as an [[https://en.wikipedia.org/wiki/Ethnic_slur][ethnic slur]] towards minority groups in the United States.
#+end_quote
