:PROPERTIES:
:ID:       efd4f0a8-71b6-4a15-8109-60d9d51f1f0a
:END:
#+title: Bell Labs
#+filetags: :research:organization:

Research and development organization originally a division of Western Electric, later Western Electric and AT&T, then just AT&T, and eventually acquired by Nokia.  Mostly known for the research done at the organization in the 1960s, 70s, and 80s under Western Electric and AT&T.
* (en.wikipedia.org) Bell Labs - Wikipedia                          :website:
:PROPERTIES:
:ID:       f407a5c2-f7ad-4f5a-9fce-4eae3f580223
:ROAM_REFS: https://en.wikipedia.org/wiki/Bell_Labs
:END:

#+begin_quote
  *Bell Labs* is an American industrial [[https://en.wikipedia.org/wiki/Research_and_development][research and development]] (R&D) [[https://en.wikipedia.org/wiki/Company][company]], currently operating as a subsidiary of Finnish technology company [[https://en.wikipedia.org/wiki/Nokia][Nokia]].  With a long history, Bell Labs is credited with the development of [[https://en.wikipedia.org/wiki/Radio_astronomy][radio astronomy]], the [[https://en.wikipedia.org/wiki/Transistor][transistor]], the [[https://en.wikipedia.org/wiki/Laser][laser]], the [[https://en.wikipedia.org/wiki/Photovoltaic_cell][photovoltaic cell]], the [[https://en.wikipedia.org/wiki/Charge-coupled_device][charge-coupled device]] (CCD), [[https://en.wikipedia.org/wiki/Information_theory][information theory]], the [[https://en.wikipedia.org/wiki/Unix][Unix]] operating system, and the [[https://en.wikipedia.org/wiki/Programming_language][programming languages]] [[https://en.wikipedia.org/wiki/B_(programming_language)][B]], [[https://en.wikipedia.org/wiki/C_(programming_language)][C]], [[https://en.wikipedia.org/wiki/C++][C++]], [[https://en.wikipedia.org/wiki/S_(programming_language)][S]], [[https://en.wikipedia.org/wiki/SNOBOL][SNOBOL]], [[https://en.wikipedia.org/wiki/AWK][AWK]], [[https://en.wikipedia.org/wiki/AMPL][AMPL]], and others, throughout the 20th century.  Eleven [[https://en.wikipedia.org/wiki/Nobel_Prize][Nobel Prizes]] and five [[https://en.wikipedia.org/wiki/Turing_Award][Turing Awards]] have been awarded for work completed at Bell Laboratories.

  The laboratory began in the late 19th century as the [[https://en.wikipedia.org/wiki/Western_Electric][Western Electric]] Engineering Department, located at [[https://en.wikipedia.org/wiki/Bell_Laboratories_Building_(Manhattan)][463 West Street]] in New York City.  After years of conducting research and development under [[https://en.wikipedia.org/wiki/Western_Electric][Western Electric]], a Bell [[https://en.wikipedia.org/wiki/Subsidiary][subsidiary]], the Engineering Department was reformed into Bell Telephone Laboratories in 1925 and placed under the shared ownership of Western Electric and the [[https://en.wikipedia.org/wiki/American_Telephone_and_Telegraph_Company][American Telephone and Telegraph Company]] (AT&T).  In the 1960s, laboratory and company headquarters were moved to [[https://en.wikipedia.org/wiki/Murray_Hill,_New_Jersey][Murray Hill, New Jersey]]. [[https://en.wikipedia.org/wiki/List_of_Bell_Labs_alumni][Its alumni]] during this time include people like [[https://en.wikipedia.org/wiki/William_Shockley][William Shockley]], [[https://en.wikipedia.org/wiki/Dennis_Ritchie][Dennis Ritchie]], [[https://en.wikipedia.org/wiki/Claude_Shannon][Claude Shannon]] and [[https://en.wikipedia.org/wiki/Willard_Boyle][Willard Boyle]].

  Bell Labs became a subsidiary of [[https://en.wikipedia.org/wiki/AT&T_Technologies][AT&T Technologies]] in 1984 after the [[https://en.wikipedia.org/wiki/Breakup_of_the_Bell_System][Bell System was broken up]].  After the breakup, its funding greatly declined.  In 1996, AT&T Technologies was spun off and renamed to Lucent Technologies, who used the Murray Hill site as their headquarters.  Bell Laboratories was split as well, with part of it going to [[https://en.wikipedia.org/wiki/AT&T][AT&T]] as [[https://en.wikipedia.org/wiki/AT&T_Laboratories][AT&T Laboratories]].  In 2006, [[https://en.wikipedia.org/wiki/Lucent_Technologies][Lucent]] merged with French [[https://en.wikipedia.org/wiki/Telecommunications][telecommunications]] company [[https://en.wikipedia.org/wiki/Alcatel][Alcatel]] to form [[https://en.wikipedia.org/wiki/Alcatel-Lucent][Alcatel-Lucent]], which was in turn acquired by [[https://en.wikipedia.org/wiki/Nokia][Nokia]] in 2016.
#+end_quote
