:PROPERTIES:
:ID:       9eb1ccab-a5d8-458c-b532-528551c420ca
:END:
#+title: MIPS
#+filetags: :electronics:processor:microprocessor:computer_architecture:computer_science:

A family if [[id:321ba3cc-d73a-4620-88f7-2527cbae1aac][RISC]] [[id:c980a340-2564-437e-a79f-388122a206ad][ISA]]s and corresponding microprocessors.
* (en.wikipedia.org) MIPS architecture - Wikipedia                  :website:
:PROPERTIES:
:ID:       d02bc40c-bde8-4672-b8bf-c664afff9084
:ROAM_REFS: https://en.wikipedia.org/wiki/MIPS_architecture
:END:

#+begin_quote
  *MIPS* (*Microprocessor without Interlocked Pipelined Stages*) is a family of [[https://en.wikipedia.org/wiki/Reduced_instruction_set_computer][reduced instruction set computer]] (RISC) [[https://en.wikipedia.org/wiki/Instruction_set_architecture][instruction set architectures]] (ISA) developed by MIPS Computer Systems, now [[https://en.wikipedia.org/wiki/MIPS_Technologies][MIPS Technologies]], based in the [[https://en.wikipedia.org/wiki/United_States][United States]].

  There are multiple versions of MIPS, including MIPS I, II, III, IV, and V, as well as five releases of MIPS32/64 (for 32- and 64-bit implementations, respectively).  The early MIPS architectures were 32-bit; 64-bit versions were developed later.  As of April 2017, the current version of MIPS is MIPS32/64 Release 6.  MIPS32/64 primarily differs from MIPS I--V by defining the privileged kernel mode System Control Coprocessor in addition to the user mode architecture.

  The MIPS architecture has several optional extensions: [[https://en.wikipedia.org/wiki/MIPS-3D][MIPS-3D]], a simple set of [[https://en.wikipedia.org/wiki/Floating-point][floating-point]] [[https://en.wikipedia.org/wiki/Instruction_set_architecture#SIMD_instruction][SIMD instructions]] dedicated to [[https://en.wikipedia.org/wiki/3D_computer_graphics][3D computer graphics]]; [[https://en.wikipedia.org/wiki/MDMX][MDMX]] (MaDMaX), a more extensive integer [[https://en.wikipedia.org/wiki/Single_instruction,_multiple_data][SIMD]] instruction set using 64-bit floating-point registers; MIPS16e, which adds [[https://en.wikipedia.org/wiki/Compressed_instructions][compression to the instruction stream]] to reduce the memory programs require; and MIPS MT, which adds [[https://en.wikipedia.org/wiki/Multithreading_(computer_architecture)][multithreading]] capability.

  [[https://en.wikipedia.org/wiki/Computer_architecture][Computer architecture]] courses in universities and technical schools often study the MIPS architecture.  The architecture greatly influenced later RISC architectures such as [[https://en.wikipedia.org/wiki/DEC_Alpha][Alpha]].  In March 2021, MIPS announced that the development of the MIPS architecture had ended as the company is making the transition to [[https://en.wikipedia.org/wiki/RISC-V][RISC-V]].
#+end_quote
* (en.wikipedia.org) Stanford MIPS - Wikipedia                      :website:
:PROPERTIES:
:ID:       86ee3b1b-c387-4b77-9010-61dbdf260b08
:ROAM_REFS: https://en.wikipedia.org/wiki/Stanford_MIPS
:END:

#+begin_quote
  *MIPS*, an acronym for *Microprocessor without Interlocked Pipeline Stages*, was a research project conducted by [[https://en.wikipedia.org/wiki/John_L._Hennessy][John L. Hennessy]] at [[https://en.wikipedia.org/wiki/Stanford_University][Stanford University]] between 1981 and 1984.  MIPS investigated a type of [[https://en.wikipedia.org/wiki/Instruction_set_architecture][instruction set architecture]] (ISA) now called [[https://en.wikipedia.org/wiki/Reduced_instruction_set_computer][reduced instruction set computer]] (RISC), its implementation as a [[https://en.wikipedia.org/wiki/Microprocessor][microprocessor]] with [[https://en.wikipedia.org/wiki/Very_large_scale_integration][very large scale integration]] (VLSI) [[https://en.wikipedia.org/wiki/Semiconductor][semiconductor]] technology, and the effective exploitation of RISC architectures with [[https://en.wikipedia.org/wiki/Optimizing_compiler][optimizing compilers]].  MIPS, together with the [[https://en.wikipedia.org/wiki/IBM_801][IBM 801]] and [[https://en.wikipedia.org/wiki/Berkeley_RISC][Berkeley RISC]], were the three research projects that pioneered and popularized RISC technology in the mid-1980s.  In recognition of the impact MIPS made on computing, Hennessy was awarded the [[https://en.wikipedia.org/wiki/IEEE_John_von_Neumann_Medal][IEEE John von Neumann Medal]] in 2000 by the [[https://en.wikipedia.org/wiki/Institute_of_Electrical_and_Electronics_Engineers][Institute of Electrical and Electronics Engineers]] (IEEE) (shared with [[https://en.wikipedia.org/wiki/David_Patterson_(computer_scientist)][David A. Patterson]]), the [[https://en.wikipedia.org/wiki/Eckert–Mauchly_Award][Eckert--Mauchly Award]] in 2001 by the [[https://en.wikipedia.org/wiki/Association_for_Computing_Machinery][Association for Computing Machinery]], the [[https://en.wikipedia.org/wiki/Seymour_Cray_Computer_Engineering_Award][Seymour Cray Computer Engineering Award]] in 2001 by the [[https://en.wikipedia.org/wiki/IEEE_Computer_Society][IEEE Computer Society]], and, again with David Patterson, the [[https://en.wikipedia.org/wiki/Turing_Award][Turing Award]] in 2017 by the ACM.

  The project was initiated in 1981 in response to reports of similar projects at [[https://en.wikipedia.org/wiki/IBM][IBM]] (the [[https://en.wikipedia.org/wiki/IBM_801][801]]) and the [[https://en.wikipedia.org/wiki/University_of_California,_Berkeley][University of California, Berkeley]] (the [[https://en.wikipedia.org/wiki/Berkeley_RISC][RISC]]).  MIPS was conducted by Hennessy and his graduate students until its conclusion in 1984.  Hennessy founded [[https://en.wikipedia.org/wiki/MIPS_Computer_Systems][MIPS Computer Systems]] in the same year to commercialize the technology developed by the project.  In 1985, MIPS Computer Systems announced a new ISA, also called [[https://en.wikipedia.org/wiki/MIPS_architecture][MIPS]], and its first implementation, the [[https://en.wikipedia.org/wiki/R2000_(microprocessor)][R2000]] microprocessor.  The commercial MIPS ISA, and its implementations went on to be widely used, appearing in embedded computers, personal computers, workstations, servers, and supercomputers.  As of May 2017, the commercial MIPS ISA is owned by [[https://en.wikipedia.org/wiki/Imagination_Technologies][Imagination Technologies]], and is used mainly in embedded computers.  In the late 1980s, a follow-up project called [[https://en.wikipedia.org/wiki/MIPS-X][MIPS-X]] was conducted by Hennessy at Stanford.

  The MIPS ISA was based on a 32-bit word.  It supported 32-bit addressing, and was word-addressed.  It was a [[https://en.wikipedia.org/wiki/Load/store_architecture][load/store architecture]]—all references to memory used load and store instructions that copied data between the [[https://en.wikipedia.org/wiki/Main_memory][main memory]] and 32 [[https://en.wikipedia.org/wiki/General-purpose_register][general-purpose registers]] (GPRs).  All other instructions, such as integer arithmetic, operated on the GPRs.  It possessed a basic instruction set consisting of instructions for [[https://en.wikipedia.org/wiki/Control_flow][control flow]], integer arithmetic, and logical operations.  To minimize pipeline stalls, all instructions except for load and store had to be executed in one [[https://en.wikipedia.org/wiki/Clock_cycle][clock cycle]].  There were no instructions for integer multiplication or division, or operations for [[https://en.wikipedia.org/wiki/Floating-point_number][floating-point numbers]].  The architecture exposed all [[https://en.wikipedia.org/wiki/Hazard_(computer_architecture)][hazards]] caused by the five-stage pipeline with [[https://en.wikipedia.org/wiki/Delay_slot][delay slots]].  The compiler scheduled instructions to avoid hazards resulting in incorrect computation whilst simultaneously ensuring that the generated code minimized execution time.  MIPS instructions are 16 or 32 bit long.  The decision to expose all hazards was motivated by the desire to maximize performance by minimizing critical paths, which interlock circuits lengthened.  Instructions were packed into 32-bit /instruction words/ (as MIPS is word-addressed).  A 32-bit instruction word could contain two 16-bit operations.  These were included to reduce the size of machine code.  The MIPS microprocessor was implemented in [[https://en.wikipedia.org/wiki/NMOS_logic][NMOS logic]].
#+end_quote
* (en.wikipedia.org) MIPS-X - Wikipedia                             :website:
:PROPERTIES:
:ID:       43ebcdd4-40fe-4343-aa7b-a0ced98ad96f
:ROAM_REFS: https://en.wikipedia.org/wiki/MIPS-X
:END:

#+begin_quote
  *MIPS-X* is a [[https://en.wikipedia.org/wiki/Reduced_instruction_set_computer][reduced instruction set computer]] (RISC) [[https://en.wikipedia.org/wiki/Microprocessor][microprocessor]] and [[https://en.wikipedia.org/wiki/Instruction_set_architecture][instruction set architecture]] (ISA) developed as a follow-on project to the [[https://en.wikipedia.org/wiki/Stanford_MIPS][MIPS]] project at [[https://en.wikipedia.org/wiki/Stanford_University][Stanford University]] by the same team that developed MIPS.  The project was supported by the Defense Advanced Research Projects Agency ([[https://en.wikipedia.org/wiki/DARPA][DARPA]]) and began in 1984.  Its final form was described in a set of papers released in 1986--87.  Unlike its older cousin, MIPS-X was never commercialized as a [[https://en.wikipedia.org/wiki/Workstation][workstation]] [[https://en.wikipedia.org/wiki/Central_processing_unit][central processing unit]] (CPU), and has mainly been seen in [[https://en.wikipedia.org/wiki/Embedded_system][embedded system]] designs based on chips designed by [[https://en.wikipedia.org/wiki/8x8_Inc][Integrated Information Technology]] (IIT) for use in [[https://en.wikipedia.org/wiki/Digital_video][digital video]] applications.

  MIPS-X, while designed by the same team and architecturally very similar, is instruction-set incompatible with the mainline [[https://en.wikipedia.org/wiki/MIPS_architecture][MIPS architecture]] R-series processors.  The MIPS-X processor introduced the concept of a delayed branch, which includes two [[https://en.wikipedia.org/wiki/Delay_slot][delay slots]].  An MIPS-X processor also includes a Processor Status Word (PSW) register.  The PSW register contains some flags that enable [[https://en.wikipedia.org/wiki/Interrupt][interruptions]], overflow exceptions and other status information.  The MIPS-X processor is obscure enough that, as of November 20, 2005, support for it is provided only by specialist developers (such as [[https://en.wikipedia.org/wiki/Green_Hills_Software][Green Hills Software]]), and is notably missing from the [[https://en.wikipedia.org/wiki/GNU_Compiler_Collection][GNU Compiler Collection]] (GCC).

  MIPS-X has become important among [[https://en.wikipedia.org/wiki/DVD_player][DVD player]] [[https://en.wikipedia.org/wiki/Firmware][firmware]] [[https://en.wikipedia.org/wiki/Hacker_(hobbyist)][hackers]], since many [[https://en.wikipedia.org/wiki/DVD_player][DVD players]] (especially low-end devices) use chips based on the IIT design (and produced by [[https://en.wikipedia.org/wiki/ESS_Technology][ESS Technology]]), as their central processor.  Devices such as the ESS VideoDrive [[https://en.wikipedia.org/wiki/System_on_a_chip][system on a chip]] (SoC) also include a [[https://en.wikipedia.org/wiki/Digital_signal_processor][digital signal processor]] (DSP) (coprocessor) for decoding MPEG audio and video streams.
#+end_quote
