:PROPERTIES:
:ID:       77ffee75-ff6f-43e3-a594-39214bf181f2
:END:
#+title: Introduction to Algorithms
#+filetags: :algorithms:computer_science:textbooks:books:

Classical textbook on algorithms.
* (mitpress.mit.edu) Introduction to Algorithms                     :website:
:PROPERTIES:
:ID:       10acd728-bfa3-44ca-ae44-db4a52dc61da
:ROAM_REFS: https://mitpress.mit.edu/9780262046305/introduction-to-algorithms/
:END:

#+begin_quote
  A comprehensive update of the leading algorithms text, with new material on matchings in bipartite graphs, online algorithms, machine learning, and other topics.

  Some books on algorithms are rigorous but incomplete; others cover masses of material but lack rigor.  /Introduction to Algorithms/ uniquely combines rigor and comprehensiveness.  It covers a broad range of algorithms in depth, yet makes their design and analysis accessible to all levels of readers, with self-contained chapters and algorithms in pseudocode.  Since the publication of the first edition, /Introduction to Algorithms/ has become the leading algorithms text in universities worldwide as well as the standard reference for professionals.  This fourth edition has been updated throughout, with new chapters on matchings in bipartite graphs, online algorithms, and machine learning, and new material on such topics as solving recurrence equations, hash tables, potential functions, and suffix arrays.

  Each chapter is relatively self-contained, presenting an algorithm, a design technique, an application area, or a related topic, and can be used as a unit of study.  The algorithms are described in English and in a pseudocode designed to be readable by anyone who has done a little programming.  The explanations have been kept elementary without sacrificing depth of coverage or mathematical rigor.  The fourth edition has 140 new exercises and 22 new problems, and color has been added to improve visual presentations.  The writing has been revised throughout, and made clearer, more personal, and gender neutral.  The book's website offers supplemental material.

  Warning: Avoid counterfeit copies of /Introduction to Algorithms/ by buying only from reputable retailers.  Counterfeit and pirated copies are incomplete and contain errors.
#+end_quote
* (en.wikipedia.org) Introduction to Algorithms - Wikipedia :programming:algorithms:mathematics:computer_science:books:website:
:PROPERTIES:
:ID:       87a1a554-a120-484e-a014-80f3135627a7
:ROAM_REFS: https://en.wikipedia.org/wiki/Introduction_to_Algorithms
:END:

#+begin_quote
  /*Introduction to Algorithms*/ is a book on computer programming by [[https://en.wikipedia.org/wiki/Thomas_H._Cormen][Thomas H. Cormen]], [[https://en.wikipedia.org/wiki/Charles_E._Leiserson][Charles E. Leiserson]], [[https://en.wikipedia.org/wiki/Ron_Rivest][Ronald L. Rivest]], and [[https://en.wikipedia.org/wiki/Clifford_Stein][Clifford Stein]].  The book is described by its publisher as "the leading algorithms text in universities worldwide as well as the standard reference for professionals".  It is commonly [[https://en.wikipedia.org/wiki/Citation][cited]] as a reference for algorithms in published [[https://en.wikipedia.org/wiki/Academic_publishing#Scholarly_paper][papers]], with over 10,000 citations documented on [[https://en.wikipedia.org/wiki/CiteSeerX][CiteSeerX]], and over 70,000 citations on Google Scholar as of 2024.  The book sold half a million copies during its first 20 years, and surpassed a million copies sold in 2022.  Its fame has led to the common use of the abbreviation "*CLRS*" (Cormen, Leiserson, Rivest, Stein), or, in the first edition, "*CLR*" (Cormen, Leiserson, Rivest).

  In the preface, the authors write about how the book was written to be comprehensive and useful in both teaching and professional environments.  Each chapter focuses on an algorithm, and discusses its design techniques and areas of application.  Instead of using a specific programming language, the algorithms are written in [[https://en.wikipedia.org/wiki/Pseudocode][pseudocode]].  The descriptions focus on the aspects of the algorithm itself, its mathematical properties, and emphasize efficiency.
#+end_quote
* (www.amazon.com) Introduction to Algorithms, fourth edition: 9780262046305: Computer Science Books @ Amazon.com :website:
:PROPERTIES:
:ID:       460b96cf-0ab7-480d-804e-a71fb2c7dabc
:ROAM_REFS: https://www.amazon.com/dp/026204630X/
:END:
