:PROPERTIES:
:ID:       348bc7ac-4d8d-4fae-8e25-97ae9fd957a8
:ROAM_ALIASES: WYSIWYM "What You See Is What You Mean"
:END:
#+title: WYSIWYM (What You See Is What You Mean)
#+filetags: :human_interaction:computer_science:design:

/What you see is what you mean/.  A description of software that displays content in a form representing meaning as opposed to what the final display form of the content is.  Adjunct to [[id:e4458b32-801d-48b8-8fa5-b021c7406e2d][WYSIWYG]].
* (en.wikipedia.org) WYSIWYM - Wikipedia                            :website:
:PROPERTIES:
:ID:       1cc34c5e-ac6b-4c0d-aa6e-e3005f3a4c2b
:ROAM_REFS: https://en.wikipedia.org/wiki/WYSIWYM
:END:

#+begin_quote
  In [[https://en.wikipedia.org/wiki/Computing][computing]], *What You See Is What You Mean* (*WYSIWYM,* [[https://en.wikipedia.org/wiki/Help:IPA/English][/ˈwɪziwɪm/]]) is a [[https://en.wikipedia.org/wiki/Paradigm][paradigm]] for editing a [[https://en.wikipedia.org/wiki/Structured_document][structured document]].  It is an adjunct to the [[https://en.wikipedia.org/wiki/WYSIWYG][WYSIWYG]] (What You See Is What You Get) paradigm, which displays the result of a formatted document as it will appear on screen or in print---without showing the descriptive code underneath.

  In a WYSIWYM editor, the user writes the contents in a structured way, marking the content according to its meaning, its significance in the document, and leaves its final appearance up to one or more separate [[https://en.wikipedia.org/wiki/Style_sheet_language][style sheets]].  In essence, it aims to accurately display the contents being conveyed, rather than the actual formatting associated with it.

  For example, in a WYSIWYM document, one would manually mark text as the title of the document, the name of a section, the caption associated with a figure, or the name of an author; this would in turn allow one element, such as section headings, to be rendered as large bold text in one style sheet, or as red center justified text in another, without further manual intervention.  More often than not, this requires the [[https://en.wikipedia.org/wiki/Semantics][semantic]] structure of the document to be decided in advance before writing it.  The editor also needs a system for exporting structured content to generate the document's final format, following the indicated structure.

  The main advantage of this system is the total [[https://en.wikipedia.org/wiki/Separation_of_content_and_presentation][separation of content and presentation]]: users can structure and write the document once, rather than repeatedly alternating between the two modes of presentation---an approach which comes with its own [[https://en.wikipedia.org/wiki/Task_switching_(psychology)#Switch_cost][switch cost]].  And since the rendering of formatting is left to the export system, this also makes it easier to achieve consistency in design as well.
#+end_quote
