:PROPERTIES:
:ID:       b7ffa33f-6da2-4918-9ced-6afd0fbdb0fe
:END:
#+title: Unix
#+filetags: :unix:software:operating_systems:computer_science:

[[id:412bbcad-6c00-4f13-b748-d1ffde0588e1][Operating system]] originally developed at [[id:efd4f0a8-71b6-4a15-8109-60d9d51f1f0a][Bell Labs]] by [[id:11238d7d-6b5d-44a8-99dc-be50cafa5657][Ken L. Thompson]], [[id:42a22d7b-4dfd-46a8-9e7d-0ee2bb4a52ec][Dennis M. Ritchie]], and [[id:fe1aeb41-296c-4f8f-aae0-75be06c6e5fb][Brian W. Kernighan]].  Implemented in the [[id:c46eea5e-e2d2-4a21-bafe-74b6751292d2][C]] [[id:b24601aa-09df-41e1-aa7e-25ead342db34][programming language]].  Inspired the creation of clones and other derivatives, including [[id:bf0bc2d7-17df-413c-823b-93904faffc58][Linux]], [[id:43194992-e4b9-4c9c-b8bb-32aba92e3891][NetBSD]], [[id:9de6b78d-1506-4837-bfa5-03e8632be933][FreeBSD]], and [[id:a641ae8e-1d3c-4e90-911c-51a594b05a08][OpenBSD]].
* (en.wikipedia.org) Unix - Wikipedia                               :website:
:PROPERTIES:
:ID:       dc29cf0c-7490-4185-9157-3cdfd174b89b
:ROAM_REFS: https://en.wikipedia.org/wiki/Unix
:END:

#+begin_quote
  *Unix* ([[https://en.wikipedia.org/wiki/Help:IPA/English][/ˈjuːnɪks/]], [[https://en.wikipedia.org/wiki/Help:Pronunciation_respelling_key][/YOO-niks/]]; trademarked as *UNIX*) is a family of [[https://en.wikipedia.org/wiki/Computer_multitasking][multitasking]], [[https://en.wikipedia.org/wiki/Multi-user_software][multi-user]] computer [[https://en.wikipedia.org/wiki/Operating_system][operating systems]] that derive from the original [[https://en.wikipedia.org/wiki/AT&T_Corporation][AT&T]] Unix, whose development started in 1969 at the [[https://en.wikipedia.org/wiki/Bell_Labs][Bell Labs]] research center by [[https://en.wikipedia.org/wiki/Ken_Thompson][Ken Thompson]], [[https://en.wikipedia.org/wiki/Dennis_Ritchie][Dennis Ritchie]], and others.  Initially intended for use inside the [[https://en.wikipedia.org/wiki/Bell_System][Bell System]], AT&T [[https://en.wikipedia.org/wiki/License][licensed]] Unix to outside parties in the late 1970s, leading to a variety of both academic and commercial Unix variants from vendors including [[https://en.wikipedia.org/wiki/University_of_California,_Berkeley][University of California, Berkeley]] ([[https://en.wikipedia.org/wiki/Berkeley_Software_Distribution][BSD]]), [[https://en.wikipedia.org/wiki/Microsoft][Microsoft]] ([[https://en.wikipedia.org/wiki/Xenix][Xenix]]), [[https://en.wikipedia.org/wiki/Sun_Microsystems][Sun Microsystems]] ([[https://en.wikipedia.org/wiki/SunOS][SunOS]]/[[https://en.wikipedia.org/wiki/Solaris_(operating_system)][Solaris]]), [[https://en.wikipedia.org/wiki/Hewlett-Packard][HP]]/[[https://en.wikipedia.org/wiki/Hewlett_Packard_Enterprise][HPE]] ([[https://en.wikipedia.org/wiki/HP-UX][HP-UX]]), and [[https://en.wikipedia.org/wiki/IBM][IBM]] ([[https://en.wikipedia.org/wiki/IBM_AIX][AIX]]).

  The early versions of Unix---which are retrospectively referred to as "[[https://en.wikipedia.org/wiki/Research_Unix][Research Unix]]"---ran on computers such as the [[https://en.wikipedia.org/wiki/PDP-11][PDP-11]] and [[https://en.wikipedia.org/wiki/VAX][VAX]]; Unix was commonly used on [[https://en.wikipedia.org/wiki/Minicomputers][minicomputers]] and [[https://en.wikipedia.org/wiki/Mainframe_computer][mainframes]] from the 1970s onwards.  It distinguished itself from its predecessors as the first [[https://en.wikipedia.org/wiki/Software_portability][portable]] operating system: almost the entire operating system is written in the [[https://en.wikipedia.org/wiki/C_(programming_language)][C programming language]] (in 1973), which allows Unix to operate on numerous platforms.  Unix systems are characterized by a [[https://en.wikipedia.org/wiki/Modular_design][modular design]] that is sometimes called the "[[https://en.wikipedia.org/wiki/Unix_philosophy][Unix philosophy]]".  According to this philosophy, the operating system should provide a set of simple tools, each of which performs a limited, well-defined function.  A unified and [[https://en.wikipedia.org/wiki/Inode][inode]]-based [[https://en.wikipedia.org/wiki/Unix_filesystem][filesystem]] and an [[https://en.wikipedia.org/wiki/Inter-process_communication][inter-process communication]] mechanism known as "[[https://en.wikipedia.org/wiki/Pipeline_(Unix)][pipes]]" serve as the main means of communication, and a [[https://en.wikipedia.org/wiki/Shell_(computing)][shell]] scripting and command language (the [[https://en.wikipedia.org/wiki/Unix_shell][Unix shell]]) is used to combine the tools to perform complex workflows.

  [[https://en.wikipedia.org/wiki/Version_7_Unix][Version 7]] in 1979 was the final widely released Research Unix, after which AT&T sold [[https://en.wikipedia.org/wiki/UNIX_System_III][UNIX System III]], based on Version 7, commercially in 1982; to avoid confusion between the Unix variants, AT&T combined various versions developed by others and released it as [[https://en.wikipedia.org/wiki/UNIX_System_V][UNIX System V]] in 1983.  However as these were closed-source, the University of California, Berkeley continued developing BSD as an alternative.  Other vendors that were beginning to create commercialized versions of Unix would base their version on either System V (like [[https://en.wikipedia.org/wiki/Silicon_Graphics][Silicon Graphics]]'s [[https://en.wikipedia.org/wiki/IRIX][IRIX]]) or BSD (like SunOS).  Amid the "[[https://en.wikipedia.org/wiki/Unix_wars][Unix wars]]" of standardization, AT&T alongside Sun merged System V, BSD, SunOS and Xenix, soldifying their features into one package as UNIX System V Release 4 (SVR4) in 1989, and it was commercialized by [[https://en.wikipedia.org/wiki/Unix_System_Laboratories][Unix System Laboratories]], an AT&T spinoff.  A rival Unix by other vendors was released as [[https://en.wikipedia.org/wiki/OSF/1][OSF/1]], however most commercial Unix vendors eventually changed their distributions to be based on SVR4 with BSD features added on top.

  AT&T sold Unix to [[https://en.wikipedia.org/wiki/Novell][Novell]] in 1992, who later sold the UNIX trademark to a new industry consortium called [[https://en.wikipedia.org/wiki/The_Open_Group][The Open Group]] which allow the use of the mark for certified operating systems that comply with the [[https://en.wikipedia.org/wiki/Single_UNIX_Specification][Single UNIX Specification]] (SUS).  Since the 1990s, Unix systems have appeared on [[https://en.wikipedia.org/wiki/Home_computers][home-class computers]]: [[https://en.wikipedia.org/wiki/BSD/OS][BSD/OS]] was the first to be commercialized for [[https://en.wikipedia.org/wiki/I386][i386]] computers and since then free [[https://en.wikipedia.org/wiki/Unix-like][Unix-like]] clones of existing systems have been developed, such as [[https://en.wikipedia.org/wiki/FreeBSD][FreeBSD]] and the combination of [[https://en.wikipedia.org/wiki/Linux][Linux]] and [[https://en.wikipedia.org/wiki/GNU][GNU]], the latter of which have since eclipsed Unix in popularity.  Unix was, until 2005, the most widely used [[https://en.wikipedia.org/wiki/Server_(computing)][server]] operating system.  However in the present day, Unix distributions like IBM AIX, Oracle Solaris and [[https://en.wikipedia.org/wiki/OpenServer][OpenServer]] continue to be widely used in certain fields.
#+end_quote
