:PROPERTIES:
:ID:       ad0fa652-01e1-4d94-ab14-92377817aa19
:END:
#+title: Coisas CMS
#+filetags: :open_source:content_management:www:web_development:software:

An [[id:a3c19488-876c-4b17-81c0-67b9c7fc64ee][open-source]], [[id:003ec9df-d673-4336-aae0-9a034fd89997][git]]-based, headless [[id:093a1925-9878-460d-8819-cd7847232bad][CMS]] that works with any static site generator.
* (coisas.fiatjaf.com) Coisas CMS                                   :website:
:PROPERTIES:
:ID:       03631b32-8535-4ae3-b13f-426ed0d2f273
:ROAM_REFS: https://coisas.fiatjaf.com/
:END:
* (github.com) fiatjaf/coisas: a client-side CMS for editing GitHub Markdown (and other) files :website:
:PROPERTIES:
:ID:       51a10b9b-013e-4641-8c8c-71a28367a1c4
:ROAM_REFS: https://github.com/fiatjaf/coisas
:END:

#+begin_quote
  *coisas* is a headless CMS specifically designed to let you edit files hosted in a GitHub repository.  It is similar to [[https://github.com/netlify/netlify-cms][Netlify CMS]] and [[http://prose.io/][Prose]].  Unlike existing alternatives, *coisas* doesn't try to be a multipurpose CMS.  It still lets you edit, create, upload, and browse files, but doesn't try to look like a fancy CMS (custom schema, objects and all that mess).  It also isn't tailored to Jekyll websites, which means that it won't insert Jekyll specific code or expect your repository to have a Jekyll-specific file structure.

  Other features that *coisas* includes are:

  - file tree view;
  - simple metadata editor and automatic saving of Markdown and HTML files with YAML front-matter;
  - behavior customizations that can be configured from your repository, while still accessing *coisas* from its own URL;
  - easy embedding in your own site, so you'll never have to touch *coisas* own URL;
  - image gallery with all the images from your repository, so you can drag and drop them inside the editor;
  - simple visualization of many file formats (only text files are editable, however).
#+end_quote
