:PROPERTIES:
:ID:       b451b5a8-2b57-4427-931e-f25ae4fc01f3
:END:
#+title: GNOME Project
#+filetags: :organization:

Project that maintains the [[id:e96272a6-c2f0-40b6-846d-7066f3a460f6][GNOME desktop environment]] and associated software.
* GNOME Desktop Environment                            :open_source:software:
:PROPERTIES:
:ID:       e96272a6-c2f0-40b6-846d-7066f3a460f6
:END:

[[id:a3c19488-876c-4b17-81c0-67b9c7fc64ee][Open-source]] desktop environment of the [[id:b451b5a8-2b57-4427-931e-f25ae4fc01f3][GNOME Project]].
* (www.gnome.org) GNOME                                             :website:
:PROPERTIES:
:ID:       85fe5e64-89a0-4f1f-8371-205bcc47a2f1
:ROAM_REFS: https://www.gnome.org/
:END:
** (www.gnome.org) GNOME - About Us
:PROPERTIES:
:ID:       e5f22e89-3dff-4086-8a42-711777f4de04
:ROAM_REFS: https://www.gnome.org/about
:END:

#+begin_quote
  ** The GNOME Story

  The GNOME project was founded in 1997 by two students, Miguel de Icaza and Federico Mena.  Their goal: to take on the tech giants of the day, and build a completely free desktop operating system.  From that small beginning, GNOME grew to become a global phenomenon.  Its community spread across the world, and the project spawned many components which themselves went on to become critical elements of Linux-based systems.

  Today, GNOME's software is used by millions of people the world over.  It provides the user experience for all the main Linux distributions, and the project continues to develop vital software which is relied upon far beyond the desktop.

  ** What we make

  GNOME today produces and maintains around 120 software modules.  Together, these components provide:

  - The graphical GNOME user system, including the system interface, display systems, window management, input handling, and system settings and behavior.
  - A [[https://apps.gnome.org/][suite of essential apps]] which are included as part of the GNOME system.
  - GNOME's application development platform and runtime environment, which allows developers to create their own apps.

  This software is developed in collaboration with the wider open source Linux ecosystem, which provides the lower level software on which GNOME depends.

  ** Who we are

  GNOME is a thriving community of contributors and supporting organizations.  Our project is made up of participants from across the globe, and includes volunteers and paid contributors.  Our work encompasses every aspect of the software development process, from design, through to development, testing, and documentation.

  The GNOME community is backed and supported by the non-profit [[https://foundation.gnome.org/][GNOME Foundation]].

  ** Our mission

  Miguel and Federico's vision of freedom remains at the heart of the GNOME project.  Open source principles, equality of participation, and collaboration remain guiding principles for the project.

  GNOME's openness is also one of its greatest strengths, allowing it to provide unique learning opportunities for its participants, and for its software to be used in the most critical situations, from space flight control rooms, to automotive systems, to the laptops of those threatened by oppressive regimes.

  Today, GNOME continues its mission to promote software freedom, expanding its endeavours to new computing frontiers.  The project leads in several critical areas, from the movement to create a free and independent app ecosystem, to open user centered design practices, to open mobile.

  We invite you to join us.
#+end_quote
