:PROPERTIES:
:ID:       d1896f87-0187-4f30-8b58-304bda6cd000
:END:
#+title: Android
#+filetags: :software:mobile_telephony:phones:android_os:open_source:google:operating_systems:

[[id:a3c19488-876c-4b17-81c0-67b9c7fc64ee][Open-source]] [[id:412bbcad-6c00-4f13-b748-d1ffde0588e1][operating system]] for smartphones using the [[id:bf0bc2d7-17df-413c-823b-93904faffc58][Linux]] kernel and developed by Google.
* (en.wikipedia.org) Android (operating system) - Wikipedia         :website:
:PROPERTIES:
:ID:       3a918ffa-4667-4c9a-b626-dc258d8bf308
:ROAM_REFS: https://en.wikipedia.org/wiki/Android_(operating_system)
:END:

#+begin_quote
  *Android* is a [[https://en.wikipedia.org/wiki/Mobile_operating_system][mobile operating system]] based on a modified version of the [[https://en.wikipedia.org/wiki/Linux_kernel][Linux kernel]] and other [[https://en.wikipedia.org/wiki/Open-source_software][open-source]] software, designed primarily for [[https://en.wikipedia.org/wiki/Touchscreen][touchscreen]]-based mobile devices such as [[https://en.wikipedia.org/wiki/Smartphone][smartphones]] and [[https://en.wikipedia.org/wiki/Tablet_computer][tablets]].  Android has historically been developed by a consortium of developers known as the [[https://en.wikipedia.org/wiki/Open_Handset_Alliance][Open Handset Alliance]], but its most widely used version is primarily developed by [[https://en.wikipedia.org/wiki/Google][Google]].  First released in 2008, Android is the world's [[https://en.wikipedia.org/wiki/Usage_share_of_operating_systems][most widely used operating system]]; the latest version, released on October 15, 2024, is [[https://en.wikipedia.org/wiki/Android_15][Android 15]].

  At its core, the operating system is known as the *Android Open Source Project* (*AOSP*) and is [[https://en.wikipedia.org/wiki/Free_and_open-source_software][free and open-source software]] (FOSS) primarily licensed under the [[https://en.wikipedia.org/wiki/Apache_License][Apache License]].  However, most devices run the [[https://en.wikipedia.org/wiki/Proprietary_software][proprietary]] Android version developed by Google, which ships with additional proprietary closed-source software pre-installed, most notably [[https://en.wikipedia.org/wiki/Google_Mobile_Services][Google Mobile Services]] (GMS), which includes core apps such as [[https://en.wikipedia.org/wiki/Google_Chrome][Google Chrome]], the [[https://en.wikipedia.org/wiki/Digital_distribution][digital distribution]] platform [[https://en.wikipedia.org/wiki/Google_Play][Google Play]], and the associated [[https://en.wikipedia.org/wiki/Google_Play_Services][Google Play Services]] development platform. [[https://en.wikipedia.org/wiki/Firebase_Cloud_Messaging][Firebase Cloud Messaging]] is used for push notifications.  While AOSP is free, the "Android" name and logo are [[https://en.wikipedia.org/wiki/Trademark][trademarks]] of Google, who restrict the use of Android branding on "uncertified" products.  The majority of smartphones based on AOSP run Google's ecosystem---which is known simply as Android---some with [[https://en.wikipedia.org/wiki/Vendor][vendor]]-customized user interfaces and software suites, for example [[https://en.wikipedia.org/wiki/One_UI][One UI]].  Numerous [[https://en.wikipedia.org/wiki/List_of_custom_Android_distributions][modified distributions]] exist, which include competing [[https://en.wikipedia.org/wiki/Fire_OS][Amazon Fire OS]], community-developed [[https://en.wikipedia.org/wiki/LineageOS][LineageOS]], and others; the source code has also been used to develop a variety of Android distributions on a range of other electronics, such as [[https://en.wikipedia.org/wiki/Android_TV][Android TV]] for televisions, [[https://en.wikipedia.org/wiki/Wear_OS][Wear OS]] for [[https://en.wikipedia.org/wiki/Wearable_computer][wearables]], and [[https://en.wikipedia.org/wiki/Meta_Horizon_OS][Meta Horizon OS]] for [[https://en.wikipedia.org/wiki/Virtual_reality_headset][VR headsets]].

  Software packages on Android, which use the [[https://en.wikipedia.org/wiki/Apk_(file_format)][APK]] format, are generally distributed through proprietary [[https://en.wikipedia.org/wiki/Application_store][application stores]] like [[https://en.wikipedia.org/wiki/Google_Play_Store][Google Play Store]], [[https://en.wikipedia.org/wiki/Amazon_Appstore][Amazon Appstore]], [[https://en.wikipedia.org/wiki/Samsung_Galaxy_Store][Samsung Galaxy Store]], [[https://en.wikipedia.org/wiki/Huawei_AppGallery][Huawei AppGallery]], [[https://en.wikipedia.org/wiki/Cafe_Bazaar][Cafe Bazaar]], [[https://en.wikipedia.org/wiki/GetJar][GetJar]], and [[https://en.wikipedia.org/wiki/Aptoide][Aptoide]], or open source platforms like [[https://en.wikipedia.org/wiki/F-Droid][F-Droid]].  Since 2011 Android has been the most used operating system worldwide on smartphones.  It has the largest [[https://en.wikipedia.org/wiki/Installed_base][installed base]] of any operating system in the world with over three billion [[https://en.wikipedia.org/wiki/Monthly_active_users][monthly active users]] and accounting for 46% of the global operating system market.
#+end_quote
