:PROPERTIES:
:ID:       5c1e66dd-65de-4e8d-9f7d-077a352af8ab
:END:
#+title: C++ (Programming Language)
#+filetags: :cpp_lang:programming:programming_language:computer_science:

Originally based on the [[id:c46eea5e-e2d2-4a21-bafe-74b6751292d2][C]] [[id:b24601aa-09df-41e1-aa7e-25ead342db34][programming language]] and designed by [[id:a74eb2a7-2da6-4993-8278-368351a9c154][Bjarne Stroustrup]].
* (en.wikipedia.org) C++ - Wikipedia                                :website:
:PROPERTIES:
:ID:       bff2fe26-367a-40fe-85d3-eee8b5264128
:ROAM_REFS: https://en.wikipedia.org/wiki/C++
:END:

#+begin_quote
  *C++* ([[https://en.wikipedia.org/wiki/Help:IPA/English][/ˈsiː plʌs plʌs/]], pronounced "*C plus plus*" and sometimes abbreviated as *CPP*) is a [[https://en.wikipedia.org/wiki/High-level_programming_language][high-level]], [[https://en.wikipedia.org/wiki/General-purpose_programming_language][general-purpose programming language]] created by Danish computer scientist [[https://en.wikipedia.org/wiki/Bjarne_Stroustrup][Bjarne Stroustrup]].  First released in 1985 as an extension of the [[https://en.wikipedia.org/wiki/C_(programming_language)][C programming language]], it has since expanded significantly over time; as of 1997, C++ has [[https://en.wikipedia.org/wiki/Object-oriented_programming][object-oriented]], [[https://en.wikipedia.org/wiki/Generic_programming][generic]], and [[https://en.wikipedia.org/wiki/Functional_programming][functional]] features, in addition to facilities for [[https://en.wikipedia.org/wiki/Low-level_programming_language][low-level]] [[https://en.wikipedia.org/wiki/Memory_(computing)][memory]] manipulation for systems like [[https://en.wikipedia.org/wiki/Microcomputer][microcomputers]] or to make operating systems like [[https://en.wikipedia.org/wiki/Linux][Linux]] or [[https://en.wikipedia.org/wiki/Microsoft_Windows][Windows]].  It is usually implemented as a [[https://en.wikipedia.org/wiki/Compiled_language][compiled language]], and many vendors provide [[https://en.wikipedia.org/wiki/List_of_compilers#C.2B.2B_compilers][C++ compilers]], including the [[https://en.wikipedia.org/wiki/Free_Software_Foundation][Free Software Foundation]], [[https://en.wikipedia.org/wiki/LLVM][LLVM]], [[https://en.wikipedia.org/wiki/Microsoft][Microsoft]], [[https://en.wikipedia.org/wiki/Intel][Intel]], [[https://en.wikipedia.org/wiki/Embarcadero_Technologies][Embarcadero]], [[https://en.wikipedia.org/wiki/Oracle_Developer_Studio][Oracle]], and [[https://en.wikipedia.org/wiki/IBM][IBM]].

  C++ was designed with [[https://en.wikipedia.org/wiki/Systems_programming][systems programming]] and [[https://en.wikipedia.org/wiki/Embedded_software][embedded]], resource-constrained software and large systems in mind, with [[https://en.wikipedia.org/wiki/Performance_(software)][performance]], efficiency, and flexibility of use as its design highlights.  C++ has also been found useful in many other contexts, with key strengths being software infrastructure and resource-constrained applications, including [[https://en.wikipedia.org/wiki/Application_software][desktop applications]], [[https://en.wikipedia.org/wiki/Video_game_development][video games]], [[https://en.wikipedia.org/wiki/Server_(computing)][servers]] (e.g., [[https://en.wikipedia.org/wiki/E-commerce][e-commerce]], [[https://en.wikipedia.org/wiki/Web_search_engine][web search]], or [[https://en.wikipedia.org/wiki/Database][databases]]), and performance-critical applications (e.g., [[https://en.wikipedia.org/wiki/Telephone_switches][telephone switches]] or [[https://en.wikipedia.org/wiki/Space_probes][space probes]]).

  C++ is standardized by the [[https://en.wikipedia.org/wiki/International_Organization_for_Standardization][International Organization for Standardization]] (ISO), with the latest standard version ratified and published by ISO in October 2024 as /ISO/IEC 14882:2024/ (informally known as [[https://en.wikipedia.org/wiki/C++23][C++23]]).  The C++ programming language was initially standardized in 1998 as /ISO/IEC 14882:1998/, which was then amended by the [[https://en.wikipedia.org/wiki/C++03][C++03]], [[https://en.wikipedia.org/wiki/C++11][C++11]], [[https://en.wikipedia.org/wiki/C++14][C++14]], [[https://en.wikipedia.org/wiki/C++17][C++17]], and [[https://en.wikipedia.org/wiki/C++20][C++20]] standards.  The current [[https://en.wikipedia.org/wiki/C++23][C++23]] standard supersedes these with new features and an enlarged [[https://en.wikipedia.org/wiki/C++_Standard_library][standard library]].  Before the initial standardization in 1998, C++ was developed by Stroustrup at [[https://en.wikipedia.org/wiki/Bell_Labs][Bell Labs]] since 1979 as an extension of the C language; he wanted an efficient and flexible language similar to C that also provided [[https://en.wikipedia.org/wiki/High-level_programming_language][high-level features]] for program organization.  Since 2012, C++ has been on a three-year release schedule with [[https://en.wikipedia.org/wiki/C++26][C++26]] as the next planned standard.

  Despite its widespread adoption, some notable programmers have [[https://en.wikipedia.org/wiki/Criticism_of_C++][criticized the C++ language]], including [[https://en.wikipedia.org/wiki/Linus_Torvalds][Linus Torvalds]], [[https://en.wikipedia.org/wiki/Richard_Stallman][Richard Stallman]], [[https://en.wikipedia.org/wiki/Joshua_Bloch][Joshua Bloch]], [[https://en.wikipedia.org/wiki/Ken_Thompson][Ken Thompson]], and [[https://en.wikipedia.org/wiki/Donald_Knuth][Donald Knuth]].  This is largely due to its manual memory management, which makes it vulnerable to [[https://en.wikipedia.org/wiki/Buffer_overflow][buffer overflow]] bugs, which represent a security risk.
#+end_quote
