:PROPERTIES:
:ID:       abd50a09-4c8a-4648-b73d-67b2a1724d27
:END:
#+title: iptables
#+filetags: :linux:networking:

Userspace frontend to [[id:bf0bc2d7-17df-413c-823b-93904faffc58][Linux]] network filtering system [[id:4902673c-f336-4a97-8ea2-99d258c4e42a][Netfilter]].  Succeeded by [[id:78c9c8fd-611c-496e-9103-ea8cc061d6fa][nftables]].
* (en.wikipedia.org) iptables - Wikipedia                           :website:
:PROPERTIES:
:ID:       ee84af5b-76e1-4afd-9b0e-7c09fbcc63c2
:ROAM_REFS: https://en.wikipedia.org/wiki/Iptables
:END:

#+begin_quote
  *iptables* is a [[https://en.wikipedia.org/wiki/User_space][user-space]] utility program that allows a [[https://en.wikipedia.org/wiki/System_administrator][system administrator]] to configure the [[https://en.wikipedia.org/wiki/Packet_filter][IP packet filter rules]] of the [[https://en.wikipedia.org/wiki/Linux_kernel][Linux kernel]] [[https://en.wikipedia.org/wiki/Firewall_(computing)][firewall]], implemented as different [[https://en.wikipedia.org/wiki/Netfilter][Netfilter]] modules.  The filters are organized in a set of tables, which contain chains of rules for how to treat network traffic packets.  Different kernel modules and programs are currently used for different protocols; /iptables/ applies to IPv4, /ip6tables/ to IPv6, /arptables/ to [[https://en.wikipedia.org/wiki/Address_Resolution_Protocol][ARP]], and /ebtables/ to [[https://en.wikipedia.org/wiki/Ethernet_frame][Ethernet frames]].

  iptables requires elevated privileges to operate and must be executed by user [[https://en.wikipedia.org/wiki/Superuser][root]], otherwise it fails to function.  On most Linux systems, iptables is installed as

  /usr/sbin/iptables and documented in its [[https://en.wikipedia.org/wiki/Man_page][man pages]], which can be opened using =man iptables= when installed.  It may also be found in =/sbin/iptables=, but since iptables is more like a service rather than an "essential binary", the preferred location remains /usr/sbin.

  The term /iptables/ is also commonly used to inclusively refer to the kernel-level components. /x_tables/ is the name of the kernel module carrying the shared code portion used by all four modules that also provides the API used for extensions; subsequently, /Xtables/ is more or less used to refer to the entire firewall (v4, v6, arp, and eb) architecture.

  iptables superseded [[https://en.wikipedia.org/wiki/Ipchains][ipchains]]; and the successor of iptables is [[https://en.wikipedia.org/wiki/Nftables][nftables]], which was released on 19 January 2014 and was merged into the [[https://en.wikipedia.org/wiki/Linux_kernel_mainline][Linux kernel mainline]] in kernel version 3.13.
#+end_quote
