:PROPERTIES:
:ID:       04f28544-1c6f-4519-8c5d-88c0ff07c656
:END:
#+title: x86
#+filetags: :amd_inc:intel_corp:electronics:microprocessor:processor:computer_architecture:computer_science:

A family of 16-, 32-, and 64-bit [[id:96b6fc36-5b86-4108-b2b4-39b85a38f385][CISC]] processors, and corresponding [[id:c980a340-2564-437e-a79f-388122a206ad][ISA]], originally developed by Intel.
* (en.wikipedia.org) x86 - Wikipedia                                :website:
:PROPERTIES:
:ID:       19fe7278-adfb-4651-9455-075ea8229833
:ROAM_REFS: https://en.wikipedia.org/wiki/X86
:END:

#+begin_quote
  *x86* (also known as *80x86* or the *8086 family*) is a family of [[https://en.wikipedia.org/wiki/Complex_instruction_set_computer][complex instruction set computer]] (CISC) [[https://en.wikipedia.org/wiki/Instruction_set_architecture][instruction set architectures]] initially developed by [[https://en.wikipedia.org/wiki/Intel][Intel]], based on the [[https://en.wikipedia.org/wiki/Intel_8086][8086]] microprocessor and its 8-bit-external-bus variant, the [[https://en.wikipedia.org/wiki/Intel_8088][8088]].  The 8086 was introduced in 1978 as a fully [[https://en.wikipedia.org/wiki/16-bit_computing][16-bit]] extension of [[https://en.wikipedia.org/wiki/8-bit_computing][8-bit]] Intel's [[https://en.wikipedia.org/wiki/Intel_8080][8080]] microprocessor, with [[https://en.wikipedia.org/wiki/X86_memory_segmentation][memory segmentation]] as a solution for addressing more memory than can be covered by a plain 16-bit address.  The term "x86" came into being because the names of several successors to Intel's 8086 processor end in "86", including the [[https://en.wikipedia.org/wiki/Intel_80186][80186]], [[https://en.wikipedia.org/wiki/Intel_80286][80286]], [[https://en.wikipedia.org/wiki/I386][80386]] and [[https://en.wikipedia.org/wiki/I486][80486]].  Colloquially, their names were "186", "286", "386" and "486".

  The term is not synonymous with [[https://en.wikipedia.org/wiki/IBM_PC_compatible][IBM PC compatibility]], as this implies a multitude of other [[https://en.wikipedia.org/wiki/Computer_hardware][computer hardware]]. [[https://en.wikipedia.org/wiki/Embedded_system][Embedded systems]] and general-purpose computers used x86 chips [[https://en.wikipedia.org/wiki/Influence_of_the_IBM_PC_on_the_personal_computer_market#Before_the_IBM_PC's_introduction][before the PC-compatible market started]], some of them before the [[https://en.wikipedia.org/wiki/IBM_PC][IBM PC]] (1981) debut.

  As of June 2022, most [[https://en.wikipedia.org/wiki/Desktop_computer][desktop]] and [[https://en.wikipedia.org/wiki/Laptop][laptop]] computers sold are based on the x86 architecture family, while mobile categories such as [[https://en.wikipedia.org/wiki/Smartphone][smartphones]] or [[https://en.wikipedia.org/wiki/Tablet_computer][tablets]] are dominated by [[https://en.wikipedia.org/wiki/ARM_architecture][ARM]].  At the high end, x86 continues to dominate computation-intensive [[https://en.wikipedia.org/wiki/Workstation][workstation]] and [[https://en.wikipedia.org/wiki/Cloud_computing][cloud computing]] segments.
#+end_quote
