:PROPERTIES:
:ID:       588e2e0b-2c43-4326-9c1c-2f1ce1e8aa2a
:END:
#+title: Pale Moon
#+filetags: :open_source:firefox:www:software:

Hard-fork of [[id:11f55adb-3785-4f14-9de5-719fde4906b8][Firefox]] focused on customizability and supporting legacy browser extensions and XUL.
* (www.palemoon.org) The Pale Moon Project homepage                 :website:
:PROPERTIES:
:ID:       abdb8831-fceb-475f-a781-34a432caf582
:ROAM_REFS: https://www.palemoon.org/
:END:

#+begin_quote
  * Welcome to Pale Moon -- Your Browser, Your Way™

  Pale Moon is an Open Source, Goanna-based web browser available for various operating systems including Microsoft Windows, Mac OS and Linux (with contributed other operating system support), focusing on efficiency and customization.  Make sure to get the most out of your browser!

  Pale Moon offers you a browsing experience in a browser completely built from its own, independently developed source that has been forked off from Firefox/Mozilla code a number of years ago, with carefully selected features and optimizations to improve the browser's stability and user experience, while offering full customization and a growing collection of extensions and themes to make the browser truly your own.

  Impatient?  Jump to our download page:

  [[https://www.palemoon.org/download.shtml][Download now]]

  Looking for specific download options like a package for a different operating system, development options or a portable version?  Check the download menu at the top of this page!

  Main features:

  - Optimized for modern processors (see [[https://www.palemoon.org/systemrequirements.shtml][system requirements]])
  - Based on our own optimized layout and rendering engine, Goanna™
  - Safe: forked from mature Mozilla platform code and regularly updated with the latest security patches
  - Secure: Additional security features and security-aware development
  - Extensible with a growing number of maintained XUL browser extensions
  - Supported by our user community, and fully non-profit
  - Privacy-aware: zero ads; no telemetry, spyware or data gathering
  - Familiar, efficient, fully customizable interface
  - Support for full themes: total freedom for any element's design
  - Smooth and speedy page drawing and script processing
  - Superior gradients and fonts compared to other rendering engines
  - Continued support for NPAPI plugins like Silverlight, Adobe Flash and Java
  - Extensive and growing support for existing web standards


  This browser, even though fairly close to Gecko-based browsers like Mozilla Firefox and SeaMonkey in the way it works, is based on a different (forked) layout engine and offers a different set of features.  It aims to provide close adherence to a balanced set of official, common-sense web standards and specifications in its implementation (with minimal compromise), and purposefully excludes a number of features and Web APIs to strike a balance between general use, performance, privacy, and technical advancements on the Web.

  Pale Moon will continue to provide grouped navigation buttons of a decent size, a bookmarks toolbar that is enabled by default, tabs next to page content by default (easily switchable) and not in the least a functional status bar and more freedom in customization, to name a few things.  Its support for classic XUL extensions and full themes also provides users with powerful tools and options to change, extend and control the browser and its user interface.

  Pale Moon is, and will always be, Open Source and completely FREE to download and use!

  This browser is released as a community project to aim for open, collaborative development of a full-featured web browser, as much designed by the user as it is by our development team.  Everyone is welcome to become involved in its development or to write extensions to enhance their browsing experience!  It is released "as-is" and in the hope that it will be useful to its users.

  This project is community-supported to benefit the development of not only a web browser but any other application that builds on the freely available [[https://repo.palemoon.org/MoonchildProductions/UXP][XUL platform]] we are developing and using.  That means that if you enjoy the browser enough to help pay our bills for hosting, related on-line and off-line services, and especially further development and maintenance of the browser and underlying platform, you can support us through the following service:
#+end_quote
* (en.wikipedia.org) Pale Moon - Wikipedia                          :website:
:PROPERTIES:
:ID:       936974f0-76cf-4999-a3db-59fb10e1ab8b
:ROAM_REFS: https://en.wikipedia.org/wiki/Pale_Moon
:END:

#+begin_quote
  *Pale Moon* is a [[https://en.wikipedia.org/wiki/Free_and_open-source_software][free and open-source]] [[https://en.wikipedia.org/wiki/Web_browser][web browser]] licensed under the [[https://en.wikipedia.org/wiki/MPL2.0][MPL-2.0]] with an emphasis on customization.  There are official releases for [[https://en.wikipedia.org/wiki/Microsoft_Windows][Microsoft Windows]], [[https://en.wikipedia.org/wiki/FreeBSD][FreeBSD]], [[https://en.wikipedia.org/wiki/MacOS][macOS]], and [[https://en.wikipedia.org/wiki/Linux][Linux]].

  Pale Moon originated as a [[https://en.wikipedia.org/wiki/Fork_(software_development)][fork]] of [[https://en.wikipedia.org/wiki/Firefox][Firefox]], but has subsequently diverged.  The main differences are the [[https://en.wikipedia.org/wiki/User_interface][user interface]], [[https://en.wikipedia.org/wiki/Add-on_(Mozilla)][add-on]] support, and running in single-[[https://en.wikipedia.org/wiki/Process_(computing)][process]] mode.  Pale Moon retains the user interface of Firefox from versions 4 to 28 and supports legacy Firefox add-ons.

  Its motto is "Your browser, Your way."
#+end_quote
