:PROPERTIES:
:ID:       34a6d6d5-128a-483e-8d57-8b8f01f2c1ad
:END:
#+title: ARM
#+filetags: :arm_holdings:electronics:processor:microprocessor:computer_architecture:computer_science:

ARM, formerly Advanced RISC Machines and originally Acorn RISC Machine, is a family of [[id:321ba3cc-d73a-4620-88f7-2527cbae1aac][RISC]] [[id:c980a340-2564-437e-a79f-388122a206ad][ISA]]s and corresponding microprocessors.
* (en.wikipedia.org) ARM architecture family - Wikipedia            :website:
:PROPERTIES:
:ID:       5f33ceda-e7fd-4ba4-9b1b-8a3174566ec0
:ROAM_REFS: https://en.wikipedia.org/wiki/ARM_architecture_family
:END:

#+begin_quote
  *ARM* (stylised in lowercase as *arm*, formerly an acronym for *Advanced RISC Machines* and originally *Acorn RISC Machine*) is a family of [[https://en.wikipedia.org/wiki/Reduced_instruction_set_computer][RISC]] [[https://en.wikipedia.org/wiki/Instruction_set_architecture][instruction set architectures]] (ISAs) for [[https://en.wikipedia.org/wiki/Central_processing_unit][computer processors]].  [[https://en.wikipedia.org/wiki/Arm_Holdings][Arm Holdings]] develops the ISAs and licenses them to other companies, who build the physical devices that use the instruction set.  It also designs and licenses [[https://en.wikipedia.org/wiki/Semiconductor_intellectual_property_core][cores]] that implement these ISAs.

  Due to their low costs, low power consumption, and low heat generation, ARM processors are useful for light, portable, battery-powered devices, including [[https://en.wikipedia.org/wiki/Smartphone][smartphones]], [[https://en.wikipedia.org/wiki/Laptop][laptops]], and [[https://en.wikipedia.org/wiki/Tablet_computer][tablet computers]], as well as [[https://en.wikipedia.org/wiki/Embedded_system][embedded systems]].  However, ARM processors are also used for [[https://en.wikipedia.org/wiki/Desktop_computer][desktops]] and [[https://en.wikipedia.org/wiki/Server_(computing)][servers]], including [[https://en.wikipedia.org/wiki/Fugaku_(supercomputer)][Fugaku]], the world's fastest [[https://en.wikipedia.org/wiki/Supercomputer][supercomputer]] from 2020 to 2022.  With over 230 billion ARM chips produced, since at least 2003, and with its dominance increasing every year, ARM is the most widely used family of instruction set architectures.

  There have been several generations of the ARM design.  The original ARM1 used a [[https://en.wikipedia.org/wiki/32-bit_computing][32-bit]] internal structure but had a 26-bit [[https://en.wikipedia.org/wiki/Address_space][address space]] that limited it to 64 MB of [[https://en.wikipedia.org/wiki/Main_memory][main memory]].  This limitation was removed in the ARMv3 series, which has a 32-bit address space, and several additional generations up to ARMv7 remained 32-bit.  Released in 2011, the ARMv8-A architecture added support for a [[https://en.wikipedia.org/wiki/64-bit_computing][64-bit]] address space and 64-bit arithmetic with its new 32-bit fixed-length instruction set.  Arm Holdings has also released a series of additional instruction sets for different rules; the "Thumb" extension adds both 32- and 16-bit instructions for improved [[https://en.wikipedia.org/wiki/Code_density][code density]], while [[https://en.wikipedia.org/wiki/Jazelle][Jazelle]] added instructions for directly handling [[https://en.wikipedia.org/wiki/Java_bytecode][Java bytecode]].  More recent changes include the addition of [[https://en.wikipedia.org/wiki/Simultaneous_multithreading][simultaneous multithreading]] (SMT) for improved performance or [[https://en.wikipedia.org/wiki/Fault_tolerance][fault tolerance]].
#+end_quote
