:PROPERTIES:
:ID:       e4458b32-801d-48b8-8fa5-b021c7406e2d
:ROAM_ALIASES: WYSIWYG "What You See Is What You Get"
:END:
#+title: WYSIWYG (What You See Is What You Get)
#+filetags: :human_interaction:computer_science:design:

/What you see is what you get/.  A description of software that displays content for editing in it's intended final form as opposed to as some intermediate representation or markup.  Adjunct to [[id:348bc7ac-4d8d-4fae-8e25-97ae9fd957a8][WYSIWYM]].
* (en.wikipedia.org) WYSIWYG - Wikipedia                            :website:
:PROPERTIES:
:ID:       6a0fedd8-77cb-48ff-a1cd-4b455e1eca01
:ROAM_REFS: https://en.wikipedia.org/wiki/WYSIWYG
:END:

#+begin_quote
  In [[https://en.wikipedia.org/wiki/Computing][computing]], *WYSIWYG* ([[https://en.wikipedia.org/wiki/Help:IPA/English][/ˈwɪziwɪɡ/]] [[https://en.wikipedia.org/wiki/Help:Pronunciation_respelling_key][/WIZ-ee-wig/]]), an [[https://en.wikipedia.org/wiki/Acronym][acronym]] for *what you see is what you get*, refers to software that allows content to be edited in a form that resembles its appearance when printed or displayed as a finished product, such as a printed document, web page, or slide presentation.  WYSIWYG implies a [[https://en.wikipedia.org/wiki/User_interface][user interface]] that allows the user to view something very similar to the result while the document is being created.  In general, WYSIWYG implies the ability to directly manipulate the [[https://en.wikipedia.org/wiki/Page_layout][layout]] of a document without having to type or remember names of layout commands.
#+end_quote
