:PROPERTIES:
:ID:       110cad27-318a-47d0-82e6-fdf39388bb2f
:END:
#+title: Overleaf
#+filetags: :typesetting:latex:open_source:software:

[[id:a3c19488-876c-4b17-81c0-67b9c7fc64ee][Open-source]], [[id:48eb0495-be6d-4192-afa1-e1be5330070b][SaaS]] [[id:669335f2-8499-4ee6-b6b8-317c0c4f96ed][LaTeX]] [[id:e4458b32-801d-48b8-8fa5-b021c7406e2d][WYSIWYG]] editor.
* (www.overleaf.com) Overleaf, Online LaTeX Editor                  :website:
:PROPERTIES:
:ID:       77d17fca-fcac-429e-a0ee-d7d5ffd6cb9c
:ROAM_REFS: https://www.overleaf.com/
:END:

#+begin_quote
  Write like a rocket scientist with Overleaf —the collaborative, online LaTeX editor that anyone can use.
#+end_quote
* (github.com) overleaf/overleaf: A web-based collaborative LaTeX editor :website:
:PROPERTIES:
:ID:       fdacbcc1-3f17-401b-a1e7-06a1ec90f5d0
:ROAM_REFS: https://github.com/overleaf/overleaf/
:END:

#+begin_quote
  **** An open-source online real-time collaborative LaTeX editor.

  [[https://github.com/overleaf/overleaf/wiki][Wiki]] • [[https://www.overleaf.com/for/enterprises][Server Pro]] • [[https://github.com/overleaf/overleaf/#contributing][Contributing]] • [[https://mailchi.mp/overleaf.com/community-edition-and-server-pro][Mailing List]] • [[https://github.com/overleaf/overleaf/#authors][Authors]] • [[https://github.com/overleaf/overleaf/#license][License]]

  ** Community Edition

  [[https://www.overleaf.com/][Overleaf]] is an open-source online real-time collaborative LaTeX editor.  We run a hosted version at [[https://www.overleaf.com/][www.overleaf.com]], but you can also run your own local version, and contribute to the development of Overleaf.

  ** Enterprise

  If you want help installing and maintaining Overleaf in your lab or workplace, we offer an officially supported version called [[https://www.overleaf.com/for/enterprises][Overleaf Server Pro]].  It also includes more features for security (SSO with LDAP or SAML), administration and collaboration (e.g. tracked changes). [[https://www.overleaf.com/for/enterprises][Find out more!]]
#+end_quote
* (en.wikipedia.org) Overleaf - Wikipedia                           :website:
:PROPERTIES:
:ID:       1d44cbcc-6aeb-4888-95ac-6c091a9c0781
:ROAM_REFS: https://en.wikipedia.org/wiki/Overleaf
:END:

#+begin_quote
  *Overleaf* is a collaborative cloud-based [[https://en.wikipedia.org/wiki/LaTeX][LaTeX]] editor used for writing, editing and publishing scientific documents.

  It partners with a wide range of scientific publishers to provide official journal LaTeX templates, and direct submission links.

  Overleaf was conceived by John Hammersley and John Lees-Miller, who started developing it in 2011 as WriteLaTeX, through their company WriteLaTeX Limited.  Both are mathematicians and were inspired by their own experiences in academia to create a better solution for collaborative scientific writing.  They launched a beta version of Overleaf on 16 January 2014, at the first #FuturePub event, held at the British Library in London.

  After merging with ShareLaTeX in 2017, they released Overleaf v2, combining original features from both into a single cloud-based platform.
#+end_quote
