:PROPERTIES:
:ID:       8db7bd22-93ea-4270-86a0-2e97ef6da7e6
:END:
#+title: Pure Data
#+filetags: :open_source:programming:programming_language:software:

[[id:a3c19488-876c-4b17-81c0-67b9c7fc64ee][Open-source]], visual multi-media [[id:b24601aa-09df-41e1-aa7e-25ead342db34][programming]] system.
* (puredata.info) Pure Data — Pd Community Site                     :website:
:PROPERTIES:
:ID:       b20b774a-ae3b-442b-abed-8d1beb2df66e
:ROAM_REFS: https://puredata.info/
:END:

#+begin_quote
  * Pure Data

  by [[https://puredata.info/author/millerpuckette][Miller Puckette]] --- last modified 2023-09-22 08:43 AM

  *** Welcome to the Pure Data site!

  This site is a contribution of the [[http://iem.at/][IEM]] to the Pure Data community.  Every Pure Data user who wants to contribute is welcome to [[https://puredata.info/join_form][join]] this portal and write/contribute some documentation, reports, news, comments and announcing events.  The site is run on a Linux server with [[http://zope.org/][Zope]] / [[http://plone.org/][plone]] and administrated and driven by the Pure Data community.

  ** About Pure Data (aka "Pd" / "Pd Vanilla")

  *Pure Data* (or just "Pd") is an open source visual programming language for multimedia.  Pure Data is developed by Miller Puckette since 1996 and you can find it on [[https://msp.ucsd.edu/][his official website]] along with the official documentation and other related resources.  This is the official "Pd" or "main distribution" and it is also known as "Pd Vanilla", but there are other forks or "flavours".
#+end_quote
* (en.wikipedia.org) Pure Data - Wikipedia                          :website:
:PROPERTIES:
:ID:       076411f8-46c4-4e06-9d35-e0d353897b7f
:ROAM_REFS: https://en.wikipedia.org/wiki/Pure_Data
:END:

#+begin_quote
  *Pure Data* (*Pd*) is a [[https://en.wikipedia.org/wiki/Visual_programming_language][visual programming language]] developed by [[https://en.wikipedia.org/wiki/Miller_Puckette][Miller Puckette]] in the 1990s for creating interactive [[https://en.wikipedia.org/wiki/Computer_music][computer music]] and [[https://en.wikipedia.org/wiki/Multimedia][multimedia]] works.  While Puckette is the main author of the program, Pd is an [[https://en.wikipedia.org/wiki/Open-source_software][open-source]] project with a large developer base working on new extensions.  It is released under [[https://en.wikipedia.org/wiki/BSD_licenses][BSD-3-Clause]].  It runs on [[https://en.wikipedia.org/wiki/Linux][Linux]], [[https://en.wikipedia.org/wiki/MacOS][MacOS]], [[https://en.wikipedia.org/wiki/IOS][iOS]], [[https://en.wikipedia.org/wiki/Android_(operating_system)][Android]] and [[https://en.wikipedia.org/wiki/Windows][Windows]].  Ports exist for [[https://en.wikipedia.org/wiki/FreeBSD][FreeBSD]] and [[https://en.wikipedia.org/wiki/IRIX][IRIX]].

  Pd is very similar in scope and design to Puckette's original [[https://en.wikipedia.org/wiki/Max_(software)][Max]] program, developed while he was at [[https://en.wikipedia.org/wiki/IRCAM][IRCAM]], and is to some degree interoperable with Max/MSP, the commercial predecessor to the Max language.  They may be collectively discussed as members of the Patcher family of languages.

  With the addition of the [[https://en.wikipedia.org/wiki/Graphics_Environment_for_Multimedia][Graphics Environment for Multimedia]] (GEM) external, and externals designed to work with it (like [[https://en.wikipedia.org/w/index.php?title=Pure_Data_Packet&action=edit&redlink=1][Pure Data Packet]] / [[https://en.wikipedia.org/w/index.php?title=PiDiP&action=edit&redlink=1][PiDiP]] for Linux, Mac OS X), [[https://en.wikipedia.org/w/index.php?title=Framestein&action=edit&redlink=1][framestein]] for Windows, [[https://en.wikipedia.org/w/index.php?title=GridFlow&action=edit&redlink=1][GridFlow]] (as n-dimensional matrix processing, for Linux, Mac OS X, Windows), it is possible to create and manipulate video, [[https://en.wikipedia.org/wiki/OpenGL][OpenGL]] graphics, images, etc., in realtime with extensive possibilities for interactivity with audio, external sensors, etc.

  Pd is natively designed to enable live collaboration across networks or the Internet, allowing musicians connected via LAN or even in disparate parts of the globe to create music together in real time.  Pd uses [[https://en.wikipedia.org/wiki/FUDI][FUDI]] as a networking protocol.
#+end_quote
