:PROPERTIES:
:ID:       b75c340b-8f56-42df-a8bd-2cdaab4a530d
:END:
#+title: Designing Data-Intensive Applications: The Big Ideas Behind Reliable, Scalable, and Maintainable Systems
#+filetags: :databases:distributed_software:software_development:computer_science:books:

* (dataintensive.net) Designing Data-Intensive Applications (DDIA) — an O’Reilly book by Martin Kleppmann (The Wild Boar Book) :website:
:PROPERTIES:
:ID:       36103797-4511-4c24-b19d-e96e95f3b007
:ROAM_REFS: https://dataintensive.net/
:END:

#+begin_quote
  * Don't just hack it together

  NoSQL... Big Data... Scalability... CAP Theorem... Eventual Consistency... Sharding...

  Nice buzzwords, but how does the stuff actually /work/?

  As software engineers, we need to build applications that are reliable, scalable and maintainable in the long run.  We need to understand the range of available tools and their trade-offs.  For that, we have to dig deeper than buzzwords.

  This book will help you navigate the diverse and fast-changing landscape of technologies for storing and processing data.  We compare a broad variety of tools and approaches, so that you can see the strengths and weaknesses of each, and decide what's best for your application.
#+end_quote
* (www.oreilly.com) Designing Data-Intensive Applications, 2nd Edition[Book] :website:
:PROPERTIES:
:ID:       0a177b13-aecb-4f33-a45b-30b0b090614b
:ROAM_REFS: https://www.oreilly.com/library/view/designing-data-intensive-applications/9781098119058/
:END:

#+begin_quote
  * Designing Data-Intensive Applications, 2nd Edition

  by [[https://www.oreilly.com/search?q=author:%22Martin%20Kleppmann%22][Martin Kleppmann]], [[https://www.oreilly.com/search?q=author:%22Chris%20Riccomini%22][Chris Riccomini]]

  Released December 2025

  Publisher(s): O'Reilly Media, Inc.

  ISBN: 9781098119065

  ** Book description

  Data is at the center of many challenges in system design today.  Difficult issues such as scalability, consistency, reliability, efficiency, and maintainability need to be resolved.  In addition, there's an overwhelming variety of tools and analytical systems, including relational databases, NoSQL datastores, plus data warehouses and data lakes.  What are the right choices for your application?  How do you make sense of all these buzzwords?

  In this second edition, authors Martin Kleppmann and Chris Riccomini build on the foundation laid in the acclaimed first edition, integrating new technologies and emerging trends.  You'll be guided through the maze of decisions and trade-offs involved in building a modern data system, from choosing the right tools like Spark and Flink to understanding the intricacies of data laws like the GDPR.

  - Peer under the hood of the systems you already use, and learn to use them more effectively
  - Make informed decisions by identifying the strengths and weaknesses of different tools
  - Navigate the trade-offs around consistency, scalability, fault tolerance, and complexity
  - Understand the distributed systems research upon which modern databases are built
  - Peek behind the scenes of major online services, and learn from their architectures
#+end_quote
