:PROPERTIES:
:ID:       3993f70e-5bae-48a1-84c9-d9e18a911dda
:ROAM_REFS: https://aiimpacts.org/scale-of-the-human-brain/
:END:
#+title: (aiimpacts.org) Scale of the Human Brain – AI Impacts
#+filetags: :neuroscience:biology:website:

#+begin_quote
  # Scale of the Human Brain
  The brain has about 10¹¹ neurons and 1.8-3.2 x 10¹⁴ synapses.  These probably account for the majority of computationally interesting behavior.

  ## Support
  ### Number of neurons in the brain
  The number of neurons in the brain is about 10¹¹.  For instance, Azevado et al physically counted them and found 0.6-1 * 10¹¹.  Eric Chudler has collected estimates from a range of textbooks, which estimate 1-2 x 10¹⁰ of these (10%-30%) are in the cerebral cortex.

  ### Number of synapses in the brain
  The number of synapses in the brain is known much less precisely, but is probably about 10¹⁴.  For instance Human-memory.net reports 10¹⁴-10¹⁵ (100 – 1000 trillion) synapses in the brain, with no citation or explanation.  Wikipedia says the brain contains 100 billion neurons, with 7,000 synaptic connections each, for 7 x 10¹⁴ synapses in total, but this seems possibly in error.

  ### Number of synapses in the neocortex
  One way to estimate of the number of synapses in the brain is to extrapolate from the number in the neocortex.  According to stereologic studies that we have not investigated, there are around 1.4 x 10¹⁴ synapses in the neocortex.  This is roughly consistent with Eric Chudler’s summary of textbooks, which gives estimates between 0.6-2.4 x 10¹⁴ for the number of synapses in the cerebral cortex.
  We are not aware of convincing estimates for synaptic density outside of the cerebral cortex, and our impression is that widely reported estimates of 10¹⁴ are derived from the assumption that the neocortex contains the great bulk of synapses in the brain.  This seems plausible given the large volume of the neocortex, despite the fact that it contains a minority of the brain’s neurons.  By volume, around 80% of the human brain is neocortex.  The neocortex also consumes around 44% of the brain’s total energy, which may be another reasonable indicator of the fraction of synapses in contains.  So our guess is that the number of synapses in the entire brain is somewhere between 1.3 and 2.3 times the number in the cerebral cortex.  From above, the cerebral cortex contains around 1.4 x 10¹⁴ synapses, so this gives us 1.8-3.2 x 10¹⁴ total synapses.

  ### Number of synapses per neuron
  The number of synapses per neuron varies considerably.  According to Wikipedia, the majority of neurons are cerebellum granule cells, which have only a handful of synapses, while the statistics above suggest that the average neuron has around 1,000 synapses.  Purkinje cells have up to 200,000 synapses.

  ### Number of glial cells in the brain
  Azevado et al aforementioned investigation finds about 10¹¹ glial cells (the same as the number of neurons).

  ### Relevance of cells other than neurons to computations in the brain
  It seems that the timescales of glial dynamics are substantially longer than for neuron dynamics.  Sandberg and Bostrom write: “However, the time constants for glial calcium dynamics is generally far slower than the dynamics of action potentials (on the order of seconds or more), suggesting that the time resolution would not have to be as fine” (p. 36).  This suggests that the computational role of glial cells is not too great.  References to much larger numbers of glial cells appear to be common, but we were unable to track down any empirical research supporting these claims.  An informal blog post suggests that a common claim that there are ten times as many glial cells as neurons may be a popular myth.
  We are not aware of serious suggestions that cells other than neurons or glia play a computationally significant role in the functioning of the brain.
#+end_quote
