:PROPERTIES:
:ID:       0e57e0d7-42f4-4666-836d-b468bc40a924
:ROAM_REFS: https://arxiv.org/abs/2503.13877
:END:
#+title: (arxiv.org) [2503.13877] Shock with Confidence: Formal Proofs of Correctness for Hyperbolic Partial Differential Equation Solvers
#+filetags: :mathematics:science_paper:website:

#+begin_quote
  * Shock with Confidence: Formal Proofs of Correctness for Hyperbolic Partial Differential Equation Solvers

  Authors: [[https://arxiv.org/search/cs?searchtype=author&query=Gorard,+J][Jonathan Gorard]], [[https://arxiv.org/search/cs?searchtype=author&query=Hakim,+A][Ammar Hakim]]

  First-order systems of hyperbolic partial differential equations (PDEs) occur ubiquitously throughout computational physics, commonly used in simulations of fluid turbulence, shock waves, electromagnetic interactions, and even general relativistic phenomena.  Such equations are often challenging to solve numerically in the non-linear case, due to their tendency to form discontinuities even for smooth initial data, which can cause numerical algorithms to become unstable, violate conservation laws, or converge to physically incorrect solutions.  In this paper, we introduce a new formal verification pipeline for such algorithms in Racket, which allows a user to construct a bespoke hyperbolic PDE solver for a specified equation system, generate low-level C code which verifiably implements that solver, and then produce formal proofs of various mathematical and physical correctness properties of the resulting implementation, including L^2 stability, flux conservation, and physical validity.  We outline how these correctness proofs are generated, using a custom-built theorem-proving and automatic differentiation framework that fully respects the algebraic structure of floating-point arithmetic, and show how the resulting C code may either be used to run standalone simulations, or integrated into a larger computational multiphysics framework such as Gkeyll.
#+end_quote
