:PROPERTIES:
:ID:       f441b1d6-d151-43b2-8fca-3d8567c1f0cf
:ROAM_REFS: https://bodydoubling.com/
:END:
#+title: (bodydoubling.com) Body Doubling | Find a [virtual] body double!
#+filetags: :productivity:website:

#+begin_quote
  * Join the Body Doubling Movement

  Working together for increased productivity

  *** “WHAT IS BODY DOUBLING?

  In simple terms, it's merely being in the same room with another person who is having trouble getting things done on their own.  As a body double, you don't need to help or even say anything.  All you need to do is just be there in the room, and through some invisible power, the other person is able to focus and finish their work.  Buddies can do this over the phone for hours, simply keeping the line open---sometimes speaking, but mostly just silently being there.”

  -- Greg Riccardi in [[https://chadd.org/wp-content/uploads/2018/06/ATTN_04_15_RICCARDI.pdf][/Sometimes It Takes Two/]]

  “Many people with ADHD find it easier to */stay focused/* on housework, homework, bill paying, and other tasks when someone else is around to keep them company.  The body double may just sit quietly.  He may read, listen to music on headphones, or work on the task that the person with ADHD is working on.  Hard work is simply more fun when someone else is nearby.” \\
  -- Patricia Quinn M.D., [[https://www.additudemag.com/getting-stuff-done-easier-with-a-friend-body-double/][ADDitudeMag.com]]

  “Though reluctantly, David had identified a *strategy that really worked* for him.  I realized instantly that I had seen this same effect before with other clients.  There were times when *just being in proximity*, not advising, sorting, or strategizing, brought *clarity and focus* to the client.  I /felt/ it.  I knew the client felt it, too.  This phenomenon of /*just being there*/, which David first described out loud, I named */the body double/*.”\\
  -- Linda Anderson, MA, MCC, SAC

  It is common for neurodivergent folks (among others) to benefit from having another person's presence available while they work.  Simply by being around others, many find their executive dysfunction start to, well, function.  Even virtually this works, enabling people to remain productive.

  *The mission of this site* is to provide a gateway to body doubling for all who benefit from doing it.  The collective acceptance and understanding of what body doubling is and of its benefits is rapidly developing.  BodyDoubling.com strives to be a central body doubling hub providing access and support to its users.

  As of this writing, this site is exclusively run by me -- and while I would prefer to devote all of my time to my passion project -- I cannot afford to, yet.  It turns out that not charging people (even with solid reasoning) is not a good business tactic.  I /will not/ charge, so if you are able to donate any amount it is greatly appreciated and can be considered [[https://bodydoubling.com/support/][support]] of the astounding community that I have found here.

  -- Sean

  ** Work Together

  Finding someone has never been easier.  Register for BodyDoubling.com, then search our forums to find a virtual (while COVID-19 is still a thing) body double!

  [[https://bodydoubling.com/wp-login.php?action=register][Register]]

  BodyDoubling.com does *not* offer medical/health advice.  Please see our [[https://bodydoubling.com/bodydoubling.com/disclaimer/][disclaimer]] for more information.

  ** Contact Us

  Please don't hesitate to reach out for -- well, anything!  We accept suggestions/thoughts/recommendations/requests for support or whatever you'd like to share w/us.
#+end_quote
