:PROPERTIES:
:ID:       6a49f1f6-716a-4d98-ae17-3a3c75d60846
:ROAM_REFS: https://chem.libretexts.org/Bookshelves/Inorganic_Chemistry/Supplemental_Modules_and_Websites_(Inorganic_Chemistry)/Descriptive_Chemistry/Main_Group_Reactions/Hard_Water
:END:
#+title: (chem.libretexts.org) Hard Water - Chemistry LibreTexts
#+filetags: :chemistry:website:

#+begin_quote
  Hard water contains high amounts of minerals in the form of ions, especially the metals calcium and magnesium, which can precipitate out and cause problems in water cconducting or storing vessels like pipes.  Hard water can be distinguished from other types of water by its metallic, dry taste and the dry feeling it leaves on skin.  It is responsible for the scum rings seen in bathtubs, as well as the inability of soap to lather.

  ** Types of Hard Water

  Hard water is water containing high amounts of mineral ions.  The most common ions found in hard water are the metal cations calcium (\(Ca^{2+}\)) and magnesium (\(Mg^{2+}\)), though iron, aluminum, and manganese may also be found in certain areas.  These metals are water soluble, meaning they will dissolve in water.  The relatively high concentrations of these ions can saturate the solution and consequently cause the equilibrium of these solutes to shift to the left, towards reactants.  In other words, the ions can precipitate out of the solution.  This displacement of minerals from the solution is responsible for the calcination often seen on water faucets, which is a precipitation of calcium or magnesium carbonate.  Hard water may also react with other substances in the solution, such as soap, and form a precipitate called "scum." There are two defined types of hard water, temporary and permanent, which are described below.

  *** Temporary Hard Water

  Temporary hard water is hard water that consists primarily of calcium (\(Ca^{2+}\)) and bicarbonate (\(HCO_{3}^{-}\)) ions.  Heating causes the bicarbonate ion in temporary hard water to decompose into carbonate ion (\(CO_{3}^{2-}\)), carbon dioxide (\(CO_{2}\)), and water (\(H_{2}O\)).  The resultant carbonate ion (\(CO_{3}^{2-}\)) can then react with other ions in the solution to form insoluble compounds, such as \(CaCO_{3}\) and \(MgCO_{3}\).  The interactions of carbonate ion in the solution also cause the well-known mineral build-up seen on the sides of pots used to boil water, a rust known as "boiler scale." Increasing the temperature of temporary hard water, with its resultant decomposition of the bicarbonate ion, signifies a shift in the equilibrium equation (shown below).  The high temperature causes the equilibrium to shift to the left, causing precipitation of the initial reactants.

  \[CaCO_{3 \; (s)} + CO_{2 \; (aq)} + H_2O_{(l)} \rightleftharpoons Ca^{2+}_{(aq)} + 2HCO^-_{3 \; (aq)} \tag{1} \]

  This shift is responsible for the white scale observed in the boiling containers described above, as well as the mineral deposits that build up inside water pipes, resulting in inefficiency and even explosion due to overheating.  The \(CaCO_{3}\) or other scale does not completely dissolve back into the water when it is cooled because it is relatively insoluble, as shown by its small solubility constant.  For this reason, this type of hard water is "temporary" because boiling can remove the hardness by displacing the offending ions from solution.

  \[CaCO_{3 \; (s)} \rightleftharpoons Ca^{2+}_{(aq)} + CO^{2-}_{3 \; (aq)} \tag{2a} \]

  \[K_{(sp)} = 2.8 \times 10^{-9} \tag{2b} \]

  *** Permanent Hard Water

  Permanent hard water consists of high concentrations of anions, like the sulfate anion (\(SO_{4}^{2-}\)).  This type of hard water is referred to as "permanent" because, unlike temporary hard water, the hardness cannot be removed simply by boiling the water and thereby precipitating out the mineral ions.  However, the name is deceiving as "permanent" hard water can be softened by other means.  The scale caused by permanent hard water has detrimental effects similar to those seen with temporary hard water, such as obstruction of water flow in pipes.  Permanent hard water is also responsible for the bathtub "ring," or soap scum, seen after showering or bathing.  As previously mentioned, permanent hard water contains calcium and magnesium cations.  These cations react with soap to form insoluble compounds that are then deposited on the sides of the tub.  Additionally, the reaction of these cations with soap is the reason it is difficult for soap to foam or lather well in hard water.  The equation below gives an example of the reaction of magnesium ion with components of soap, in this case stearate (\(C_{18}H_{35}O_{2}^{2-}\)), to form the insoluble compound magnesium stearate, which is responsible for the infamous soap scum.

  \[2(C_{18}H_{35}O_2)^{2-}_{(aq)} + Mg^{2+}_{(aq)} \longrightarrow Mg(C_{18}H_{35}O_2)_{2 \; (s)} \tag{3} \]
#+end_quote
