:PROPERTIES:
:ID:       f9becc17-636b-4671-b28c-5ae6fe8bb5fa
:ROAM_REFS: https://dspace.mit.edu/handle/1721.1/5794
:END:
#+title: (dspace.mit.edu) SCHEME: An Interpreter for Extended Lambda Calculus
#+filetags: :website:

#+begin_quote
  ** SCHEME: An Interpreter for Extended Lambda Calculus

  ***** Author(s)

  Sussman, Gerald J.; Steele, Guy L., Jr.

  ***** Abstract

  Inspired by ACTORS [Greif and Hewitt] [Smith and Hewitt], we have implemented an interpreter for a LISP-like language, SCHEME, based on the lambda calculus [Church], but extended for side effects, multiprocessing, and process synchronization.  The purpose of this implementation is tutorial.  We wish to: (1) alleviate the confusion caused by Micro-PLANNER, CONNIVER, etc. by clarifying the embedding of non-recursive control structures in a recursive host language like LISP.  (2) explain how to use these control structures, independent of such issues as pattern matching and data base manipulation.  (3) have a simple concrete experimental domain for certain issues of programming semantics and style.

  ***** Date issued

  1975-12-01

  ***** URI

  [[http://hdl.handle.net/1721.1/5794]]

  ***** Other identifiers

  AIM-349

  ***** Series/Report no.

  AIM-349
#+end_quote
* (dspace.mit.edu) SCHEME: An Interpreter for Extended Lambda Calculus (AIM-349.pdf) :mime_type_application_pdf:
:PROPERTIES:
:ID:       1123e3d6-6f9f-4fa8-b001-1a39b23fc4ed
:ROAM_REFS: https://dspace.mit.edu/bitstream/handle/1721.1/5794/AIM-349.pdf
:END:
