:PROPERTIES:
:ID:       8f7dc454-0ec6-4bff-8708-9cda4baa75bd
:ROAM_REFS: https://en.wikipedia.org/wiki/Johnson–Nyquist_noise
:END:
#+title: (en.wikipedia.org) Johnson–Nyquist noise - Wikipedia
#+filetags: :thermodynamics:physics:website:

#+begin_quote
  Johnson–Nyquist noise (thermal noise, Johnson noise, or Nyquist noise) is the electronic noise generated by the thermal agitation of the charge carriers (usually the electrons) inside an electrical conductor at equilibrium, which happens regardless of any applied voltage.  Thermal noise is present in all electrical circuits, and in sensitive electronic equipment (such as radio receivers) can drown out weak signals, and can be the limiting factor on sensitivity of electrical measuring instruments.  Thermal noise is proportional to absolute temperature, so some sensitive electronic equipment such as radio telescope receivers are cooled to cryogenic temperatures to improve their signal-to-noise ratio.  The generic, statistical physical derivation of this noise is called the fluctuation-dissipation theorem, where generalized impedance or generalized susceptibility is used to characterize the medium.
  Thermal noise in an ideal resistor is approximately white, meaning that its power spectral density is nearly constant throughout the frequency spectrum (Figure 2).  When limited to a finite bandwidth and viewed in the time domain (as sketched in Figure 1), thermal noise has a nearly Gaussian amplitude distribution.
  For the general case, this definition applies to charge carriers in any type of conducting medium (e.g. ions in an electrolyte), not just resistors.  Thermal noise is distinct from shot noise, which consists of additional current fluctuations that occur when a voltage is applied and a macroscopic current starts to flow.
#+end_quote
