:PROPERTIES:
:ID:       94fbddd2-5fd5-40d9-bf2f-8fea5e71f3db
:ROAM_REFS: https://en.wikipedia.org/wiki/TI-84_Plus_series
:END:
#+title: (en.wikipedia.org) TI-84 Plus series - Wikipedia
#+filetags: :electronics:calculator:website:

#+begin_quote
  The *TI-84 Plus* is a [[https://en.wikipedia.org/wiki/Graphing_calculator][graphing calculator]] made by [[https://en.wikipedia.org/wiki/Texas_Instruments][Texas Instruments]] which was released in early 2004.  There is no original TI-84, only the TI-84 Plus, the TI-84 Plus Silver Edition models, the TI-84 Plus C Silver Edition, the TI-84 Plus CE, and TI-84 Plus CE Python.  The TI-84 Plus is an enhanced version of the [[https://en.wikipedia.org/wiki/TI-83_series][TI-83 Plus]].  The key-by-key correspondence is relatively the same, but the TI-84 features improved hardware.  The archive ([[https://en.wikipedia.org/wiki/Read-only_memory][ROM]]) is about 3 times as large, and the [[https://en.wikipedia.org/wiki/Central_processing_unit][CPU]] is about 2.5 times as fast (over the [[https://en.wikipedia.org/wiki/TI-83_series][TI-83]] and [[https://en.wikipedia.org/wiki/TI-83_series#TI-83_Plus][TI-83 Plus]]).  A [[https://en.wikipedia.org/wiki/USB][USB]] port and built-in clock functionality were also added.  The USB port on the TI-84 Plus series is [[https://en.wikipedia.org/wiki/USB_On-The-Go][USB On-The-Go]] compliant, similar to the next generation [[https://en.wikipedia.org/wiki/TI-Nspire][TI-Nspire]] calculator, which supports connecting to USB based data collection devices and probes, and supports device to device transfers over USB rather than over the serial link port.  It is also able to connect to a special TI application for calculator screenshots and image download.
#+end_quote
