:PROPERTIES:
:ID:       86b3de62-af82-4adc-8575-91d9d24d475b
:ROAM_REFS: https://en.wikipedia.org/wiki/Computer_access_control
:END:
#+title: (en.wikipedia.org) Computer access control - Wikipedia
#+filetags: :security:computer_science:website:

#+begin_quote
  In computer security, general access control includes identification, authorization, authentication, access approval, and audit.  A more narrow definition of access control would cover only access approval, whereby the system makes a decision to grant or reject an access request from an already authenticated subject, based on what the subject is authorized to access.  Authentication and access control are often combined into a single operation, so that access is approved based on successful authentication, or based on an anonymous access token.  Authentication methods and tokens include passwords, biometric scans, physical keys, electronic keys and devices, hidden paths, social barriers, and monitoring by humans and automated systems.
#+end_quote
