:PROPERTIES:
:ID:       e30d8076-1c96-4384-b5df-3fa6e337d4dc
:ROAM_REFS: https://en.wikipedia.org/wiki/Non-Newtonian_fluid
:END:
#+title: (en.wikipedia.org) Non-Newtonian fluid - Wikipedia
#+filetags: :physics:website:

#+begin_quote
  In [[https://en.wikipedia.org/wiki/Physics][physics]] and [[https://en.wikipedia.org/wiki/Chemistry][chemistry]], a *non-Newtonian fluid* is a [[https://en.wikipedia.org/wiki/Fluid][fluid]] that does not follow [[https://en.wikipedia.org/wiki/Newton's_law_of_viscosity][Newton's law of viscosity]], that is, it has variable viscosity dependent on [[https://en.wikipedia.org/wiki/Stress_(mechanics)][stress]].  In particular, the viscosity of non-Newtonian fluids can change when subjected to force.  [[https://en.wikipedia.org/wiki/Ketchup][Ketchup]], for example, becomes runnier when shaken and is thus a non-Newtonian fluid.  Many [[https://en.wikipedia.org/wiki/Salt][salt]] solutions and molten polymers are non-Newtonian fluids, as are many commonly found substances such as [[https://en.wikipedia.org/wiki/Custard][custard]], [[https://en.wikipedia.org/wiki/Toothpaste][toothpaste]], [[https://en.wikipedia.org/wiki/Starch][starch]] suspensions, [[https://en.wikipedia.org/wiki/Corn_starch][corn starch]], [[https://en.wikipedia.org/wiki/Paint][paint]], [[https://en.wikipedia.org/wiki/Blood][blood]], melted [[https://en.wikipedia.org/wiki/Butter][butter]] and [[https://en.wikipedia.org/wiki/Shampoo][shampoo]].

  Most commonly, the [[https://en.wikipedia.org/wiki/Viscosity][viscosity]] (the gradual deformation by shear or [[https://en.wikipedia.org/wiki/Tensile_stress][tensile stresses]]) of non-Newtonian fluids is dependent on [[https://en.wikipedia.org/wiki/Shear_rate][shear rate]] or shear rate history.  Some non-Newtonian fluids with shear-independent viscosity, however, still exhibit normal stress-differences or other non-Newtonian behavior.  In a Newtonian fluid, the relation between the [[https://en.wikipedia.org/wiki/Shear_stress][shear stress]] and the shear rate is linear, passing through the [[https://en.wikipedia.org/wiki/Origin_(mathematics)][origin]], the constant of proportionality being the coefficient of [[https://en.wikipedia.org/wiki/Viscosity][viscosity]].  In a non-Newtonian fluid, the relation between the shear stress and the shear rate is different.  The fluid can even exhibit [[https://en.wikipedia.org/wiki/Time-dependent_viscosity][time-dependent viscosity]].  Therefore, a constant coefficient of viscosity cannot be defined.

  Although the concept of viscosity is commonly used in [[https://en.wikipedia.org/wiki/Fluid_mechanics][fluid mechanics]] to characterize the shear properties of a fluid, it can be inadequate to describe non-Newtonian fluids.  They are best studied through several other [[https://en.wikipedia.org/wiki/Rheology][rheological]] properties that relate [[https://en.wikipedia.org/wiki/Stress_(physics)][stress]] and [[https://en.wikipedia.org/wiki/Strain_rate][strain rate]] tensors under many different flow conditions---such as [[https://en.wikipedia.org/wiki/Oscillation][oscillatory]] shear or extensional flow---which are measured using different devices or [[https://en.wikipedia.org/wiki/Rheometer][rheometers]].  The properties are better studied using [[https://en.wikipedia.org/wiki/Tensor][tensor]]-valued [[https://en.wikipedia.org/wiki/Constitutive_equations][constitutive equations]], which are common in the field of [[https://en.wikipedia.org/wiki/Continuum_mechanics][continuum mechanics]].

  For non-Newtonian fluid's [[https://en.wikipedia.org/wiki/Viscosity][viscosity]], there are [[https://en.wikipedia.org/wiki/Pseudoplastic][pseudoplastic]], [[https://en.wikipedia.org/wiki/Plastic_flow][plastic]], and [[https://en.wikipedia.org/wiki/Dilatant][dilatant]] flows that are time-independent, and there are [[https://en.wikipedia.org/wiki/Thixotropic][thixotropic]] and [[https://en.wikipedia.org/wiki/Rheopectic][rheopectic]] flows that are time-dependent.  Three well-known time-dependent non-newtonian fluids which can be identified by the defining authors are the Oldroyd-B model, Walters' Liquid B and Williamson fluids.

  Time-dependent [[https://en.wikipedia.org/wiki/Self-similar_solution][self-similar]] analysis of the [[https://en.wikipedia.org/wiki/Olga_Ladyzhenskaya][Ladyzenskaya]]-type model with a non-linear velocity dependent stress tensor was performed unfortunately no analytical solutions could be derived, however a rigorous mathematical existence theorem was given for the solution.

  For time-independent non-Newtonian fluids the known analytic solutions are much broader
#+end_quote
