:PROPERTIES:
:ID:       e87c5605-38ab-4659-95df-cb893292db25
:ROAM_REFS: https://en.wikipedia.org/wiki/Division_by_zero
:END:
#+title: (en.wikipedia.org) Division by zero - Wikipedia
#+filetags: :mathematics:website:

#+begin_quote
  In [[https://en.wikipedia.org/wiki/Mathematics][mathematics]], *division by zero*, [[https://en.wikipedia.org/wiki/Division_(mathematics)][division]] where the divisor (denominator) is [[https://en.wikipedia.org/wiki/0][zero]], is a unique and problematic special case.  Using [[https://en.wikipedia.org/wiki/Fraction][fraction]] notation, the general example can be written as \(\frac{a}{0}\), where \(a\) is the dividend (numerator).

  The usual definition of the [[https://en.wikipedia.org/wiki/Quotient][quotient]] in [[https://en.wikipedia.org/wiki/Elementary_arithmetic][elementary arithmetic]] is the number which yields the dividend when [[https://en.wikipedia.org/wiki/Multiplication][multiplied]] by the divisor.  That is, \(c = \frac{a}{b}\) is equivalent to \(c \cdot b = a.\) By this definition, the quotient \(q = \frac{a}{0}\) is nonsensical, as the product \(q \cdot 0\) is always \(0\) rather than some other number \(a.\) Following the ordinary rules of [[https://en.wikipedia.org/wiki/Elementary_algebra][elementary algebra]] while allowing division by zero can create a [[https://en.wikipedia.org/wiki/Mathematical_fallacy][mathematical fallacy]], a subtle mistake leading to absurd results.  To prevent this, the arithmetic of [[https://en.wikipedia.org/wiki/Real_number][real numbers]] and more general numerical structures called [[https://en.wikipedia.org/wiki/Field_(mathematics)][fields]] leaves division by zero [[https://en.wikipedia.org/wiki/Undefined_(mathematics)][undefined]], and situations where division by zero might occur must be treated with care.  Since any number multiplied by zero is zero, the expression [[https://en.wikipedia.org/wiki/0/0][\(\frac{0}{0}\)]] is also undefined.

  [[https://en.wikipedia.org/wiki/Calculus][Calculus]] studies the behavior of [[https://en.wikipedia.org/wiki/Function_(mathematics)][functions]] in the [[https://en.wikipedia.org/wiki/Limit_(mathematics)][limit]] as their input tends to some value.  When a [[https://en.wikipedia.org/wiki/Real_function][real function]] can be expressed as a fraction whose denominator tends to zero, the output of the function becomes arbitrarily large, and is said to "[[https://en.wikipedia.org/wiki/Limit_(mathematics)#Infinity_in_limits_of_functions][tend to infinity]]", a type of [[https://en.wikipedia.org/wiki/Mathematical_singularity][mathematical singularity]].  For example, the [[https://en.wikipedia.org/wiki/Reciprocal_function][reciprocal function]], \(f(x) = \frac{1}{x},\) tends to infinity as \(x\) tends to \(0.\) When both the numerator and the denominator tend to zero at the same input, the expression is said to take an [[https://en.wikipedia.org/wiki/Indeterminate_form#Indeterminate_form_0/0][indeterminate form]], as the resulting limit depends on the specific functions forming the fraction and cannot be determined from their separate limits.

  As an alternative to the common convention of working with fields such as the real numbers and leaving division by zero undefined, it is possible to define the result of division by zero in other ways, resulting in different number systems.  For example, the quotient \(\frac{a}{0}\) can be defined to equal zero; it can be defined to equal a new explicit [[https://en.wikipedia.org/wiki/Point_at_infinity][point at infinity]], sometimes denoted by the [[https://en.wikipedia.org/wiki/Infinity_symbol][infinity symbol]] \(\infty\); or it can be defined to result in signed infinity, with positive or negative sign depending on the sign of the dividend.  In these number systems division by zero is no longer a special exception per se, but the point or points at infinity involve their own new types of exceptional behavior.

  In [[https://en.wikipedia.org/wiki/Computer][computing]], an error may result from an attempt to divide by zero.  Depending on the context and the type of number involved, dividing by zero may evaluate to [[https://en.wikipedia.org/wiki/Extended_real_number_line][positive or negative infinity]], return a special [[https://en.wikipedia.org/wiki/NaN][not-a-number]] value, or [[https://en.wikipedia.org/wiki/Crash_(computing)][crash]] the program, among other possibilities.
#+end_quote
