:PROPERTIES:
:ID:       1f6f005e-95a7-4d64-a14b-e47000684083
:ROAM_REFS: https://en.wikipedia.org/wiki/Maemo
:END:
#+title: (en.wikipedia.org) Maemo - Wikipedia
#+filetags: :linux:software:operating_systems:website:

#+begin_quote
  *Maemo* is a [[https://en.wikipedia.org/wiki/Linux][Linux]]-based [[https://en.wikipedia.org/wiki/Software_platform][software platform]] originally developed by [[https://en.wikipedia.org/wiki/Nokia][Nokia]], now developed by the [[https://en.wikipedia.org/wiki/Free_software_movement][community]], for [[https://en.wikipedia.org/wiki/Smartphone][smartphones]] and [[https://en.wikipedia.org/wiki/Internet_tablet][Internet tablets]].  The platform comprises both the Maemo operating system and [[https://en.wikipedia.org/wiki/Software_development_kit][SDK]].  Maemo played a key role in Nokia's failed strategy to compete with [[https://en.wikipedia.org/wiki/Apple_Inc.][Apple]] and [[https://en.wikipedia.org/wiki/Android_(operating_system)][Android]]; the only retail devices that shipped with Maemo were the [[https://en.wikipedia.org/wiki/Nokia_Internet_tablet][Nokia Internet tablet]] line released in 2005 and the [[https://en.wikipedia.org/wiki/Nokia_N900][Nokia N900]] smartphone in 2009.

  Maemo is mostly based on [[https://en.wikipedia.org/wiki/Free_and_open-source_software][open-source]] code and has been developed by Maemo Devices within Nokia in collaboration with many open-source projects such as the [[https://en.wikipedia.org/wiki/Linux_kernel][Linux kernel]], [[https://en.wikipedia.org/wiki/Debian][Debian]], and [[https://en.wikipedia.org/wiki/GNOME][GNOME]].  Maemo is based on [[https://en.wikipedia.org/wiki/Debian][Debian]] and draws much of its [[https://en.wikipedia.org/wiki/GUI][GUI]], [[https://en.wikipedia.org/wiki/Software_framework][frameworks]], and [[https://en.wikipedia.org/wiki/Library_(computing)][libraries]] from the [[https://en.wikipedia.org/wiki/GNOME][GNOME]] project.  It uses the [[https://en.wikipedia.org/wiki/Matchbox_(window_manager)][Matchbox]] window manager and the [[https://en.wikipedia.org/wiki/GTK][GTK]]-based [[https://en.wikipedia.org/wiki/Hildon][Hildon]] framework as its GUI and [[https://en.wikipedia.org/wiki/Application_framework][application framework]].

  The [[https://en.wikipedia.org/wiki/User_interface][user interface]] in Maemo 4 is similar to many hand-held interfaces and features a "home" screen, from which all applications and settings are accessed.  The home screen is divided into areas for launching applications, a menu bar, and a large customizable area that can display information such as an [[https://en.wikipedia.org/wiki/News_aggregator][RSS reader]], [[https://en.wikipedia.org/wiki/Internet_radio][Internet radio]] player, and Google search box.  The Maemo 5 user interface is slightly different; the menu bar and info area are consolidated to the top of the display, and the four desktops can be customized with shortcuts and widgets.

  At the [[https://en.wikipedia.org/wiki/Mobile_World_Congress][Mobile World Congress]] in February 2010, it was announced that the Maemo project would be merging with [[https://en.wikipedia.org/wiki/Moblin][Moblin]] to create the [[https://en.wikipedia.org/wiki/MeeGo][MeeGo]] mobile software platform.  Despite that, the Maemo community continued to be active, and in late 2012 Nokia began transferring Maemo ownership to the [[https://en.wikipedia.org/wiki/Hildon_Foundation][Hildon Foundation]], which was replaced by a German association [[https://wiki.maemo.org/MaemoCommunity_eV][Maemo Community e.V.]] Since 2017, a new release called [[https://en.wikipedia.org/w/index.php?title=Maemo_Leste&action=edit&redlink=1][Maemo Leste]] is in development which is based on [[https://en.wikipedia.org/wiki/Devuan][Devuan]].
#+end_quote
