:PROPERTIES:
:ID:       9ed79822-cb4b-4983-a040-20f3e3c48d39
:ROAM_REFS: https://en.wikipedia.org/wiki/Four-velocity
:END:
#+title: (en.wikipedia.org) Four-velocity - Wikipedia
#+filetags: :mathematics:physics:website:

#+begin_quote
  In [[https://en.wikipedia.org/wiki/Physics][physics]], in particular in [[https://en.wikipedia.org/wiki/Special_relativity][special relativity]] and [[https://en.wikipedia.org/wiki/General_relativity][general relativity]], a *four-velocity* is a [[https://en.wikipedia.org/wiki/Four-vector][four-vector]] in four-dimensional [[https://en.wikipedia.org/wiki/Spacetime][spacetime]] that represents the relativistic counterpart of [[https://en.wikipedia.org/wiki/Velocity][velocity]], which is a [[https://en.wikipedia.org/wiki/Three-dimensional_space][three-dimensional]] [[https://en.wikipedia.org/wiki/Vector_(mathematics_and_physics)][vector]] in space.

  Physical [[https://en.wikipedia.org/wiki/Event_(relativity)][events]] correspond to mathematical points in time and space, the set of all of them together forming a mathematical model of physical four-dimensional spacetime.  The history of an object traces a curve in spacetime, called its [[https://en.wikipedia.org/wiki/World_line][world line]].  If the object has [[https://en.wikipedia.org/wiki/Mass_in_special_relativity][mass]], so that its speed is necessarily less than the [[https://en.wikipedia.org/wiki/Speed_of_light][speed of light]], the world line may be [[https://en.wikipedia.org/wiki/Parametrization_(geometry)][parametrized]] by the [[https://en.wikipedia.org/wiki/Proper_time][proper time]] of the object.  The four-velocity is the rate of change of [[https://en.wikipedia.org/wiki/Four-position][four-position]] with respect to the proper time along the curve.  The velocity, in contrast, is the rate of change of the position in (three-dimensional) space of the object, as seen by an observer, with respect to the observer's time.

  The value of the [[https://en.wikipedia.org/wiki/Magnitude_(mathematics)#Pseudo-Euclidean_space][magnitude]] of an object's four-velocity, i.e. the quantity obtained by applying the [[https://en.wikipedia.org/wiki/Metric_tensor_(general_relativity)][metric tensor]] /g/ to the four-velocity *U*, that is ‖*U*‖^{2} = *U* ⋅ *U* = /g/_{/μν/}/U/^{/ν/}/U/^{/μ/}, is always equal to ±/c/^{2}, where c is the speed of light.  Whether the plus or minus sign applies depends on the choice of [[https://en.wikipedia.org/wiki/Metric_signature][metric signature]].  For an object at rest its four-velocity is parallel to the direction of the time coordinate with /U/^{0} = /c/.  A four-velocity is thus the normalized future-directed timelike tangent vector to a world line, and is a [[https://en.wikipedia.org/wiki/Contravariant_vector][contravariant vector]].  Though it is a vector, addition of two four-velocities does not yield a four-velocity: the space of four-velocities is not itself a [[https://en.wikipedia.org/wiki/Vector_space][vector space]].
#+end_quote
