:PROPERTIES:
:ID:       9f49f590-90a1-4cca-9da0-d5bf922c2d3f
:ROAM_REFS: https://en.wikipedia.org/wiki/Quaternion
:END:
#+title: (en.wikipedia.org) Quaternion - Wikipedia
#+filetags: :mathematics:website:

#+begin_quote
  In [[https://en.wikipedia.org/wiki/Mathematics][mathematics]], the *quaternion* [[https://en.wikipedia.org/wiki/Number_system][number system]] extends the [[https://en.wikipedia.org/wiki/Complex_number][complex numbers]].  Quaternions were first described by the Irish mathematician [[https://en.wikipedia.org/wiki/William_Rowan_Hamilton][William Rowan Hamilton]] in 1843 and applied to [[https://en.wikipedia.org/wiki/Mechanics][mechanics]] in [[https://en.wikipedia.org/wiki/Three-dimensional_space][three-dimensional space]].  The algebra of quaternions is often denoted by *H* (for /Hamilton/), or in [[https://en.wikipedia.org/wiki/Blackboard_bold][blackboard bold]] by \(\mathbb{H}.\) Quaternions are not a [[https://en.wikipedia.org/wiki/Field_(mathematics)][field]], because multiplication of quaternions is not, in general, [[https://en.wikipedia.org/wiki/Commutative][commutative]].  Quaternions provide a definition of the quotient of two [[https://en.wikipedia.org/wiki/Vector_(mathematics_and_physics)][vectors]] in a three-dimensional space.  Quaternions are generally represented in the form

  \[a + b\,\mathbf{i} + c\,\mathbf{j} + d\,\mathbf{k},\]

  where the coefficients a, b, c, d are [[https://en.wikipedia.org/wiki/Real_number][real numbers]], and 1, *i*, *j*, *k* are the /basis vectors/ or /basis elements/.

  Quaternions are used in [[https://en.wikipedia.org/wiki/Pure_mathematics][pure mathematics]], but also have practical uses in [[https://en.wikipedia.org/wiki/Applied_mathematics][applied mathematics]], particularly for [[https://en.wikipedia.org/wiki/Quaternions_and_spatial_rotation][calculations involving three-dimensional rotations]], such as in [[https://en.wikipedia.org/wiki/3D_computer_graphics][three-dimensional computer graphics]], [[https://en.wikipedia.org/wiki/Computer_vision][computer vision]], robotics, [[https://en.wikipedia.org/wiki/Magnetic_resonance_imaging][magnetic resonance imaging]] and [[https://en.wikipedia.org/wiki/Texture_(crystalline)][crystallographic texture]] analysis.  They can be used alongside other methods of rotation, such as [[https://en.wikipedia.org/wiki/Euler_angles][Euler angles]] and [[https://en.wikipedia.org/wiki/Rotation_matrix][rotation matrices]], or as an alternative to them, depending on the application.

  In modern terms, quaternions form a four-dimensional [[https://en.wikipedia.org/wiki/Associative_algebra][associative]] [[https://en.wikipedia.org/wiki/Composition_algebra][normed]] [[https://en.wikipedia.org/wiki/Division_algebra][division algebra]] over the real numbers, and therefore a ring, also a [[https://en.wikipedia.org/wiki/Division_ring][division ring]] and a [[https://en.wikipedia.org/wiki/Domain_(ring_theory)][domain]].  It is a special case of a [[https://en.wikipedia.org/wiki/Clifford_algebra][Clifford algebra]], [[https://en.wikipedia.org/wiki/Classification_of_Clifford_algebras][classified]] as \({Cl}_{0,2}(\mathbb{R}) \cong {Cl}_{3,0}^{+}(\mathbb{R}).\) It was the first noncommutative division algebra to be discovered.

  According to the [[https://en.wikipedia.org/wiki/Frobenius_theorem_(real_division_algebras)][Frobenius theorem]], the algebra \(\mathbb{H}\) is one of only two finite-dimensional [[https://en.wikipedia.org/wiki/Division_ring][division rings]] containing a proper [[https://en.wikipedia.org/wiki/Subring][subring]] [[https://en.wikipedia.org/wiki/Isomorphism][isomorphic]] to the real numbers; the other being the complex numbers.  These rings are also [[https://en.wikipedia.org/wiki/Hurwitz's_theorem_(composition_algebras)][Euclidean Hurwitz algebras]], of which the quaternions are the largest [[https://en.wikipedia.org/wiki/Associative_algebra][associative algebra]] (and hence the largest ring).  Further extending the quaternions yields the [[https://en.wikipedia.org/wiki/Non-associative_algebra][non-associative]] [[https://en.wikipedia.org/wiki/Octonion][octonions]], which is the last [[https://en.wikipedia.org/wiki/Normed_division_algebra][normed division algebra]] over the real numbers.  The next extension gives the [[https://en.wikipedia.org/wiki/Sedenions][sedenions]], which have [[https://en.wikipedia.org/wiki/Zero_divisor][zero divisors]] and so cannot be a normed division algebra.

  The [[https://en.wikipedia.org/wiki/Unit_quaternion][unit quaternions]] give a [[https://en.wikipedia.org/wiki/Group_(mathematics)][group]] structure on the [[https://en.wikipedia.org/wiki/3-sphere][3-sphere]] S^{3} isomorphic to the groups [[https://en.wikipedia.org/wiki/Spin(3)][Spin(3)]] and [[https://en.wikipedia.org/wiki/SU(2)][SU(2)]], i.e. the [[https://en.wikipedia.org/wiki/Universal_cover][universal cover]] group of [[https://en.wikipedia.org/wiki/SO(3)][SO(3)]].  The positive and negative basis vectors form the eight-element [[https://en.wikipedia.org/wiki/Quaternion_group][quaternion group]].
#+end_quote
