:PROPERTIES:
:ID:       1dba84f0-50d9-49b3-ab99-1d7488754d75
:ROAM_REFS: https://en.wikipedia.org/wiki/Terry_A._Davis
:END:
#+title: (en.wikipedia.org) Terry A. Davis - Wikipedia
#+filetags: :website:

#+begin_quote
  *Terrence Andrew Davis* (December 15, 1969 -- August 11, 2018) was an American electrical engineer and computer programmer best known for creating and designing [[https://en.wikipedia.org/wiki/TempleOS][TempleOS]], an [[https://en.wikipedia.org/wiki/Operating_system][operating system]] in the [[https://en.wikipedia.org/wiki/Public-domain_software][public domain]], by himself.

  As a teenager, Davis learned [[https://en.wikipedia.org/wiki/Assembly_language][assembly language]] on a [[https://en.wikipedia.org/wiki/Commodore_64][Commodore 64]].  He later earned both a [[https://en.wikipedia.org/wiki/Bachelor's_degree][bachelor's degree]] in [[https://en.wikipedia.org/wiki/Computer_engineering][computer engineering]] and a [[https://en.wikipedia.org/wiki/Master's_degree][master's degree]] in [[https://en.wikipedia.org/wiki/Electrical_engineering][electrical engineering]] from [[https://en.wikipedia.org/wiki/Arizona_State_University][Arizona State University]].  He worked for several years at [[https://en.wikipedia.org/wiki/Ticketmaster][Ticketmaster]] on [[https://en.wikipedia.org/wiki/VAX][VAX]] machines.  In 1996, he began experiencing regular [[https://en.wikipedia.org/wiki/Mania][manic episodes]], one of which led him to hospitalization.  Initially diagnosed with [[https://en.wikipedia.org/wiki/Bipolar_disorder][bipolar disorder]], he was later declared to have [[https://en.wikipedia.org/wiki/Schizophrenia][schizophrenia]].  He subsequently collected disability payments and resided in [[https://en.wikipedia.org/wiki/Las_Vegas][Las Vegas]] with his parents until 2017.

  Growing up [[https://en.wikipedia.org/wiki/Catholic_Church][Catholic]], Davis was an [[https://en.wikipedia.org/wiki/Atheism][atheist]] for some of his adult life.  After experiencing a self-described "revelation", he proclaimed that he had been in direct communication with [[https://en.wikipedia.org/wiki/God][God]] and that God had commanded him to build a [[https://en.wikipedia.org/wiki/Third_Temple][successor]] to the [[https://en.wikipedia.org/wiki/Second_Temple][Second Temple]].  He then committed a decade to creating an [[https://en.wikipedia.org/wiki/Operating_system][operating system]] modeled after the [[https://en.wikipedia.org/wiki/DOS][DOS]]-based interfaces of his youth.  In 2013, Davis announced that he had completed the project, now called "TempleOS".  The operating system was generally regarded as a hobby system, not suitable for general use.

  Davis amassed an online following and regularly posted video blogs to social media.  Although he remained lucid when discussing computer-related subjects, his communication skills were significantly affected by his schizophrenia.  He was controversial for his regular use of [[https://en.wikipedia.org/wiki/Pejorative][slurs]], which he explained was his way of combating factors of [[https://en.wikipedia.org/wiki/Psychological_warfare][psychological warfare]].  After 2017, he struggled with periods of homelessness and incarceration.  His fans tried to support him by bringing him supplies, but Davis refused their offers.  On August 11, 2018, he was struck by a train and died at the age of 48.
#+end_quote
