:PROPERTIES:
:ID:       45ba6b3b-9d20-401f-a47e-468bb8104172
:ROAM_REFS: https://en.wikipedia.org/wiki/Color_space
:END:
#+title: (en.wikipedia.org) Color space - Wikipedia
#+filetags: :website:

#+begin_quote
  A *color space* is a specific organization of [[https://en.wikipedia.org/wiki/Color][colors]].  In combination with color profiling supported by various physical devices, it supports reproducible representations of color -- whether such representation entails an [[https://en.wikipedia.org/wiki/Analog_signal][analog]] or a [[https://en.wikipedia.org/wiki/Digital_data][digital]] representation.  A color space may be arbitrary, i.e. with physically realized colors assigned to a set of physical [[https://en.wikipedia.org/wiki/Palette_(computing)][color swatches]] with corresponding assigned [[https://en.wikipedia.org/wiki/Color_name][color names]] (including discrete numbers in -- for example -- the [[https://en.wikipedia.org/wiki/Pantone][Pantone]] collection), or structured with mathematical rigor (as with the [[https://en.wikipedia.org/wiki/Natural_Color_System][NCS System]], [[https://en.wikipedia.org/wiki/Adobe_RGB_color_space][Adobe RGB]] and [[https://en.wikipedia.org/wiki/SRGB][sRGB]]).  A "color space" is a useful conceptual tool for understanding the color capabilities of a particular device or digital file.  When trying to reproduce color on another device, color spaces can show whether shadow/highlight detail and color saturation can be retained, and by how much either will be compromised.

  A "[[https://en.wikipedia.org/wiki/Color_model][color model]]" is an abstract mathematical model describing the way colors can be represented as [[https://en.wikipedia.org/wiki/Tuple][tuples]] of numbers (e.g. triples in [[https://en.wikipedia.org/wiki/RGB_color_model][RGB]] or quadruples in [[https://en.wikipedia.org/wiki/CMYK_color_model][CMYK]]); however, a color model with no associated mapping function to an [[https://en.wikipedia.org/wiki/Color_space#Absolute_color_space][absolute color space]] is a more or less arbitrary color system with no connection to any globally understood system of color interpretation.  Adding a specific mapping function between a color model and a reference color space establishes within the reference color space a definite "footprint", known as a [[https://en.wikipedia.org/wiki/Gamut][gamut]], and for a given color model, this defines a color space.  For example, Adobe RGB and sRGB are two different absolute color spaces, both based on the RGB color model.  When defining a color space, the usual reference standard is the [[https://en.wikipedia.org/wiki/CIELAB][CIELAB]] or [[https://en.wikipedia.org/wiki/CIE_1931_color_space][CIEXYZ]] color spaces, which were specifically designed to encompass all colors the average human can see.

  Since "color space" identifies a particular combination of the color model and the mapping function, the word is often used informally to identify a color model.  However, even though identifying a color space automatically identifies the associated color model, this usage is incorrect in a strict sense.  For example, although several specific color spaces are based on the [[https://en.wikipedia.org/wiki/RGB_color_model][RGB color model]], there is no such thing as the singular [[https://en.wikipedia.org/wiki/RGB_color_space][RGB color space]].
#+end_quote
