:PROPERTIES:
:ID:       d4ea841b-6ba4-4975-bc84-95b08ff73143
:ROAM_REFS: https://en.wikipedia.org/wiki/Delta-sigma_modulation
:END:
#+title: (en.wikipedia.org) Delta-sigma modulation - Wikipedia
#+filetags: :electronics:signal_processing:website:

#+begin_quote
  *Delta-sigma* (*ΔΣ*; or *sigma-delta*, *ΣΔ*) modulation is an [[https://en.wikipedia.org/wiki/Oversampling][oversampling]] method for encoding [[https://en.wikipedia.org/wiki/Signals][signals]] into low [[https://en.wikipedia.org/wiki/Audio_bit_depth][bit depth]] [[https://en.wikipedia.org/wiki/Digital_signal_(signal_processing)][digital signals]] at a very high [[https://en.wikipedia.org/wiki/Sampling_frequency][sample-frequency]] as part of the process of delta-sigma [[https://en.wikipedia.org/wiki/Analog-to-digital_converter][analog-to-digital converters]] (ADCs) and [[https://en.wikipedia.org/wiki/Digital-to-analog_converter][digital-to-analog converters]] (DACs).  Delta-sigma modulation achieves high [[https://en.wikipedia.org/wiki/Audio_quality][quality]] by utilizing a [[https://en.wikipedia.org/wiki/Negative_feedback][negative feedback]] loop during quantization to the lower bit depth that continuously corrects [[https://en.wikipedia.org/wiki/Quantization_error][quantization errors]] and moves quantization noise to higher frequencies well above the original signal's [[https://en.wikipedia.org/wiki/Bandwidth_(signal_processing)][bandwidth]].  Subsequent [[https://en.wikipedia.org/wiki/Low-pass_filtering][low-pass filtering]] for [[https://en.wikipedia.org/wiki/Demodulation][demodulation]] easily removes this high frequency noise and [[https://en.wikipedia.org/wiki/Time_average][time averages]] to achieve high accuracy in amplitude, which can be ultimately encoded as [[https://en.wikipedia.org/wiki/Pulse-code_modulation][pulse-code modulation]] (PCM).

  Both ADCs and DACs can employ delta-sigma modulation.  A delta-sigma ADC (e.g. Figure 1 top) encodes an [[https://en.wikipedia.org/wiki/Analog_signal][analog signal]] using high-frequency delta-sigma modulation and then applies a [[https://en.wikipedia.org/wiki/Digital_filter][digital filter]] to demodulate it to a high-bit digital output at a lower sampling-frequency.  A delta-sigma DAC (e.g. Figure 1 bottom) encodes a high-resolution digital input signal into a lower-resolution but higher sample-frequency signal that may then be mapped to [[https://en.wikipedia.org/wiki/Voltage][voltages]] and smoothed with an analog filter for demodulation.  In both cases, the temporary use of a low bit depth signal at a higher sampling frequency simplifies circuit design and takes advantage of the efficiency and high accuracy in time of [[https://en.wikipedia.org/wiki/Digital_electronics][digital electronics]].

  Primarily because of its cost efficiency and reduced circuit complexity, this technique has found increasing use in modern electronic components such as DACs, ADCs, [[https://en.wikipedia.org/wiki/Frequency_synthesizer][frequency synthesizers]], [[https://en.wikipedia.org/wiki/Switched-mode_power_supplies][switched-mode power supplies]] and [[https://en.wikipedia.org/wiki/Motor_controller][motor controllers]].  The coarsely-quantized output of a delta-sigma ADC is occasionally used directly in signal processing or as a representation for signal storage (e.g., [[https://en.wikipedia.org/wiki/Super_Audio_CD][Super Audio CD]] stores the raw output of a 1-bit delta-sigma modulator).

  While this article focuses on [[https://en.wikipedia.org/wiki/Synchronous_circuit][synchronous]] modulation, which requires a precise clock for quantization, [[https://en.wikipedia.org/wiki/Asynchronous_circuit][asynchronous]] delta-sigma modulation instead runs without a clock.
#+end_quote
