:PROPERTIES:
:ID:       e3273a40-fd69-4940-b897-03a53e9030b6
:ROAM_REFS: https://en.wikipedia.org/wiki/M1_Abrams
:END:
#+title: (en.wikipedia.org) M1 Abrams - Wikipedia
#+filetags: :military_tanks:military_equipment:website:

#+begin_quote
  The M1 Abrams (/ˈeɪbrəmz/) is a third-generation American main battle tank designed by Chrysler Defense (now General Dynamics Land Systems) and named for General Creighton Abrams.  Conceived for modern armored ground warfare, it is one of the heaviest tanks in service at nearly 73.6 short tons (66.8 metric tons).  It introduced several modern technologies to the United States armored forces, including a multifuel turbine engine, sophisticated Chobham composite armor, a computer fire control system, separate ammunition storage in a blowout compartment, and NBC protection for crew safety.  Initial models of the M1 were armed with a 105 mm M68 gun, while later variants feature a license-produced Rheinmetall 120 mm L/44 designated M256.

  The M1 Abrams was developed from the failed joint American-West German MBT-70 project that intended to replace the dated M60 tank.  There are three main operational Abrams versions: the M1, M1A1, and M1A2, with each new iteration seeing improvements in armament, protection, and electronics.

  The Abrams was to be replaced in U.S. Army service by the XM1202 Mounted Combat System, but because that project was canceled, the Army has opted to continue maintaining and operating the M1 series for the foreseeable future by upgrading optics, armor, and firepower.

  The M1 Abrams entered service in 1980 and serves as the main battle tank of the United States Army and formerly of the U.S. Marine Corps (USMC) until the decommissioning of all USMC tank battalions in 2021.  The export modification is used by the armed forces of Egypt, Kuwait, Saudi Arabia, Australia, Poland and Iraq.  The Abrams was first used in combat by the U.S. in the Gulf War.  It was later deployed by the U.S. in the War in Afghanistan and the Iraq War, as well as by Iraq in the war against the Islamic State, Saudi Arabia in the Yemeni Civil War, and Ukraine during the Russian invasion of Ukraine.
#+end_quote
