:PROPERTIES:
:ID:       77307143-14c0-4913-9c36-6f8aac7e5f72
:ROAM_REFS: https://en.wikipedia.org/wiki/HP_Saturn
:END:
#+title: (en.wikipedia.org) HP Saturn - Wikipedia
#+filetags: :microprocessor:electronics:website:

#+begin_quote
  The *Saturn* family of [[https://en.wikipedia.org/wiki/4-bit_computing][4-bit]] ([[https://en.wikipedia.org/wiki/Datapath][datapath]]) [[https://en.wikipedia.org/wiki/Microprocessor][microprocessors]] was developed by [[https://en.wikipedia.org/wiki/Hewlett-Packard][Hewlett-Packard]] in the 1980s first for the [[https://en.wikipedia.org/wiki/HP-71B][HP-71B]] handheld computer, released in 1984, and later for various HP calculators (starting with the [[https://en.wikipedia.org/wiki/HP-18C][HP-18C]]).  It succeeded the /[[https://en.wikipedia.org/w/index.php?title=HP_Nut&action=edit&redlink=1][Nut]]/ family of processors used in earlier calculators.  The HP48SX and HP48S were the last models to use HP manufactured Saturn processors, later models used processors manufactured by [[https://en.wikipedia.org/wiki/NEC][NEC]].  The [[https://en.wikipedia.org/wiki/HP_49_series][HP 49 series]] initially used the Saturn CPU until the NEC fab could no longer manufacture the processor for technical reasons in 2003.  Starting with the [[https://en.wikipedia.org/wiki/HP_49g+][HP 49g+]] model in 2003, the calculators switched to a [[https://en.wikipedia.org/wiki/Samsung][Samsung]] [[https://en.wikipedia.org/wiki/Samsung_S3C2410][S3C2410]] processor with an [[https://en.wikipedia.org/wiki/ARM920T][ARM920T]] core (part of the [[https://en.wikipedia.org/wiki/ARMv4T][ARMv4T]] architecture) which ran an emulator of the Saturn hardware in software.  In 2000, the [[https://en.wikipedia.org/wiki/HP_39G][HP 39G]] and [[https://en.wikipedia.org/wiki/HP_40G][HP 40G]] were the last calculators introduced based on the actual NEC fabricated Saturn hardware.  The last calculators introduced to use the Saturn emulator were the [[https://en.wikipedia.org/wiki/HP_39gs][HP 39gs]], [[https://en.wikipedia.org/wiki/HP_40gs][HP 40gs]] and [[https://en.wikipedia.org/wiki/HP_50g][HP 50g]] in 2006, as well as the 2007 revision of the [[https://en.wikipedia.org/wiki/Hp_48gII][hp 48gII]].  The HP 50g was the last calculator sold by HP using this emulator when it was discontinued in 2015 due to Samsung stopping production of the ARM processor on which it was based.
#+end_quote
* See Also
** [[id:91062197-4b54-418f-8eef-dd56c3432c55][HP 50g Calculator]]
