:PROPERTIES:
:ID:       a17c4195-8144-4b01-9757-0733e1944e96
:ROAM_REFS: https://en.wikipedia.org/wiki/To_Mock_a_Mockingbird
:END:
#+title: (en.wikipedia.org) To Mock a Mockingbird - Wikipedia
#+filetags: :mathematics:puzzles_and_challenges:books:website:

#+begin_quote
  /*To Mock a Mockingbird and Other Logic Puzzles: Including an Amazing Adventure in Combinatory Logic*/ (1985, [[https://en.wikipedia.org/wiki/ISBN_(identifier)][ISBN]] [[https://en.wikipedia.org/wiki/Special:BookSources/0-19-280142-2][0-19-280142-2]]) is a book by the [[https://en.wikipedia.org/wiki/Mathematician][mathematician]] and [[https://en.wikipedia.org/wiki/Logician][logician]] [[https://en.wikipedia.org/wiki/Raymond_Smullyan][Raymond Smullyan]].  It contains many nontrivial recreational puzzles of the sort for which Smullyan is well known.  It is also a gentle and humorous introduction to [[https://en.wikipedia.org/wiki/Combinatory_logic][combinatory logic]] and the associated [[https://en.wikipedia.org/wiki/Metamathematics][metamathematics]], built on an elaborate [[https://en.wikipedia.org/wiki/Ornithological][ornithological]] [[https://en.wikipedia.org/wiki/Metaphor][metaphor]].

  Combinatory logic, functionally equivalent to the [[https://en.wikipedia.org/wiki/Lambda_calculus][lambda calculus]], is a branch of [[https://en.wikipedia.org/wiki/Symbolic_logic][symbolic logic]] having the expressive power of [[https://en.wikipedia.org/wiki/Set_theory][set theory]], and with deep connections to questions of [[https://en.wikipedia.org/wiki/Computability_theory_(computation)][computability]] and [[https://en.wikipedia.org/wiki/Provability_logic][provability]].  Smullyan's exposition takes the form of an imaginary account of two men going into a forest and discussing the unusual "birds" (combinators) they find there (bird watching was a hobby of one of the founders of combinatory logic, [[https://en.wikipedia.org/wiki/Haskell_Curry][Haskell Curry]], and another founder [[https://en.wikipedia.org/wiki/Moses_Schönfinkel][Moses Schönfinkel's]] name means /beautiful spark/ (or possibly /beautiful little-finch/). Each species of bird in Smullyan's forest stands for a particular kind of [[https://en.wikipedia.org/wiki/Combinator][combinator]] appearing in the conventional treatment of combinatory logic.  Each bird has a distinctive call, which it emits when it hears the call of another bird.  Hence an initial call by certain "birds" gives rise to a cascading sequence of calls by a succession of birds.

  Deep inside the forest dwells the Mockingbird, which imitates other birds hearing themselves.  The resulting cascade of calls and responses analogizes to abstract [[https://en.wikipedia.org/wiki/Model_of_computation][models of computing]].  With this analogy in hand, one can explore advanced topics in the mathematical [[https://en.wikipedia.org/wiki/Theory_of_computability][theory of computability]], such as [[https://en.wikipedia.org/wiki/Church–Turing_thesis][Church–Turing computability]] and [[https://en.wikipedia.org/wiki/Gödel's_incompleteness_theorems][Gödel's theorem]].

  While the book starts off with simple riddles, it eventually shifts to a tale of Inspector Craig of Scotland Yard, who appears in Smullyan's other books; traveling from forest to forest, learning from different professors about all the different kinds of birds.  He starts off in a certain enchanted forest, then goes to an unnamed forest, then to Curry's Forest (named after Haskell Curry), then to Russell's Forest, then to The Forest Without a Name, then to Gödel's Forest and finally to The Master Forest where he also answers The Grand Question.
#+end_quote
