:PROPERTIES:
:ID:       bfff5e26-b146-4e6e-8fd2-8befdec1fabf
:ROAM_REFS: https://en.wikipedia.org/wiki/LoRa
:END:
#+title: (en.wikipedia.org) LoRa - Wikipedia
#+filetags: :digital_radio:radio:website:

#+begin_quote
  LoRa (from "long range") is a physical proprietary radio communication technique.  It is based on spread spectrum modulation techniques derived from chirp spread spectrum (CSS) technology.  It was developed by Cycleo, a company of Grenoble, France, and patented in 2014.  Cycleo was later acquired by Semtech.
  LoRaWAN (wide area network) defines the communication protocol and system architecture.  LoRaWAN is an official standard of the International Telecommunication Union (ITU), ITU-T Y.4480.  The continued development of the LoRaWAN protocol is managed by the open, non-profit LoRa Alliance, of which Semtech is a founding member.
  Together, LoRa and LoRaWAN define a low-power, wide-area (LPWA) networking protocol designed to wirelessly connect battery operated devices to the Internet in regional, national or global networks, and targets key Internet of things (IoT) requirements, such as bi-directional communication, end-to-end security, mobility and localization services.  The low power, low bit rate, and IoT use distinguish this type of network from a wireless WAN that is designed to connect users or businesses, and carry more data, using more power.  The LoRaWAN data rate ranges from 0.3 kbit/s to 50 kbit/s per channel.
#+end_quote
