:PROPERTIES:
:ID:       a7261a30-e151-4a38-831c-3b65470b32b6
:ROAM_REFS: https://en.wikipedia.org/wiki/Funarg_problem
:END:
#+title: (en.wikipedia.org) Funarg problem - Wikipedia
#+filetags: :website:

#+begin_quote
  In [[https://en.wikipedia.org/wiki/Computer_science][computer science]], the *funarg problem* /(function argument problem)/ refers to the difficulty in implementing [[https://en.wikipedia.org/wiki/First-class_function][first-class functions]] ([[https://en.wikipedia.org/wiki/Function_(programming)][functions]] as [[https://en.wikipedia.org/wiki/First-class_object][first-class objects]]) in programming language implementations so as to use [[https://en.wikipedia.org/wiki/Stack-based_memory_allocation][stack-based memory allocation]] of the functions.

  The difficulty only arises if the body of a [[https://en.wikipedia.org/wiki/Nested_function][nested function]] refers directly (i.e., not by argument passing) to identifiers defined in the environment in which the function is defined, but not in the environment of the function call.  A standard resolution is either to forbid such references or to create [[https://en.wikipedia.org/wiki/Closure_(computer_science)][closures]].

  There are two subtly different versions of the funarg problem.  The *upwards funarg problem* arises from returning (or otherwise transmitting "upwards") a function from a function call.  The *downwards funarg problem* arises from passing a function as a parameter to another function call.
#+end_quote
