:PROPERTIES:
:ID:       f75f3e17-259d-43d8-bc7f-f32fdf126b00
:ROAM_REFS: https://en.wikipedia.org/wiki/Wave_function
:END:
#+title: (en.wikipedia.org) Wave function - Wikipedia
#+filetags: :quantum_mechanics:physics:website:

#+begin_quote
  In [[https://en.wikipedia.org/wiki/Quantum_physics][quantum physics]], a *wave function* (or *wavefunction*) is a mathematical description of the [[https://en.wikipedia.org/wiki/Quantum_state][quantum state]] of an isolated [[https://en.wikipedia.org/wiki/Quantum_system][quantum system]].  The most common symbols for a wave function are the Greek letters /ψ/ and Ψ (lower-case and capital [[https://en.wikipedia.org/wiki/Psi_(letter)][psi]], respectively).  Wave functions are [[https://en.wikipedia.org/wiki/Complex_number][complex-valued]].  For example, a wave function might assign a complex number to each point in a region of space.  The [[https://en.wikipedia.org/wiki/Born_rule][Born rule]] provides the means to turn these complex [[https://en.wikipedia.org/wiki/Probability_amplitude][probability amplitudes]] into actual probabilities.  In one common form, it says that the [[https://en.wikipedia.org/wiki/Squared_modulus][squared modulus]] of a wave function that depends upon position is the [[https://en.wikipedia.org/wiki/Probability_density_function][probability density]] of [[https://en.wikipedia.org/wiki/Measurement_in_quantum_mechanics][measuring]] a particle as being at a given place.  The integral of a wavefunction's squared modulus over all the system's degrees of freedom must be equal to 1, a condition called /normalization/.  Since the wave function is complex-valued, only its relative phase and relative magnitude can be measured; its value does not, in isolation, tell anything about the magnitudes or directions of measurable observables.  One has to apply [[https://en.wikipedia.org/wiki/Operator_(quantum_mechanics)][quantum operators]], whose eigenvalues correspond to sets of possible results of measurements, to the wave function /ψ/ and calculate the statistical distributions for measurable quantities.

  Wave functions can be [[https://en.wikipedia.org/wiki/Function_(mathematics)][functions]] of variables other than position, such as [[https://en.wikipedia.org/wiki/Momentum][momentum]].  The information represented by a wave function that is dependent upon position can be converted into a wave function dependent upon momentum and vice versa, by means of a [[https://en.wikipedia.org/wiki/Fourier_transform][Fourier transform]].  Some particles, like [[https://en.wikipedia.org/wiki/Electron][electrons]] and [[https://en.wikipedia.org/wiki/Photon][photons]], have nonzero [[https://en.wikipedia.org/wiki/Spin_(physics)][spin]], and the wave function for such particles includes spin as an intrinsic, discrete degree of freedom; other discrete variables can also be included, such as [[https://en.wikipedia.org/wiki/Isospin][isospin]].  When a system has internal degrees of freedom, the wave function at each point in the continuous degrees of freedom (e.g., a point in space) assigns a complex number for /each/ possible value of the discrete degrees of freedom (e.g., z-component of spin).  These values are often displayed in a [[https://en.wikipedia.org/wiki/Column_matrix][column matrix]] (e.g., a 2 × 1 column vector for a non-relativistic electron with spin 1⁄2).

  According to the [[https://en.wikipedia.org/wiki/Superposition_principle][superposition principle]] of quantum mechanics, wave functions can be added together and multiplied by complex numbers to form new wave functions and form a [[https://en.wikipedia.org/wiki/Hilbert_space][Hilbert space]].  The inner product of two wave functions is a measure of the overlap between the corresponding physical states and is used in the foundational probabilistic interpretation of quantum mechanics, the [[https://en.wikipedia.org/wiki/Born_rule][Born rule]], relating transition probabilities to inner products.  The [[https://en.wikipedia.org/wiki/Schrödinger_equation][Schrödinger equation]] determines how wave functions evolve over time, and a wave function behaves qualitatively like other [[https://en.wikipedia.org/wiki/Wave][waves]], such as [[https://en.wikipedia.org/wiki/Water_wave][water waves]] or waves on a string, because the Schrödinger equation is mathematically a type of [[https://en.wikipedia.org/wiki/Wave_equation][wave equation]].  This explains the name "wave function", and gives rise to [[https://en.wikipedia.org/wiki/Wave–particle_duality][wave--particle duality]].  However, the wave function in quantum mechanics describes a kind of physical phenomenon, as of 2023 still open to different [[https://en.wikipedia.org/wiki/Interpretations_of_quantum_mechanics][interpretations]], which fundamentally differs from that of [[https://en.wikipedia.org/wiki/Classic_mechanical][classic mechanical]] waves.
#+end_quote
