:PROPERTIES:
:ID:       c272710d-aaa1-43b4-b34e-24aa9572a8d2
:ROAM_REFS: https://en.wikipedia.org/wiki/Size-change_termination_principle
:END:
#+title: (en.wikipedia.org) Size-change termination principle - Wikipedia
#+filetags: :mathematics:static_analysis:computer_science:website:

#+begin_quote
  The *size-change termination principle (SCT)* guarantees [[https://en.wikipedia.org/wiki/Termination_analysis][termination]] for a [[https://en.wikipedia.org/wiki/Program_(machine)][computer program]] by proving that infinite computations always trigger infinite descent in data values that are well-founded.  Size-change termination analysis utilizes this principle in order to solve the [[https://en.wikipedia.org/wiki/Halting_problem#Halting_on_all_inputs][universal halting problem]] for a certain class of programs.  When applied to general programs, the principle is intended to be used conservatively, which means that if the analysis determines that a program is terminating, the answer is sound, but a negative answer means "don't know".  The [[https://en.wikipedia.org/wiki/Decision_problem][decision problem]] for SCT is [[https://en.wikipedia.org/wiki/PSPACE-complete][PSPACE-complete]]; however, there exists an algorithm that computes an approximation of the decision problem in polynomial time.  Size-change analysis is applicable to both first-order and higher-order functional programs, as well as imperative programs and logic programs.  The latter application preceded by four years the general formulation of the principle by Lee et al.
#+end_quote
