:PROPERTIES:
:ID:       82c9cfe8-eb0d-4340-8592-373c3581c0dd
:ROAM_REFS: https://en.wikipedia.org/wiki/Lie_algebra
:END:
#+title: (en.wikipedia.org) Lie algebra - Wikipedia
#+filetags: :mathematics:website:

#+begin_quote
  In [[https://en.wikipedia.org/wiki/Mathematics][mathematics]], a *Lie algebra* (pronounced [[https://en.wikipedia.org/wiki/Help:IPA/English][/liː/]] [[https://en.wikipedia.org/wiki/Help:Pronunciation_respelling_key][/LEE/]]) is a [[https://en.wikipedia.org/wiki/Vector_space][vector space]] \(\mathfrak{g}\) together with an operation called the *Lie bracket*, an [[https://en.wikipedia.org/wiki/Alternating_multilinear_map][alternating bilinear map]] \(\mathfrak{g} \times \mathfrak{g}\rightarrow\mathfrak{g}\), that satisfies the [[https://en.wikipedia.org/wiki/Jacobi_identity][Jacobi identity]].  In other words, a Lie algebra is an [[https://en.wikipedia.org/wiki/Algebra_over_a_field][algebra over a field]] for which the multiplication operation (called the Lie bracket) is alternating and satisfies the Jacobi identity.  The Lie bracket of two vectors \(x\) and \(y\) is denoted \(\lbrack x,y\rbrack\).  A Lie algebra is typically a [[https://en.wikipedia.org/wiki/Non-associative_algebra][non-associative algebra]].  However, every [[https://en.wikipedia.org/wiki/Associative_algebra][associative algebra]] gives rise to a Lie algebra, consisting of the same vector space with the [[https://en.wikipedia.org/wiki/Commutator][commutator]] Lie bracket, \(\lbrack x,y\rbrack = xy - yx\).

  Lie algebras are closely related to [[https://en.wikipedia.org/wiki/Lie_group][Lie groups]], which are [[https://en.wikipedia.org/wiki/Group_(mathematics)][groups]] that are also [[https://en.wikipedia.org/wiki/Smooth_manifolds][smooth manifolds]]: every Lie group gives rise to a Lie algebra, which is the [[https://en.wikipedia.org/wiki/Tangent_space][tangent space]] at the identity. (In this case, the Lie bracket measures the failure of [[https://en.wikipedia.org/wiki/Commutativity][commutativity]] for the Lie group.) Conversely, to any finite-dimensional Lie algebra over the [[https://en.wikipedia.org/wiki/Real_number][real]] or [[https://en.wikipedia.org/wiki/Complex_number][complex numbers]], there is a corresponding [[https://en.wikipedia.org/wiki/Connected_space][connected]] Lie group, unique up to [[https://en.wikipedia.org/wiki/Covering_space][covering spaces]] ([[https://en.wikipedia.org/wiki/Lie's_third_theorem][Lie's third theorem]]).  This [[https://en.wikipedia.org/wiki/Lie_group–Lie_algebra_correspondence][correspondence]] allows one to study the structure and [[https://en.wikipedia.org/wiki/List_of_simple_Lie_groups][classification]] of Lie groups in terms of Lie algebras, which are simpler objects of linear algebra.

  In more detail: for any Lie group, the multiplication operation near the identity element 1 is commutative to first order.  In other words, every Lie group /G/ is (to first order) approximately a real vector space, namely the tangent space \(\mathfrak{g}\) to /G/ at the identity.  To second order, the group operation may be non-commutative, and the second-order terms describing the non-commutativity of /G/ near the identity give \(\mathfrak{g}\) the structure of a Lie algebra.  It is a remarkable fact that these second-order terms (the Lie algebra) completely determine the group structure of /G/ near the identity.  They even determine /G/ globally, up to covering spaces.

  In physics, Lie groups appear as symmetry groups of physical systems, and their Lie algebras (tangent vectors near the identity) may be thought of as infinitesimal symmetry motions.  Thus Lie algebras and their representations are used extensively in physics, notably in [[https://en.wikipedia.org/wiki/Quantum_mechanics][quantum mechanics]] and particle physics.

  An elementary example (not directly coming from an associative algebra) is the 3-dimensional space \(\mathfrak{g} = \mathbb{R}^{3}\) with Lie bracket defined by the [[https://en.wikipedia.org/wiki/Cross_product][cross product]] \(\lbrack x,y\rbrack = x \times y.\) This is skew-symmetric since \(x \times y = - y \times x\), and instead of associativity it satisfies the Jacobi identity:

  \(x \times (y \times z) + y \times (z \times x) + z \times (x \times y) = 0.\)

  This is the Lie algebra of the Lie group of [[https://en.wikipedia.org/wiki/3D_rotation_group][rotations of space]], and each vector \(v \in \mathbb{R}^{3}\) may be pictured as an infinitesimal rotation around the axis \(v\), with angular speed equal to the magnitude of \(v\).  The Lie bracket is a measure of the non-commutativity between two rotations.  Since a rotation commutes with itself, one has the alternating property \(\lbrack x,x\rbrack = x \times x = 0\).
#+end_quote
