:PROPERTIES:
:ID:       3d59c659-e749-4ff2-96bb-ab2690446068
:ROAM_REFS: https://en.wikipedia.org/wiki/Btrfs
:END:
#+title: (en.wikipedia.org) Btrfs - Wikipedia
#+filetags: :filesystems:website:

#+begin_quote
  Btrfs (pronounced as "better F S", "butter F S", "b-tree F S", or B.T.R.F.S.) is a computer storage format that combines a file system based on the copy-on-write (COW) principle with a logical volume manager (distinct from Linux's LVM), developed together.  It was created by Chris Mason in 2007 for use in Linux, and since November 2013, the file system's on-disk format has been declared stable in the Linux kernel.
  Btrfs is intended to address the lack of pooling, snapshots, checksums, and integral multi-device spanning in Linux file systems.  Mason, the principal Btrfs author, stated that its goal was "to let [Linux] scale for the storage that will be available.  Scaling is not just about addressing the storage but also means being able to administer and to manage it with a clean interface that lets people see what's being used and makes it more reliable".
#+end_quote
