:PROPERTIES:
:ID:       82fb19d5-4914-4ed3-9b21-24a2126987b7
:ROAM_REFS: https://en.wikipedia.org/wiki/Riemann_hypothesis
:END:
#+title: (en.wikipedia.org) Riemann hypothesis - Wikipedia
#+filetags: :mathematics:website:

#+begin_quote
  In mathematics, the Riemann hypothesis is the conjecture that the Riemann zeta function has its zeros only at the negative even integers and complex numbers with real part ⁠1/2⁠.  Many consider it to be the most important unsolved problem in pure mathematics.  It is of great interest in number theory because it implies results about the distribution of prime numbers.  It was proposed by Bernhard Riemann (1859), after whom it is named.
  The Riemann hypothesis and some of its generalizations, along with Goldbach's conjecture and the twin prime conjecture, make up Hilbert's eighth problem in David Hilbert's list of twenty-three unsolved problems; it is also one of the Millennium Prize Problems of the Clay Mathematics Institute, which offers US$1 million for a solution to any of them.  The name is also used for some closely related analogues, such as the Riemann hypothesis for curves over finite fields.
  The Riemann zeta function ζ(s) is a function whose argument s may be any complex number other than 1, and whose values are also complex.  It has zeros at the negative even integers; that is, ζ(s) = 0 when s is one of −2, −4, −6, ….  These are called its trivial zeros.  The zeta function is also zero for other values of s, which are called nontrivial zeros.  The Riemann hypothesis is concerned with the locations of these nontrivial zeros, and states that:
    The real part of every nontrivial zero of the Riemann zeta function is ⁠1/2⁠.
  Thus, if the hypothesis is correct, all the nontrivial zeros lie on the critical line consisting of the complex numbers ⁠1/2⁠ + i t, where t is a real number and i is the imaginary unit.
#+end_quote
* See Also
** [[id:2f4f8294-ca71-41da-8f45-c621a8527b38][Riemann zeta function - Wikipedia]]
