:PROPERTIES:
:ID:       e63d67d7-3b70-4685-9eb7-be151bba8f7d
:ROAM_REFS: https://en.wikipedia.org/wiki/Dialectic
:END:
#+title: (en.wikipedia.org) Dialectic - Wikipedia
#+filetags: :logic:philosophy:website:

#+begin_quote
  Dialectic (Ancient Greek: διαλεκτική, dialektikḗ; German: Dialektik), also known as the dialectical method, refers originally to dialogue between people holding different points of view about a subject but wishing to arrive at the truth through reasoned argumentation.  Dialectic resembles debate, but the concept excludes subjective elements such as emotional appeal and rhetoric.  It has its origins in ancient philosophy and continued to be developed in the Middle Ages.
  Hegelianism refigured "dialectic" to no longer refer to a literal dialogue.  Instead, the term takes on the specialized meaning of development by way of overcoming internal contradictions.  Dialectical materialism, a theory advanced by Karl Marx and Friedrich Engels, adapted the Hegelian dialectic into a materialist theory of history.  The legacy of Hegelian and Marxian dialectics has been criticized by philosophers, such as Karl Popper and Mario Bunge, who considered it unscientific.
  Dialectic implies a developmental process and so does not fit naturally within classical logic.  Nevertheless, some twentieth-century logicians have attempted to formalize it.  In the field of education, the dialectic approach may be contrasted with the didactic method.
#+end_quote
* (en.wikipedia.org) Hegelian Dialectic - Modern Philosophy - Dialectic - Wikipedia
:PROPERTIES:
:ID:       bdacde14-f5f3-470a-aafa-e6ec828a0979
:ROAM_REFS: https://en.wikipedia.org/wiki/Dialectic#Hegelian_dialectic
:END:
#+begin_quote
  The Hegelian dialectic describes changes in the forms of thought through their own internal contradictions into concrete forms that overcome previous oppositions.
  This dialectic is sometimes presented in a threefold manner, as first stated by Heinrich Moritz Chalybäus, as comprising three dialectical stages of development: a thesis, giving rise to its reaction; an antithesis, which contradicts or negates the thesis; and the tension between the two being resolved by means of a synthesis. Although, Hegel opposed these terms.
  By contrast, the terms abstract, negative, and concrete suggest a flaw or an incompleteness in any initial thesis.  For Hegel, the concrete must always pass through the phase of the negative, that is, mediation.  This is the essence of what is popularly called Hegelian dialectics.
  To describe the activity of overcoming the negative, Hegel often used the term Aufhebung, variously translated into English as "sublation" or "overcoming", to conceive of the working of the dialectic.  Roughly, the term indicates preserving the true portion of an idea, thing, society, and so forth, while moving beyond its limitations.  What is sublated, on the one hand, is overcome, but, on the other hand, is preserved and maintained.
  As in the Socratic dialectic, Hegel claimed to proceed by making implicit contradictions explicit: each stage of the process is the product of contradictions inherent or implicit in the preceding stage.  On his view, the purpose of dialectics is "to study things in their own being and movement and thus to demonstrate the finitude of the partial categories of understanding".
  For Hegel, even history can be reconstructed as a unified dialectic, the major stages of which chart a progression from self-alienation as servitude to self-unification and realization as the rational constitutional state of free and equal citizens.
#+end_quote
