:PROPERTIES:
:ID:       aa79adc9-3e6a-4056-9bd8-6fe00a1ccf12
:ROAM_REFS: https://en.wikipedia.org/wiki/Extended_Euclidean_algorithm
:END:
#+title: (en.wikipedia.org) Extended Euclidean algorithm - Wikipedia
#+filetags: :algorithms:computer_science:mathematics:website:

#+begin_quote
  In [[https://en.wikipedia.org/wiki/Arithmetic][arithmetic]] and [[https://en.wikipedia.org/wiki/Computer_programming][computer programming]], the *extended Euclidean algorithm* is an extension to the [[https://en.wikipedia.org/wiki/Euclidean_algorithm][Euclidean algorithm]], and computes, in addition to the [[https://en.wikipedia.org/wiki/Greatest_common_divisor][greatest common divisor]] (gcd) of integers /a/ and /b/, also the coefficients of [[https://en.wikipedia.org/wiki/Bézout's_identity][Bézout's identity]], which are integers /x/ and /y/ such that

  \(ax + by = \gcd(a,b).\)

  This is a [[https://en.wikipedia.org/wiki/Certifying_algorithm][certifying algorithm]], because the gcd is the only number that can simultaneously satisfy this equation and divide the inputs.  It allows one to compute also, with almost no extra cost, the quotients of /a/ and /b/ by their greatest common divisor.

  /Extended Euclidean algorithm/ also refers to a [[https://en.wikipedia.org/wiki/Polynomial_greatest_common_divisor#Bézout's_identity_and_extended_GCD_algorithm][very similar algorithm]] for computing the [[https://en.wikipedia.org/wiki/Polynomial_greatest_common_divisor][polynomial greatest common divisor]] and the coefficients of Bézout's identity of two [[https://en.wikipedia.org/wiki/Univariate_polynomial][univariate polynomials]].

  The extended Euclidean algorithm is particularly useful when /a/ and /b/ are [[https://en.wikipedia.org/wiki/Coprime][coprime]].  With that provision, /x/ is the [[https://en.wikipedia.org/wiki/Modular_multiplicative_inverse][modular multiplicative inverse]] of /a/ [[https://en.wikipedia.org/wiki/Modular_arithmetic][modulo]] /b/, and /y/ is the modular multiplicative inverse of /b/ modulo /a/.  Similarly, the polynomial extended Euclidean algorithm allows one to compute the [[https://en.wikipedia.org/wiki/Multiplicative_inverse][multiplicative inverse]] in [[https://en.wikipedia.org/wiki/Algebraic_field_extension][algebraic field extensions]] and, in particular in [[https://en.wikipedia.org/wiki/Finite_field][finite fields]] of non prime order.  It follows that both extended Euclidean algorithms are widely used in [[https://en.wikipedia.org/wiki/Cryptography][cryptography]].  In particular, the computation of the [[https://en.wikipedia.org/wiki/Modular_multiplicative_inverse][modular multiplicative inverse]] is an essential step in the derivation of key-pairs in the [[https://en.wikipedia.org/wiki/RSA_(algorithm)][RSA]] public-key encryption method.
#+end_quote
