:PROPERTIES:
:ID:       a592fdab-5b43-4124-87f9-09367184c691
:ROAM_REFS: https://en.wikipedia.org/wiki/Zermelo–Fraenkel_set_theory
:END:
#+title: (en.wikipedia.org) Zermelo–Fraenkel set theory - Wikipedia
#+filetags: :website:

#+begin_quote
  In [[https://en.wikipedia.org/wiki/Set_theory][set theory]], *Zermelo--Fraenkel set theory*, named after mathematicians [[https://en.wikipedia.org/wiki/Ernst_Zermelo][Ernst Zermelo]] and [[https://en.wikipedia.org/wiki/Abraham_Fraenkel][Abraham Fraenkel]], is an [[https://en.wikipedia.org/wiki/Axiomatic_system][axiomatic system]] that was proposed in the early twentieth century in order to formulate a [[https://en.wikipedia.org/wiki/Theory_of_sets][theory of sets]] free of paradoxes such as [[https://en.wikipedia.org/wiki/Russell's_paradox][Russell's paradox]].  Today, Zermelo--Fraenkel set theory, with the historically controversial [[https://en.wikipedia.org/wiki/Axiom_of_choice][axiom of choice]] (AC) included, is the standard form of [[https://en.wikipedia.org/wiki/Axiomatic_set_theory][axiomatic set theory]] and as such is the most common [[https://en.wikipedia.org/wiki/Foundations_of_mathematics][foundation of mathematics]].  Zermelo--Fraenkel set theory with the axiom of choice included is abbreviated *ZFC*, where C stands for "choice", and *ZF* refers to the axioms of Zermelo--Fraenkel set theory with the axiom of choice excluded.

  Informally, Zermelo--Fraenkel set theory is intended to formalize a single primitive notion, that of a [[https://en.wikipedia.org/wiki/Hereditary_set][hereditary]] [[https://en.wikipedia.org/wiki/Well-founded][well-founded]] [[https://en.wikipedia.org/wiki/Set_(mathematics)][set]], so that all [[https://en.wiktionary.org/wiki/entity][entities]] in the [[https://en.wikipedia.org/wiki/Universe_of_discourse][universe of discourse]] are such sets.  Thus the [[https://en.wikipedia.org/wiki/Axiom][axioms]] of Zermelo--Fraenkel set theory refer only to [[https://en.wikipedia.org/wiki/Pure_set][pure sets]] and prevent its [[https://en.wikipedia.org/wiki/Model_theory][models]] from containing [[https://en.wikipedia.org/wiki/Urelement][urelements]] (elements that are not themselves sets).  Furthermore, [[https://en.wikipedia.org/wiki/Proper_class][proper classes]] (collections of [[https://en.wikipedia.org/wiki/Mathematical_object][mathematical objects]] defined by a property shared by their members where the collections are too big to be sets) can only be treated indirectly.  Specifically, Zermelo--Fraenkel set theory does not allow for the existence of a [[https://en.wikipedia.org/wiki/Universal_set][universal set]] (a set containing all sets) nor for [[https://en.wikipedia.org/wiki/Unrestricted_comprehension][unrestricted comprehension]], thereby avoiding Russell's paradox.  [[https://en.wikipedia.org/wiki/Von_Neumann–Bernays–Gödel_set_theory][Von Neumann--Bernays--Gödel set theory]] (NBG) is a commonly used [[https://en.wikipedia.org/wiki/Conservative_extension][conservative extension]] of Zermelo--Fraenkel set theory that does allow explicit treatment of proper classes.

  There are many equivalent formulations of the axioms of Zermelo--Fraenkel set theory.  Most of the axioms state the existence of particular sets defined from other sets.  For example, the [[https://en.wikipedia.org/wiki/Axiom_of_pairing][axiom of pairing]] implies that given any two sets \(a\) and \(b\) there is a new set \(\{ a,b\}\) containing exactly \(a\) and \(b\).  Other axioms describe properties of set membership.  A goal of the axioms is that each axiom should be true if interpreted as a statement about the collection of all sets in the [[https://en.wikipedia.org/wiki/Von_Neumann_universe][von Neumann universe]] (also known as the cumulative hierarchy).

  The [[https://en.wikipedia.org/wiki/Metamathematics][metamathematics]] of Zermelo--Fraenkel set theory has been extensively studied.  Landmark results in this area established the [[https://en.wikipedia.org/wiki/Independence_(mathematical_logic)][logical independence]] of the axiom of choice from the remaining Zermelo-Fraenkel axioms and of the [[https://en.wikipedia.org/wiki/Continuum_hypothesis][continuum hypothesis]] from ZFC.  The [[https://en.wikipedia.org/wiki/Consistency][consistency]] of a theory such as ZFC cannot be proved within the theory itself, as shown by [[https://en.wikipedia.org/wiki/Gödel's_second_incompleteness_theorem][Gödel's second incompleteness theorem]].
#+end_quote
