:PROPERTIES:
:ID:       5c7b57e8-9ed4-4cf9-bb2a-70b20b2a1418
:ROAM_REFS: https://en.wikipedia.org/wiki/Nokia_N900
:END:
#+title: (en.wikipedia.org) Nokia N900 - Wikipedia
#+filetags: :electronics:website:

#+begin_quote
  The *Nokia N900* is a [[https://en.wikipedia.org/wiki/Smartphone][smartphone]] made by [[https://en.wikipedia.org/wiki/Nokia][Nokia]], launched at [[https://en.wikipedia.org/wiki/Nokia_World][Nokia World]] on 2 September 2009 and released in November.  Superseding the [[https://en.wikipedia.org/wiki/Nokia_N810][Nokia N810]], the N900's default [[https://en.wikipedia.org/wiki/Operating_system][operating system]], [[https://en.wikipedia.org/wiki/Maemo][Maemo]] 5, is a [[https://en.wikipedia.org/wiki/Linux][Linux]]-based OS originally developed for the [[https://en.wikipedia.org/wiki/Nokia_770_Internet_Tablet][Nokia 770 Internet Tablet]].  It is the first Nokia device based upon the [[https://en.wikipedia.org/wiki/Texas_Instruments_OMAP#OMAP_3][Texas Instruments OMAP3]] [[https://en.wikipedia.org/wiki/Microprocessor][microprocessor]] with the [[https://en.wikipedia.org/wiki/ARM_Cortex-A8][ARM Cortex-A8]] core.  Unlike the three Nokia Internet tablets preceding it, the Nokia N900 is the first Maemo device to include [[https://en.wikipedia.org/wiki/Cellular_network][telephony]] functionality ([[https://en.wikipedia.org/wiki/Quad-band][quad-band]] [[https://en.wikipedia.org/wiki/GSM][GSM]] and [[https://en.wikipedia.org/wiki/3G][3G]] [[https://en.wikipedia.org/wiki/UMTS][UMTS]]/[[https://en.wikipedia.org/wiki/HSDPA][HSDPA]]).

  The N900 functions as a [[https://en.wikipedia.org/wiki/Mobile_Internet_device][mobile Internet device]], and includes [[https://en.wikipedia.org/wiki/Email][email]], [[https://en.wikipedia.org/wiki/Web_browsing][web browsing]] and access to online services, a 5-[[https://en.wikipedia.org/wiki/Megapixel][megapixel]] [[https://en.wikipedia.org/wiki/Digital_camera][digital camera]] for still or video photography, a [[https://en.wikipedia.org/wiki/Portable_media_player][portable media player]] for music and video, [[https://en.wikipedia.org/wiki/Calculator][calculator]], [[https://en.wikipedia.org/wiki/Games_console][games console]] and [[https://en.wikipedia.org/wiki/Word_processor][word processor]], [[https://en.wikipedia.org/wiki/SMS][SMS]], as well as [[https://en.wikipedia.org/wiki/Mobile_telephony][mobile telephony]] using either a [[https://en.wikipedia.org/wiki/Mobile_network][mobile network]] or [[https://en.wikipedia.org/wiki/VoIP][VoIP]] via Internet (mobile or [[https://en.wikipedia.org/wiki/Wi-Fi][Wi-Fi]]).  Maemo provides an [[https://en.wikipedia.org/wiki/X_terminal][X-terminal]] interface for interacting with the core operating system.  The N900 was launched alongside Maemo 5, giving the device an overall more touch-friendly interface than its predecessors and a customizable home screen which mixes application icons with shortcuts and widgets.  Maemo 5 supports [[https://en.wikipedia.org/wiki/Adobe_Flash_Player][Adobe Flash Player]] 9.4, and includes many applications designed specifically for the mobile platform such as a touch-friendly apps.  Often referred to as a "pocket computer", the N900 and its Maemo software were well received critically; it was followed up by [[https://en.wikipedia.org/wiki/Nokia_N9][Nokia N9]] in 2011 running on Maemo's successor [[https://en.wikipedia.org/wiki/MeeGo][MeeGo]], although by this time Nokia had committed its smartphone future to [[https://en.wikipedia.org/wiki/Windows_Phone][Windows Phone]].
#+end_quote
