:PROPERTIES:
:ID:       31f51deb-54cc-4632-8bf0-13813a598ac3
:ROAM_REFS: https://en.wikipedia.org/wiki/Cell_(processor)
:END:
#+title: (en.wikipedia.org) Cell (processor) - Wikipedia
#+filetags: :ibm_corp:processor:microprocessor:computer_architecture:computer_science:website:

#+begin_quote
  *Cell*, a shorthand for *Cell Broadband Engine Architecture*, is a 64-bit [[https://en.wikipedia.org/wiki/Multi-core_processor][multi-core]] [[https://en.wikipedia.org/wiki/Microprocessor][microprocessor]] and [[https://en.wikipedia.org/wiki/Microarchitecture][microarchitecture]] that combines a general-purpose [[https://en.wikipedia.org/wiki/PowerPC][PowerPC]] [[https://en.wikipedia.org/wiki/Central_processing_unit][core]] of modest performance with streamlined [[https://en.wikipedia.org/wiki/Coprocessor][coprocessing]] elements which greatly accelerate [[https://en.wikipedia.org/wiki/Multimedia][multimedia]] and [[https://en.wikipedia.org/wiki/Vector_processing][vector processing]] applications, as well as many other forms of dedicated computation.

  It was developed by [[https://en.wikipedia.org/wiki/Sony][Sony]], [[https://en.wikipedia.org/wiki/Toshiba][Toshiba]], and [[https://en.wikipedia.org/wiki/IBM][IBM]], an alliance known as "STI".  The architectural design and first implementation were carried out at the STI Design Center in [[https://en.wikipedia.org/wiki/Austin,_Texas][Austin, Texas]] over a four-year period beginning March 2001 on a budget reported by Sony as approaching [[https://en.wikipedia.org/wiki/United_States_dollar][US$]]400 million.  The first major commercial application of Cell was in Sony's [[https://en.wikipedia.org/wiki/PlayStation_3][PlayStation 3]] [[https://en.wikipedia.org/wiki/Video_game_console][game console]], released in 2006.  In May 2008, the Cell-based [[https://en.wikipedia.org/wiki/Roadrunner_(supercomputer)][IBM Roadrunner]] [[https://en.wikipedia.org/wiki/Supercomputer][supercomputer]] became the first [[https://en.wikipedia.org/wiki/TOP500][TOP500]] [[https://en.wikipedia.org/wiki/LINPACK_benchmarks][LINPACK]] sustained 1.0 petaflops system.  [[https://en.wikipedia.org/wiki/Mercury_Computer_Systems][Mercury Computer Systems]] also developed designs based on the Cell.

  The Cell architecture includes a [[https://en.wikipedia.org/wiki/Memory_coherence][memory coherence]] architecture that emphasizes power efficiency, prioritizes [[https://en.wikipedia.org/wiki/Bandwidth_(computing)][bandwidth]] over low [[https://en.wikipedia.org/wiki/Latency_(engineering)][latency]], and favors peak computational [[https://en.wikipedia.org/wiki/Throughput][throughput]] over the simplicity of [[https://en.wikipedia.org/wiki/Source_code][program code]].  For these reasons, Cell is widely regarded as a challenging environment for [[https://en.wikipedia.org/wiki/Software_engineering][software development]].  IBM provided a [[https://en.wikipedia.org/wiki/Linux][Linux]]-based development platform to help developers program for Cell chips.
#+end_quote
