:PROPERTIES:
:ID:       764a886c-4ccf-49cb-b783-c2d23a5ac74b
:ROAM_REFS: https://en.wikipedia.org/wiki/Edsger_W._Dijkstra
:END:
#+title: (en.wikipedia.org) Edsger W. Dijkstra - Wikipedia
#+filetags: :website:

#+begin_quote
  *Edsger Wybe Dijkstra* ([[https://en.wikipedia.org/wiki/Help:IPA/English][/ˈdaɪkstrə/]] [[https://en.wikipedia.org/wiki/Help:Pronunciation_respelling_key][/DYKE-strə/]]; Dutch: [[https://en.wikipedia.org/wiki/Help:IPA/Dutch][ˈɛtsxər ˈʋibə ˈdɛikstraː]]; 11 May 1930 -- 6 August 2002) was a Dutch [[https://en.wikipedia.org/wiki/Computer_scientist][computer scientist]], [[https://en.wikipedia.org/wiki/Programmer][programmer]], [[https://en.wikipedia.org/wiki/Software_engineer][software engineer]], [[https://en.wikipedia.org/wiki/Mathematician][mathematician]], and science [[https://en.wikipedia.org/wiki/Essay][essayist]].

  Born in [[https://en.wikipedia.org/wiki/Rotterdam][Rotterdam]] in the [[https://en.wikipedia.org/wiki/Netherlands][Netherlands]], Dijkstra studied mathematics and physics and then [[https://en.wikipedia.org/wiki/Theoretical_physics][theoretical physics]] at the [[https://en.wikipedia.org/wiki/University_of_Leiden][University of Leiden]].  [[https://en.wikipedia.org/wiki/Adriaan_van_Wijngaarden][Adriaan van Wijngaarden]] offered him a job as the first [[https://en.wikipedia.org/wiki/Computer_programmer][computer programmer]] in the Netherlands at the [[https://en.wikipedia.org/wiki/Centrum_Wiskunde_&_Informatica][Mathematical Centre in Amsterdam]], where he worked from 1952 until 1962.  He formulated and solved the [[https://en.wikipedia.org/wiki/Shortest_path_problem][shortest path problem]] in 1956, and in 1960 developed the first [[https://en.wikipedia.org/wiki/Compiler][compiler]] for the programming language [[https://en.wikipedia.org/wiki/ALGOL_60][ALGOL 60]] in conjunction with colleague [[https://en.wikipedia.org/wiki/Jaap_A._Zonneveld][Jaap A. Zonneveld]].  In 1962 he moved to [[https://en.wikipedia.org/wiki/Eindhoven][Eindhoven]], and later to [[https://en.wikipedia.org/wiki/Nuenen][Nuenen]], where he became a professor in the Mathematics Department at the [[https://en.wikipedia.org/wiki/Technische_Hogeschool_Eindhoven][Technische Hogeschool Eindhoven]].  In the late 1960s he built the [[https://en.wikipedia.org/wiki/THE_multiprogramming_system][THE multiprogramming system]], which influenced the designs of subsequent systems through its use of software-based paged virtual memory.  Dijkstra joined [[https://en.wikipedia.org/wiki/Burroughs_Corporation][Burroughs Corporation]] as its sole [[https://en.wikipedia.org/wiki/Research_fellow][research fellow]] in August 1973.  The Burroughs years saw him at his most prolific in output of research articles.  He wrote nearly 500 documents in the "EWD" series, most of them technical reports, for private circulation within a select group.

  Dijkstra accepted the Schlumberger Centennial Chair in the Computer Science Department at the [[https://en.wikipedia.org/wiki/University_of_Texas_at_Austin][University of Texas at Austin]] in 1984, working in [[https://en.wikipedia.org/wiki/Austin,_Texas][Austin, USA]], until his retirement in November 1999.  He and his wife returned from Austin to his original house in Nuenen, where he died on 6 August 2002 after a long struggle with cancer.

  He received the 1972 [[https://en.wikipedia.org/wiki/Turing_Award][Turing Award]] for fundamental contributions to developing [[https://en.wikipedia.org/wiki/Structured_programming][structured programming]] languages.  Shortly before his death, he received the [[https://en.wikipedia.org/wiki/Association_for_Computing_Machinery][ACM]] [[https://en.wikipedia.org/wiki/PODC][PODC]] Influential Paper Award in distributed computing for his work on [[https://en.wikipedia.org/wiki/Self-stabilization][self-stabilization]] of program computation.  This annual award was renamed the [[https://en.wikipedia.org/wiki/Dijkstra_Prize][Dijkstra Prize]] the following year, in his honor.
#+end_quote
