:PROPERTIES:
:ID:       46d5af34-05f9-4a5b-9c2a-5fe296c15f4a
:ROAM_REFS: https://en.wikipedia.org/wiki/Utilitarianism
:END:
#+title: (en.wikipedia.org) Utilitarianism - Wikipedia
#+filetags: :utilitarianism:philosophy:website:

#+begin_quote
  In ethical philosophy, utilitarianism is a family of normative ethical theories that prescribe actions that maximize happiness and well-being for the affected individuals.  In other words, utilitarian ideas encourage actions that lead to the greatest good for the greatest number.  Although different varieties of utilitarianism admit different characterizations, the basic idea behind all of them is, in some sense, to maximize utility, which is often defined in terms of well-being or related concepts.  For instance, Jeremy Bentham, the founder of utilitarianism, described utility as the capacity of actions or objects to produce benefits, such as pleasure, happiness, and good, or to prevent harm, such as pain and unhappiness, to those affected.
  Utilitarianism is a version of consequentialism, which states that the consequences of any action are the only standard of right and wrong.  Unlike other forms of consequentialism, such as egoism and altruism, egalitarian utilitarianism considers either the interests of all humanity or all sentient beings equally.  Proponents of utilitarianism have disagreed on a number of issues, such as whether actions should be chosen based on their likely results (act utilitarianism), or whether agents should conform to rules that maximize utility (rule utilitarianism).  There is also disagreement as to whether total utility (total utilitarianism) or average utility (average utilitarianism) should be maximized.
  The seeds of the theory can be found in the hedonists Aristippus and Epicurus who viewed happiness as the only good, the consequentialism of the ancient Chinese philosopher Mozi who developed a theory to maximize benefit and minimize harm, and in the work of the medieval Indian philosopher Shantideva.  The tradition of modern utilitarianism began with Jeremy Bentham, and continued with such philosophers as John Stuart Mill, Henry Sidgwick, R. M. Hare, and Peter Singer.  The concept has been applied towards social welfare economics, questions of justice, the crisis of global poverty, the ethics of raising animals for food, and the importance of avoiding existential risks to humanity.
#+end_quote
