:PROPERTIES:
:ID:       7c746a64-9514-486e-ba61-4cfaf4214524
:ROAM_REFS: https://en.wikipedia.org/wiki/Josephson_effect
:END:
#+title: (en.wikipedia.org) Josephson effect - Wikipedia
#+filetags: :quantum_mechanics:physics:website:

#+begin_quote
  In physics, the Josephson effect is a phenomenon that occurs when two superconductors are placed in proximity, with some barrier or restriction between them.  The effect is named after the British physicist Brian Josephson, who predicted in 1962 the mathematical relationships for the current and voltage across the weak link.  It is an example of a macroscopic quantum phenomenon, where the effects of quantum mechanics are observable at ordinary, rather than atomic, scale.  The Josephson effect has many practical applications because it exhibits a precise relationship between different physical measures, such as voltage and frequency, facilitating highly accurate measurements.
  The Josephson effect produces a current, known as a supercurrent, that flows continuously without any voltage applied, across a device known as a Josephson junction (JJ).[clarification needed] These consist of two or more superconductors coupled by a weak link.  The weak link can be a thin insulating barrier (known as a superconductor–insulator–superconductor junction, or S-I-S), a short section of non-superconducting metal (S-N-S), or a physical constriction that weakens the superconductivity at the point of contact (S-c-S).
  Josephson junctions have important applications in quantum-mechanical circuits, such as SQUIDs, superconducting qubits, and RSFQ digital electronics.  The NIST standard for one volt is achieved by an array of 20,208 Josephson junctions in series.
#+end_quote
