:PROPERTIES:
:ID:       e91acbe9-913e-4700-a7ed-1c445a2024c7
:ROAM_REFS: https://f-droid.org/en/packages/com.github.olga_yakovleva.rhvoice.android/
:END:
#+title: (f-droid.org) RHVoice - a free and open source speech synthesize | F-Droid - Free and Open Source Android App Repository
#+filetags: :text_to_speech:machine_learning:software:website:

#+begin_quote
  RHVoice is a free and open source speech synthesizer.
  Voices are built from recordings of natural speech.  They have small footprints, because only statistical models are stored on users' computers.  And though the voices lack the naturalness of the synthesizers which generate speech by combining segments of the recordings themselves, they are still very intelligible and resemble the speakers who recorded the source material.

  Supported languages:
  Initially, RHVoice could speak only Russian.  Now it also supports American English, Brazilian Portuguese, Esperanto, Georgian, Ukrainian, Kyrgyz and Tatar.  In theory, it is possible to implement support for other languages, if all the necessary resources can be found or created.
#+end_quote
