:PROPERTIES:
:ID:       633f44b3-7ccf-442c-8913-7c65a0ed5355
:ROAM_REFS: https://gchq.github.io/CyberChef/
:END:
#+title: (gchq.github.io) CyberChef
#+filetags: :www:software_development:software:website:

#+begin_quote
  * CyberChef - The Cyber Swiss Army Knife

  Version 10.19.4\\
  Compile time: 21/02/2025 22:14:02 UTC

  © Crown Copyright 2016-2025.

  Released under the Apache Licence, Version 2.0.

  - [[https://gchq.github.io/CyberChef/#faqs][FAQs]]
  - [[https://gchq.github.io/CyberChef/#report-bug][Report a bug]]
  - [[https://gchq.github.io/CyberChef/#about][About]]
  - [[https://gchq.github.io/CyberChef/#keybindings][Keybindings]]

  ** FAQ

  [[https://gchq.github.io/CyberChef/null][How does X feature work?]]

  CyberChef has a contextual help feature. Just hover your cursor over a feature that you want to learn more about and press =F1= on your keyboard to get some information about it. Give it a try by hovering over this text and pressing =F1= now!

  [[https://gchq.github.io/CyberChef/null][What sort of things can I do with CyberChef?]]

  There are 452 operations in CyberChef allowing you to carry out simple and complex tasks easily. Here are some examples:

  - [[https://gchq.github.io/CyberChef/#recipe=From_Base64('A-Za-z0-9+/=',true)&input=VTI4Z2JHOXVaeUJoYm1RZ2RHaGhibXR6SUdadmNpQmhiR3dnZEdobElHWnBjMmd1][Decode a Base64-encoded string]]
  - [[https://gchq.github.io/CyberChef/#recipe=Translate_DateTime_Format('Standard%20date%20and%20time','DD/MM/YYYY%20HH:mm:ss','UTC','dddd%20Do%20MMMM%20YYYY%20HH:mm:ss%20Z%20z','Australia/Queensland')&input=MTUvMDYvMjAxNSAyMDo0NTowMA][Convert a date and time to a different time zone]]
  - [[https://gchq.github.io/CyberChef/#recipe=Parse_IPv6_address()&input=MjAwMTowMDAwOjQxMzY6ZTM3ODo4MDAwOjYzYmY6M2ZmZjpmZGQy][Parse a Teredo IPv6 address]]
  - [[https://gchq.github.io/CyberChef/#recipe=From_Hexdump()Gunzip()&input=MDAwMDAwMDAgIDFmIDhiIDA4IDAwIDEyIGJjIGYzIDU3IDAwIGZmIDBkIGM3IGMxIDA5IDAwIDIwICB8Li4uLi6881cu/y7HwS4uIHwKMDAwMDAwMTAgIDA4IDA1IGQwIDU1IGZlIDA0IDJkIGQzIDA0IDFmIGNhIDhjIDQ0IDIxIDViIGZmICB8Li7QVf4uLdMuLsouRCFb/3wKMDAwMDAwMjAgIDYwIGM3IGQ3IDAzIDE2IGJlIDQwIDFmIDc4IDRhIDNmIDA5IDg5IDBiIDlhIDdkICB8YMfXLi6+QC54Sj8uLi4ufXwKMDAwMDAwMzAgIDRlIGM4IDRlIDZkIDA1IDFlIDAxIDhiIDRjIDI0IDAwIDAwIDAwICAgICAgICAgICB8TshObS4uLi5MJC4uLnw][Convert data from a hexdump, then decompress]]
  - [[https://gchq.github.io/CyberChef/#recipe=RC4(%7B'option':'UTF8','string':'secret'%7D,'Hex','Hex')Disassemble_x86('64','Full%20x86%20architecture',16,0,true,true)&input=MjFkZGQyNTQwMTYwZWU2NWZlMDc3NzEwM2YyYTM5ZmJlNWJjYjZhYTBhYWJkNDE0ZjkwYzZjYWY1MzEyNzU0YWY3NzRiNzZiM2JiY2QxOTNjYjNkZGZkYmM1YTI2NTMzYTY4NmI1OWI4ZmVkNGQzODBkNDc0NDIwMWFlYzIwNDA1MDcxMzhlMmZlMmIzOTUwNDQ2ZGIzMWQyYmM2MjliZTRkM2YyZWIwMDQzYzI5M2Q3YTVkMjk2MmMwMGZlNmRhMzAwNzJkOGM1YTZiNGZlN2Q4NTlhMDQwZWVhZjI5OTczMzYzMDJmNWEwZWMxOQ][Decrypt and disassemble shellcode]]
  - [[https://gchq.github.io/CyberChef/#recipe=Fork('\n','\n',false)From_UNIX_Timestamp('Seconds%20(s)')&input=OTc4MzQ2ODAwCjEwMTI2NTEyMDAKMTA0NjY5NjQwMAoxMDgxMDg3MjAwCjExMTUzMDUyMDAKMTE0OTYwOTYwMA][Display multiple timestamps as full dates]]
  - [[https://gchq.github.io/CyberChef/#recipe=Fork('\n','\n',false)Conditional_Jump('1',false,'base64',10)To_Hex('Space')Return()Label('base64')To_Base64('A-Za-z0-9+/=')&input=U29tZSBkYXRhIHdpdGggYSAxIGluIGl0ClNvbWUgZGF0YSB3aXRoIGEgMiBpbiBpdA][Carry out different operations on data of different types]]
  - [[https://gchq.github.io/CyberChef/#recipe=Register('key=(%5B\da-f%5D*)',true,false)Find_/_Replace(%7B'option':'Regex','string':'.*data=(.*)'%7D,'$1',true,false,true)RC4(%7B'option':'Hex','string':'$R0'%7D,'Hex','Latin1')&input=aHR0cDovL21hbHdhcmV6LmJpei9iZWFjb24ucGhwP2tleT0wZTkzMmE1YyZkYXRhPThkYjdkNWViZTM4NjYzYTU0ZWNiYjMzNGUzZGIxMQ][Use parts of the input as arguments to operations]]

  [[https://gchq.github.io/CyberChef/null][Can I load input directly from files?]]

  Yes! Just drag your file over the input box and drop it.

  CyberChef can handle files up to around 2GB (depending on your browser), however some of the operations may take a very long time to run over this much data.

  If the output is larger than a certain threshold (default [[https://gchq.github.io/CyberChef/#recipe=Multiply('Line%20feed')Convert_data_units('Bytes%20(B)','Mebibytes%20(MiB)')&input=MTAyNAoxMDI0][1MiB]]), it will be presented to you as a file available for download. Slices of the file can be viewed in the output if you need to inspect them.

  [[https://gchq.github.io/CyberChef/null][How do I run operation X over multiple inputs at once?]]

  Maybe you have 10 timestamps that you want to parse or 16 encoded strings that all have the same key.

  The 'Fork' operation (found in the 'Flow control' category) splits up the input line by line and runs all subsequent operations on each line separately. Each output is then displayed on a separate line. These delimiters can be changed, so if your inputs are separated by commas, you can change the split delimiter to a comma instead.

  [[https://gchq.github.io/CyberChef/#recipe=Fork('\n','\n',false)From_UNIX_Timestamp('Seconds%20(s)')&input=OTc4MzQ2ODAwCjEwMTI2NTEyMDAKMTA0NjY5NjQwMAoxMDgxMDg3MjAwCjExMTUzMDUyMDAKMTE0OTYwOTYwMA][Click here]] for an example.

  [[https://gchq.github.io/CyberChef/null][How does the 'Magic' operation work?]]

  The 'Magic' operation uses a number of methods to detect encoded data and the operations which can be used to make sense of it. A technical description of these methods can be found [[https://github.com/gchq/CyberChef/wiki/Automatic-detection-of-encoded-data-using-CyberChef-Magic][here]].

  ** Report a Bug

  If you find a bug in CyberChef, please raise an issue in our GitHub repository explaining it in as much detail as possible. Copy and include the following information if relevant.

  #+begin_example
    * Version: 10.19.4
    * Compile time: 21/02/2025 22:14:02 UTC
    * User-Agent:
    Mozilla/5.0 (X11; Linux x86_64; rv:128.0) Gecko/20100101 Firefox/128.0
    * [Link to reproduce](https://gchq.github.io/CyberChef/)
  #+end_example

  [[https://github.com/gchq/CyberChef/issues/new/choose][Raise issue on GitHub]]

  ** About

  *** *What*

  A simple, intuitive web app for analysing and decoding data without having to deal with complex tools or programming languages. CyberChef encourages both technical and non-technical people to explore data formats, encryption and compression.

  *** *Why*

  Digital data comes in all shapes, sizes and formats in the modern world -- CyberChef helps to make sense of this data all on one easy-to-use platform.

  *** *How*

  The interface is designed with simplicity at its heart. Complex techniques are now as trivial as drag-and-drop. Simple functions can be combined to build up a "recipe", potentially resulting in complex analysis, which can be shared with other users and used with their input.

  For those comfortable writing code, CyberChef is a quick and efficient way to prototype solutions to a problem which can then be scripted once proven to work.

  *** *Who*

  It is expected that CyberChef will be useful for cybersecurity and antivirus companies. It should also appeal to the academic world and any individuals or companies involved in the analysis of digital data, be that software developers, analysts, mathematicians or casual puzzle solvers.

  *** *Aim*

  It is hoped that by releasing CyberChef through [[https://github.com/gchq/CyberChef][GitHub]], contributions can be added which can be rolled out into future versions of the tool.

  There are 452 useful operations in CyberChef for anyone working on anything vaguely Internet-related, whether you just want to convert a timestamp to a different format, decompress gzipped data, create a SHA3 hash, or parse an X.509 certificate to find out who issued it.

  It's the Cyber Swiss Army Knife.
#+end_quote
