:PROPERTIES:
:ID:       42cca393-8613-422e-9415-239ab9ae3221
:ROAM_REFS: https://gigamonkeys.com/book/beyond-exception-handling-conditions-and-restarts
:END:
#+title: (gigamonkeys.com) Beyond Exception Handling: Conditions and Restarts
#+filetags: :common_lisp:lisp:books:website:

#+begin_quote
  One of Lisp's great features is its condition system.  It serves a similar purpose to the exception handling systems in Java, Python, and C++ but is more flexible.  In fact, its flexibility extends beyond error handling—conditions are more general than exceptions in that a condition can represent any occurrence during a program's execution that may be of interest to code at different levels on the call stack.  For example, in the section "Other Uses for Conditions," you'll see that conditions can be used to emit warnings without disrupting execution of the code that emits the warning while allowing code higher on the call stack to control whether the warning message is printed.  For the time being, however, I'll focus on error handling.
#+end_quote
