:PROPERTIES:
:ID:       0733e52c-c3d8-4db9-8568-3bf467aeeaa7
:ROAM_REFS: https://github.com/jaywalnut310/vits
:END:
#+title: (github.com) jaywalnut310/vits: VITS: Conditional Variational Autoencoder with Adversarial Learning for End-to-End Text-to-Speech
#+filetags: :text_to_speech:machine_learning:software:website:

#+begin_quote
  In our recent paper, we propose VITS: Conditional Variational Autoencoder with Adversarial Learning for End-to-End Text-to-Speech.

  Several recent end-to-end text-to-speech (TTS) models enabling single-stage training and parallel sampling have been proposed, but their sample quality does not match that of two-stage TTS systems.  In this work, we present a parallel end-to-end TTS method that generates more natural sounding audio than current two-stage models.  Our method adopts variational inference augmented with normalizing flows and an adversarial training process, which improves the expressive power of generative modeling.  We also propose a stochastic duration predictor to synthesize speech with diverse rhythms from input text.  With the uncertainty modeling over latent variables and the stochastic duration predictor, our method expresses the natural one-to-many relationship in which a text input can be spoken in multiple ways with different pitches and rhythms.  A subjective human evaluation (mean opinion score, or MOS) on the LJ Speech, a single speaker dataset, shows that our method outperforms the best publicly available TTS systems and achieves a MOS comparable to ground truth.

  Visit our demo for audio samples.

  We also provide the pretrained models.
#+end_quote
