:PROPERTIES:
:ID:       782dabf7-d1c8-4fff-bca6-ddcd0771f132
:ROAM_REFS: https://github.com/segv/jss
:END:
#+title: (github.com) segv/jss: jsSlime - An emacs toolkit for developing and debugging in-browser javascript code
#+filetags: :firefox:emacs:programming:web_development:www:software:website:

#+begin_quote
  * jsSlime - An emacs interface to webkit and mozilla debuggers

  jsSlime (jss for short) is designed for emacs users who program web based javascript applications.

  ** Salient Features

  Connects directly to your browser.  Does not require injecting js into pages nor using some kind of middle man / proxy (well, the browser itself is the middle man or proxy). This means that any page can be debugged without having to change the page itself.

  Has debugger buffers with exceptions and per call-frame code evaluation and source code navigation.

  Implements ‘resume points' to automatically skip exceptions in code we don't control or aren't interested in debugging.

  Quickly see the raw http request/response headers sent over the network.

  Customizable pretty printing of server responses (currently has syntax highlighting for html, css and js, and parsing/reindenting of json data)

  HTTP repl mode for testing and debugging ajax apis.

  Since its emacs the debugger and your editing environment are the same.
#+end_quote
