:PROPERTIES:
:ID:       25a5cf42-5cb4-49a8-93ed-1f49ad410dcb
:ROAM_REFS: https://github.com/stumpwm/mahogany
:END:
#+title: (github.com) stumpwm/mahogany: A stumpwm like Wayland compositor
#+filetags: :website:

#+begin_quote
  * Mahogany

  Mahogany is a tiling window manager for Wayland modeled after StumpWM.  While it is not a drop-in replacement for stumpwm, stumpwm users should be very comfortable with Mahogany.  Its planned features are:

  - Easy extensibility: through the use of different modes, users can modify keybindings present in Mahogany.
  - Module system that allows users to load and use code at their discretion.
  - Programs to interact with other running services such as pulseaudio and alsamixer, as well as facilities to control screen brightness.  These are module based, so they don't have to be loaded if your system doesn't use them.
  - Good support for floating windows.
  - A configuration system using Common Lisp.

  This branch contains a version of Mahogany using a backend written in C. The old version written entirely in Common Lisp can be found in the [[https://github.com/stumpwm/mahogany/tree/full-cl-old][full-cl-old]] branch.
#+end_quote
