:PROPERTIES:
:ID:       14fb1e65-fb9b-4808-ac1e-262099d81174
:ROAM_REFS: https://github.com/MPRI
:END:
#+title: (github.com) MPRI
#+filetags: :education:website:

#+begin_quote
  The MPRI is a research-oriented master programme in computer science run jointly by the following institutions: Université de Paris (which is the coordinating institution), l'École normale supérieure de la rue d'Ulm, Paris, henceforth ENS Ulm, and University Paris Saclay (which includes l'Ecole normale supérieure de Paris-Saclay (ENS Paris-Saclay)), Institut Polytechnique de Paris (which includes l'École Polytechnique, and Telecom Paris).  Moreover the Master has special ties with the following universities and research institutions: Sorbonne Université (SU), CNRS, INRIA, and CEA.
  Its purpose is to train future scientists through intensive exposure to contemporary research in computer science.  It is open to students who have completed a French Licence or equivalent Bachelor's degree at a French or foreign college or university.
  Most MPRI graduates continue on with a doctorate (Ph.D.), although some students successfully enter professional life after obtaining their Master's degree from MPRI.  The MPRI + doctorate combination naturally leads to careers in academia (teaching-research positions at universities, full-time research positions at research institutions) or in industrial research and development.
  From a formal point of view, the Master MPRI corresponds to:
   - the specialization Recherche en Informatique (MIR) of the Master Informatique of Université de Paris.
   - the specialization Algorithmique et Fondements de la Programmation of the Master Informatique of PSL University.
   - the specialization Algorithmique et Fondements de la Programmation (AFP) of the Master Informatique of University Paris Saclay.
   - the specialization MPRI of the Master Foundations of Computer Science of IP Paris.
  The application rules determine the Master where candidates should apply and enroll.  The validation rules of the Master are independent of the institution where the student enrolls.
#+end_quote
* (github.com) M2-4-2/Types and Programming Languages.pdf at master · MPRI/M2-4-2 :mathematics:programming_language_design:books:website:
:PROPERTIES:
:ID:       9b747334-ee05-4d9e-820f-a62215d803a7
:ROAM_REFS: "https://github.com/MPRI/M2-4-2/blob/master/Types and Programming Languages.pdf"
:END:
