:PROPERTIES:
:ID:       fd6a7eb7-153a-49a5-888d-7948e933e4f6
:ROAM_REFS: https://github.com/rags/toggle-test
:END:
#+title: (github.com) rags/toggle-test: Language agnostic test toggle functionality for Emacs
#+filetags: :emacs_lisp:emacs:programming:software_development:software:website:

#+begin_quote
  * Toggle Test

  Toggle Test allows you to quickly switch between test and test subject.  This is a very useful tool to have when you are [[http://en.wikipedia.org/wiki/Test-driven_development][TDD]]ing.  Test Toggle is similar to test toggle functionality provided by IntelliJ and other JetBrains IDEs.

  *Features:*

  - Test Toggle allows you quick navigate between test and source files, without having to remember file paths.
  - It creates the the test or source file you are trying to navigate to (along the entire directory hierarchy) if it does not already exist.
  - Sometimes there might be mutiple test files for a given source (Ex: Unit and Integration test). Test Toggle presents the user with choices whenever there is multiple matches and navigates to the chosen file (creating it of required).
  - Test Toggle is language/tech stack agnostic.  So it can work with your Rails, Python, Clojure or any other project.
  - You can work with multiple such projects at the same time.
#+end_quote
