:PROPERTIES:
:ID:       266e410a-c16d-40b0-8c50-65e9df7efa26
:ROAM_REFS: https://hbpms.blogspot.com/
:END:
#+title: (hbpms.blogspot.com) How to Become a Pure Mathematician (or Statistician)
#+filetags: :books:education_resource:mathematics:lists:blog_post:blogs:website:

#+begin_quote
  * How to Become a Pure Mathematician (or Statistician)

  a List of Undergraduate and Basic Graduate Textbooks and Lecture Notes - the blog

  *** [[https://hbpms.blogspot.com/2008/05/content-and-about.html][Content and About]]

  Last Revised: 4/6/2012

  *Table of Contents*

  Stage 1
  - [[http://hbpms.blogspot.com/2008/05/stage-1-elementary-stuff.html][Elementary Stuff]]
  - [[http://hbpms.blogspot.com/2008/05/stage-1-introductory-discrete.html][Introductory Discrete Mathematics]]
  - [[http://hbpms.blogspot.com/2008/05/stage-1-introductory-algebra.html][Introductory Algebra]]
  - [[http://hbpms.blogspot.com/2008/05/stage-1-introductory-calculus.html][Introductory Calculus]]

  Stage 2
  - [[http://hbpms.blogspot.com/2008/05/stage-2-linear-algebra.html][Linear Algebra]]
  - [[http://hbpms.blogspot.com/2008/05/stage-2-introductory-higher-algebra.html][Introductory Higher Algebra]]
  - [[http://hbpms.blogspot.com/2008/05/stage-2-calculus.html][Calculus (Introductory Real Analysis, Several Variables Calculus, Vector Calculus, etc)]]
  - [[http://hbpms.blogspot.com/2008/05/stage-2-complex-variable.html][Complex Variables (Introductory Complex Analysis)]]
  - [[http://hbpms.blogspot.com/2008/05/stage-2-differential-equations.html][Differential Equation]]
  - [[http://hbpms.blogspot.com/2008/05/stage-2-probability-and-statistics.html][Probability and Statistics]]

  Stage 3
  - [[http://hbpms.blogspot.com/2008/05/stage-3-introductory-analysis.html][Introductory Analysis]]
  - [[http://hbpms.blogspot.com/2008/05/stage-3-abstract-algebra.html][Abstract Algebra]]
  - [[http://hbpms.blogspot.com/2008/05/stage-3-introductory-number-theory.html][Introductory Number Theory]]
  - [[http://hbpms.blogspot.com/2008/05/stage-3-introductory-topology.html][Introductory Topology]]
  - [[http://hbpms.blogspot.com/2008/05/stage-3-differential-geometry.html][Differential Geometry]]
  - [[http://hbpms.blogspot.com/2008/05/stage-3-mathematical-modelling.html][Mathematical Modelling (optional)]]
  - [[http://hbpms.blogspot.com/2008/05/stage-3-statistical-inference.html][Statistical Inference (optional)]]
  - [[http://hbpms.blogspot.com/2008/05/stage-3-probability-and-stochastic.html][Probability and Stochastic Processes (optional)]]
  - [[http://hbpms.blogspot.com/2008/05/stage-3-statistical-computing.html][Statistical Computing (optional)]]

  Stage 4
  - [[http://hbpms.blogspot.com/2008/05/stage-4-foundations-and-discrete.html][Foundations and Discrete Mathematics]]
    Foundation, Logic, Set Theory, etc, Graph Theory, Combinatorics, Cryptography, Coding and Information Theory.
  - [[http://hbpms.blogspot.com/2008/05/stage-4-analysis.html][Analysis]] Functional Analysis, Measure Theory, Hilbert Spaces, Real and Complex Analysis, Fourier and Harmonic Analysis.
  - [[http://hbpms.blogspot.com/2008/05/stage-4-algebra.html][Algebra]] Advanced Linear Algebra, Groups and Lie Algebras, Rings, Fields and Galois Theory, Modules and Representation Theory, Commutative Algebra, Homological Algebra and Category.
  - [[http://hbpms.blogspot.com/2008/05/stage-4-number-theory.html][Number Theory]] Algebraic NT, Class Field Theory, Analytic NT, Riemann Zeta Function and the Hypothesis, Modular Forms, Elliptic Curves, etc.
  - [[http://hbpms.blogspot.com/2008/05/stage-4-geometry.html][Geometry]] Algebraic Geometry, Differential Geometry, Riemannian Geometry, Fractals.
  - [[http://hbpms.blogspot.com/2008/05/stage-4-topology.html][Topology]] Geometric Topology, Algebraic Topology, K-theory, Differential Topology.
  - [[http://hbpms.blogspot.com/2008/05/stage-4-further-calculus.html][Further Calculus (optional)]] Ordinary DE, Partial DE, Calculus of Variations.
  - [[http://hbpms.blogspot.com/2008/05/stage-4-mathematical-physics.html][Mathematical Physics (optional)]] Mathematical methods in physics, Relativity, Quantum Mechanics, Quantum Field Theory, String Theory, Chaos.
  - [[http://hbpms.blogspot.com/2008/05/stage-4-probability.html][Probability (optional)]] Probaility built upon Measure Theory, Stochastic Processes, Stochastic Analysis.
  - [[http://hbpms.blogspot.com/2008/05/stage-4-statistics.html][Statistics (optional)]] Statistical Models and Regression, Multivariate Analysis, Bayesian Statistics, Simulation and the Monte Carlo Method, Nonparametric Statistics, Categorical Data Analysis, Data Mining, Time Series.
  - [[http://hbpms.blogspot.com/2008/05/stage-4-biostatistics.html][Biostatistics (optional)]] Statistical Methods in Epidemiology, Design and Analysis of Clinical Trials, Longitudinal Data Analysis, Survival Analysis.

  Stage 5

  : It's like if you want to be a good pianist,
  : you have to do a lot of scales and a lot of practice,
  : and a lot of that is kind of boring, it's work.
  : But you need to do that before you can really be very expressive and really play beautiful music.
  : You have to go through that phase of practice and drill.
  — Terry Tao

  About this article:

  - What for?
    OK, there is a way to [[http://www.phys.uu.nl/~thooft/theorist.html][become a good theoretical physicist]].  Here is a guide to study pure mathematics, or even more.  This list is written for those who want to learn mathematics but have no idea how to start.  Yup, a list for beginners.  I don't claim that this list makes you a /good/ pure mathematician, since I belong to the complement of good pure mathematician.  I make no attempt to define what pure mathematics is, but hopefully it will be clear as you proceed.  I also highlighted several books that you would really like to keep in your own library.  You probably like to read those books again and again in your life.  Free material excluded.  Note the highlighted list does NOT indicate those books are good for beginners.  I shall try to keep this list up to date whenever I exist.
  - Assumed knowledge.
    I assumed you have high school mathematics background (i.e. basic trigonometry, Euclidean geometry, etc).  The aim of this page is to introduce what different branches of mathematics are; and recommended a few notes or texts.
    Scientists in other fields and engineers may skip first or second stages and begin at later stages, according to their prior knowledge.
  - Time.
    It takes approximately one year for each stage (except for stage 4, I list more material in each field for more advanced studies), for a full time student.  Part time students may double the time.  But its better for anyone to understand most parts of stage n before proceeding to n+1, for some integer n in {1, 2, 3, 4}.  If you decided to attend a class, don't expect the professor can teach, it always happen, especially in higher level courses.  What's the order of courses to study within a stage doesn't really matter, usually.  One doesn't need to read every listed book within a subject to master the subject.  I listed more than enough so that you can scout around to find one that you feel comfortable with.  Some people like to consult a few books, beware of the symbols from different books in such cases.
    Moreover, it often happens that you couldn't solve a problem within an hour.  It's not surprise to spend a week or more to tackle one problem.  Things may come to your head suddenly.  Shouting eureka is the high point of a mathematician.
  - "Axiom of choice".
    My selection will not be bounded by any publication press, author's nationality or religion.  It relies on two factors: well written or cheap.  These two factors are not mutually exclusive.  I treat "free" as an element in "cheap".  Note the price factor may by irrelevant, sometimes I get a HK $2xx book and Amazon says its US $1xx (~HK $7xx)...... with the only difference is, perhaps, I got the international edition.  Moreover, some Chinese press in mainland China published photocopied of English text with a relatively cheap price.
    Bear in mind that, just because one is a good mathematician doesn't imply he's a good author or educator.  Perhaps Terry Tao is an exceptional case.  To study science, reading the classics (the /Elements/, /Dialogo sopra i due massimi sistemi del mondo/, the /Principia/, /Disquisitiones Arithmeticae/, /Principia Mathematica/, etc) is optional.  While for literature or philosophy, I wonder if any well educated student has never study Shakespeare or Plato.
    To view [.pdf] [[http://www.adobe.com/products/acrobat/readstep2.html][get Adobe Reader]], to view [.ps] download [[ftp://mirror.cs.wisc.edu/pub/mirrors/ghost/AFPL/gs853/gs853w32.exe][this]] and [[ftp://mirror.cs.wisc.edu/pub/mirrors/ghost/ghostgum/gsv48w32.exe][this]], or visit [[http://pages.cs.wisc.edu/~ghost/gsview/][this page]], to view [.djvu] get [[http://www.lizardtech.com/download/dl_options.php?page=doc][this]].  Get [[http://www.rarlab.com/][WinRAR]] for [.rar] files.
  - Comments.
    Links to Amazon for most of the listed book are included, so that you have an easy access to other users' comments.  Note that the comments are sometimes quite extreme: for the same book, one rated it with 5 star (with dozens of people supporting) and at the same time another rated 1 star (with dozens of people supporting again), especially for introductory discrete mathematics, probability and statistics books.  It seemed to me that lots of people study these subjects because they need to, they want to apply mathematics.  Large proportion of these readers are lack of mathematical maturity.  If they can't pass the exam, you know...  In contrast, most pure mathematics students study because they like the subject and enjoy it.  So, ask yourself, why do you study?
  - Other resources.
    Although I'm not into reading books online, I should remind you that [[http://ocw.mit.edu/OcwWeb/Mathematics/index.htm][MIT's open recourse]], [[http://www.archim.org.uk/notes/][the Archimedeans]] and [[http://en.wikibooks.org/wiki/Category:Mathematics][Wikibooks]] provide another great sources of materials.  These are excluded in the following list.  The list below aimed to recommend books or (usually) printable notes. [[http://books.google.com/][Google books]] allow you to preview sections from a book. [[http://www.mhprofessional.com/category/?cat=4234][Schaum's Outlines]] series are cheap, but I seldom include them, you may search the relevant if you like.
  - Me.
    A product of [[http://www.maths.unsw.edu.au/][School of Mathematics and Statistics]], [[http://www.unsw.edu.au/][UNSW]], Sydney, Australia.  I've taken all undergraduate core pure mathematics and statistics courses there, with all pure mathematics courses in higher level (perhaps equivalent to Honors Courses in the US which focus on theory), whenever they exist.  Also, I was Terry Tao's teacher's student, Michael Artin's student's student, Gottfried Leibniz's student Jacob Bernoulli's student Johann Bernoulli's student Leonhard Euler's student Joseph Lagrange's student Simeon Poisson's student's student's student's student's student's student's student's student's student, Max Planck's student's student's student's student and Thomas Kuhn's student's student.  Just feel like I'm an idiot.
  - Disclaimer.
    I'm not responsible for any external link.
  - Comments/suggestion for a book, etc.  Either make comment in the blog [[http://hbpms.blogspot.com/]] or email me: [[https://www.blogger.com/mathphyweb@yahoo.com.hk][mathphyweb@yahoo.com.hk]].
#+end_quote
