:PROPERTIES:
:ID:       228ff5ea-225f-45ea-8370-fb51a48e0a8c
:ROAM_REFS: https://ipa-reader.com/
:END:
#+title: (ipa-reader.com) IPA Reader
#+filetags: :international_phonetic_alphabet:website:

#+begin_quote
  This is a tool for reading [[https://en.wikipedia.org/wiki/International_Phonetic_Alphabet][International Phonetic Alphabet (IPA)]] notation aloud.

  It makes it easy to actually hear how words are pronounced based on their phonetic spelling, without having to look up each character in [[https://upload.wikimedia.org/wikipedia/commons/8/8e/IPA_chart_2018.pdf][the IPA chart]] and string the sounds together yourself.

  For example, "budgerigar" (AKA the [[https://en.wikipedia.org/wiki/Budgerigar][common parakeet]]) can be pronounced according to its IPA notation =/ˈbʌdʒərɪɡɑːr/=.

  ** How Do You Use It?

  Find a word you would like to hear pronounced, grab the IPA notation (if you don't already have it, [[https://en.wiktionary.org/][Wiktionary]] is a great place to look), toss it in the form, and hit the "Read" button.

  For example, =/ˈpɪdʒən/= will be read as "pigeon."

  ** How Does It Work?

  I had fun making this, so I wrote about how it was built [[https://cuttlesoft.com/blog/2018/09/13/pronouncing-things-with-amazons-polly/][here]]!

  Basically, the current version structures a request to Amazon Polly, a text-to-speech service, then retrieves and plays the resulting generated audio.

  (This also means that pronunciation is constrained by which phonemes Polly does or does not support; details about specific phonemes can be found in their [[https://docs.aws.amazon.com/polly/latest/dg/ref-phoneme-tables-shell.html][documentation of supported phonemes]].)
#+end_quote
