:PROPERTIES:
:ID:       474a3ecc-55a3-4627-b57c-09d36deda29e
:ROAM_REFS: https://ladybird.org/
:END:
#+title: (ladybird.org) Ladybird
#+filetags: :www:software:website:

#+begin_quote
  * Welcome to Ladybird, a truly independent web browser.

  We are building a brand-new browser from scratch, backed by a non-profit.

  ** About Ladybird

  Ladybird is a brand-new browser & web engine.  Driven by a web standards first approach, Ladybird aims to render the modern web with good performance, stability and security.

  From its humble beginnings as an HTML viewer for the SerenityOS hobby operating system project, Ladybird has since grown into a cross-platform browser supporting Linux, macOS, and other Unix-like systems.

  Ladybird is currently in heavy development.  We are targeting a first Alpha release for early adopters in 2026.

  ** What makes Ladybird unique

  **** Truly independent

  No code from other browsers.  We're building a new engine, based on web standards.

  **** Singular focus

  We are focused on one thing: the web browser.

  **** No monetization

  No "default search deals", crypto tokens, or other forms of user monetization, ever.
#+end_quote
