:PROPERTIES:
:ID:       6dc55bf7-213c-49ff-91f5-7c6a5c910529
:ROAM_REFS: https://learn.microsoft.com/en-us/windows-hardware/drivers/debugger/debugger-download-tools
:END:
#+title: (learn.microsoft.com) Debugging Tools for Windows - Windows drivers | Microsoft Learn
#+filetags: :documentation:programming:software_development:software:microsoft_windows:microsoft:website:

#+begin_quote
  * Debugging Tools for Windows

  - Article
  - 12/06/2024
  -

  ** In this article

  1. [[https://learn.microsoft.com/en-us/windows-hardware/drivers/debugger/debugger-download-tools#install-debugging-tools-for-windows][Install Debugging Tools for Windows]]
  2. [[https://learn.microsoft.com/en-us/windows-hardware/drivers/debugger/debugger-download-tools#debugging-environments][Debugging environments]]
  3. [[https://learn.microsoft.com/en-us/windows-hardware/drivers/debugger/debugger-download-tools#windows-debuggers][Windows debuggers]]
  4. [[https://learn.microsoft.com/en-us/windows-hardware/drivers/debugger/debugger-download-tools#command-line-debuggers][Command line debuggers]]
  5. [[https://learn.microsoft.com/en-us/windows-hardware/drivers/debugger/debugger-download-tools#symbols-and-symbol-files][Symbols and symbol files]]
  6. [[https://learn.microsoft.com/en-us/windows-hardware/drivers/debugger/debugger-download-tools#blue-screens-and-crash-dump-files][Blue screens and crash dump files]]
  7. [[https://learn.microsoft.com/en-us/windows-hardware/drivers/debugger/debugger-download-tools#looking-for-the-debugging-tools-for-earlier-versions-of-windows][Looking for the debugging tools for earlier versions of Windows?]]
  8. [[https://learn.microsoft.com/en-us/windows-hardware/drivers/debugger/debugger-download-tools#learn-more-about-the-debuggers][Learn more about the debuggers]]
  9. [[https://learn.microsoft.com/en-us/windows-hardware/drivers/debugger/debugger-download-tools#looking-for-other-downloads][Looking for other downloads?]]

  In addition to the debuggers such as WinDbg, Debugging Tools for Windows includes a set of tools that are useful for debugging. For a complete list of the tools, see [[https://learn.microsoft.com/en-us/windows-hardware/drivers/debugger/extra-tools][Tools Included in Debugging Tools for Windows]].

  For directions on how to download and install just the Windows debugger, see [[https://learn.microsoft.com/en-us/windows-hardware/drivers/debugger/][Download and install the WinDbg Windows debugger]].

  [[https://learn.microsoft.com/en-us/windows-hardware/drivers/debugger/debugger-download-tools#install-debugging-tools-for-windows]]

  ** Install Debugging Tools for Windows

  You can get Debugging Tools for Windows as part of a development kit or as a standalone toolset:

  - *As part of the WDK*

    Debugging Tools for Windows is included in the Windows Driver Kit (WDK). To get the WDK, see [[https://learn.microsoft.com/en-us/windows-hardware/drivers/download-the-wdk][Download the Windows Driver Kit (WDK)]].

  - *As part of the Windows SDK*

    Debugging Tools for Windows is included in the Windows Software Development Kit (SDK). To download the installer or an ISO image, see [[https://developer.microsoft.com/windows/downloads/windows-sdk][Windows SDK]] on Windows Dev Center.

  - *As a standalone toolset*

    You can install the Debugging Tools for Windows alone, without the Windows SDK or WDK, by starting the installation of the Windows SDK and then selecting only *Debugging Tools for Windows* in the list of features to install (and clearing the selection of all other features). To download the installer or an ISO image, see [[https://developer.microsoft.com/windows/downloads/windows-10-sdk][Windows SDK]] on Windows Dev Center.

  [[https://learn.microsoft.com/en-us/windows-hardware/drivers/debugger/debugger-download-tools#debugging-environments]]

  ** Debugging environments

  If your computer has Visual Studio and the WDK installed, then you have six available debugging environments. For descriptions of these environments, see [[https://learn.microsoft.com/en-us/windows-hardware/drivers/debugger/debuggers-in-the-debugging-tools-for-windows-package][Debugging Environments]].

  All of these debugging environments provide user interfaces for the same underlying debugging engine, which is implemented in the Windows Symbolic Debugger Engine (Dbgeng.dll). This debugging engine is also called the /Windows debugger/, and the six debugging environments are collectively called the /Windows debuggers/.

  Note

  Visual Studio includes its own debugging environment and debugging engine, which together are called the /Visual Studio debugger/. For information on debugging in Visual Studio, see [[https://learn.microsoft.com/en-us/visualstudio/debugger/][Debugging in Visual Studio]]. For debugging managed code, such as C#, using the Visual Studio debugger is often the easiest way to get started.

  [[https://learn.microsoft.com/en-us/windows-hardware/drivers/debugger/debugger-download-tools#windows-debuggers]]

  ** Windows debuggers

  The Windows debuggers can run on x86-based, x64-based, or Arm-based processors, and they can debug code that is running on those same architectures. Sometimes the debugger and the code being debugged run on the same computer, but other times the debugger and the code being debugged run on separate computers. In either case, the computer that is running the debugger is called the /host computer/, and the computer that is being debugged is called the /target computer/. The Windows debuggers support the following versions of Windows for both the host and target computers.

  [[https://learn.microsoft.com/en-us/windows-hardware/drivers/debugger/debugger-download-tools#command-line-debuggers]]

  ** Command line debuggers

  There are four command line debuggers that are available for specialized environments and for those that prefer a command line interface.

  [[https://learn.microsoft.com/en-us/windows-hardware/drivers/debugger/debugger-download-tools#kd-and-ntkd]]

  *** KD and NTKD

  KD and NTKD are identical in every way, except that NTKD spawns a new text window when it is started, whereas KD inherits the Command Prompt window from which it was invoked. For more information, see [[https://learn.microsoft.com/en-us/windows-hardware/drivers/debugger/debugging-using-kd-and-ntkd][Debugging Using KD and NTKD]].

  [[https://learn.microsoft.com/en-us/windows-hardware/drivers/debugger/debugger-download-tools#cdb-and-ntsd]]

  *** CDB and NTSD

  Also available are the Microsoft Console Debugger (CDB) and Microsoft NT Symbolic Debugger (NTSD). For more information, see [[https://learn.microsoft.com/en-us/windows-hardware/drivers/debugger/debugging-using-cdb-and-ntsd][Debugging Using CDB and NTSD]].

  [[https://learn.microsoft.com/en-us/windows-hardware/drivers/debugger/debugger-download-tools#symbols-and-symbol-files]]

  ** Symbols and symbol files

  Symbol files store a variety of data that are not required when running the executable binaries, but symbol files are very useful when debugging code. For more information about creating and using symbol files, see [[https://learn.microsoft.com/en-us/windows-hardware/drivers/debugger/symbols][Symbols for Windows debugging]].

  [[https://learn.microsoft.com/en-us/windows-hardware/drivers/debugger/debugger-download-tools#blue-screens-and-crash-dump-files]]

  ** Blue screens and crash dump files

  If Windows stops working and displays a blue screen, the computer shuts down abruptly to protect itself from data loss and displays a bug check code. For more information, see [[https://learn.microsoft.com/en-us/windows-hardware/drivers/debugger/bug-checks--blue-screens-][Bug Checks (Blue Screens)]]. You can analyze crash dump files that are created when Windows shuts down by using WinDbg and other Windows debuggers. For more information, see [[https://learn.microsoft.com/en-us/windows-hardware/drivers/debugger/crash-dump-files][Crash dump analysis using the Windows debuggers (WinDbg)]].

  [[https://learn.microsoft.com/en-us/windows-hardware/drivers/debugger/debugger-download-tools#looking-for-the-debugging-tools-for-earlier-versions-of-windows]]

  ** Looking for the debugging tools for earlier versions of Windows?

  To download the debugger tools for previous versions of Windows, you need to download the Windows SDK for the version you are debugging from the [[https://developer.microsoft.com/windows/downloads/sdk-archive][Windows SDK and emulator archive]]. In the installation wizard of the SDK, select *Debugging Tools for Windows*, and deselect all other components.

  [[https://learn.microsoft.com/en-us/windows-hardware/drivers/debugger/debugger-download-tools#learn-more-about-the-debuggers]]

  ** Learn more about the debuggers

  Learn more about WinDbg in [[https://learn.microsoft.com/en-us/windows-hardware/drivers/debugger/][Download and install the WinDbg Windows debugger]].

  To get started with Windows debugging, see [[https://learn.microsoft.com/en-us/windows-hardware/drivers/debugger/getting-started-with-windows-debugging][Getting Started with Windows Debugging]].

  For additional information related to Debugging Tools for Windows, see [[https://learn.microsoft.com/en-us/windows-hardware/drivers/debugger/debugging-resources][Debugging Resources]].

  [[https://learn.microsoft.com/en-us/windows-hardware/drivers/debugger/debugger-download-tools#looking-for-other-downloads]]

  ** Looking for other downloads?

  - [[https://learn.microsoft.com/en-us/windows-hardware/drivers/download-the-wdk][Download the Windows Driver Kit (WDK)]]
  - [[https://learn.microsoft.com/en-us/windows-hardware/drivers/debugger/debugger-download-symbols][Windows Symbol Packages]]
  - [[https://learn.microsoft.com/en-us/windows-hardware/test/hlk/windows-hardware-lab-kit][Windows Hardware Lab Kit]]
  - [[https://learn.microsoft.com/en-us/windows-hardware/get-started/adk-install][Download and install the Windows Assessment and Deployment Kit (Windows ADK)]]
  - [[https://insider.windows.com/][Windows Insider - Windows Preview builds]]
#+end_quote
