:PROPERTIES:
:ID:       a8c21074-7c37-4566-b6ac-456182f0d183
:ROAM_REFS: https://mitpress.mit.edu/9780262543231/ https://mitpress.mit.edu/9780262543231/structure-and-interpretation-of-computer-programs/
:END:
#+title: (mitpress.mit.edu) Structure and Interpretation of Computer Programs, JavaScript Edition
#+filetags: :javascript:education_resource:software_development:programming:textbooks:books:computer_science:website:

#+begin_quote
  ** Description

  A new version of the classic and widely used text adapted for the JavaScript programming language.

  Since the publication of its first edition in 1984 and its second edition in 1996, /Structure and Interpretation of Computer Programs/ (/SICP/) has influenced computer science curricula around the world.  Widely adopted as a textbook, the book has its origins in a popular entry-level computer science course taught by Harold Abelson and Gerald Jay Sussman at MIT. /SICP/ introduces the reader to central ideas of computation by establishing a series of mental models for computation.  Earlier editions used the programming language Scheme in their program examples.  This edition has been adapted to JavaScript.

  The first three chapters of /SICP/ cover programming concepts that are common to all modern high-level programming languages.  Chapters four and five, which used Scheme to formulate language processors for Scheme, required significant revision.  Chapter four offers new material, in particular an introduction to the notion of program parsing.  The evaluator and compiler in chapter five introduce a subtle stack discipline to support return statements (a prominent feature of statement-oriented languages) without sacrificing tail recursion.

  The JavaScript programs included in the book run in any implementation of the language that complies with the ECMAScript 2020 specification, using the JavaScript package /SICP/ provided on the MIT Press website.
#+end_quote
* See Also
** [[id:bc4f5e4a-5bb9-47f7-8086-d12236fe793f][Structure and Interpretation of Computer Programs]]
