:PROPERTIES:
:ID:       9e6a5967-3774-4a96-839d-4a80ee22acb1
:ROAM_REFS: https://plv.mpi-sws.org/rustbelt/stacked-borrows/paper.pdf
:END:
#+title: (plv.mpi-sws.org) Stacked Borrows: An Aliasing Model for Rust - paper.pdf
#+filetags: :static_analysis:programming_type_systems:programming_language_design:rust_lang:computer_science:science_paper:mime_type_application_pdf:website:

#+begin_quote
  * Stacked Borrows: An Aliasing Model for Rust

  Ralf Jung, Mozilla, USA and MPI-SWS, Germany\\
  Hoang-Hai Dang, MPI-SWS, Germany\\
  Jeehoon Kang, KAIST, Korea\\
  Derek Dreyer, MPI-SWS, Germany

  Type systems are useful not just for the safety guarantees they provide, but also for helping compilers generate more efficient code by simplifying important program analyses.  In Rust, the type system imposes a strict discipline on pointer aliasing, and it is an express goal of the Rust compiler developers to make use of that alias information for the purpose of program optimizations that reorder memory accesses.  The problem is that Rust also supports unsafe code, and programmers can write unsafe code that bypasses the usual compiler checks to violate the aliasing discipline.  To strike a balance between optimizations and unsafe code, the language needs to provide a set of rules such that unsafe code authors can be sure, if they are following these rules, that the compiler will preserve the semantics of their code despite all the optimizations it is doing.  In this work, we propose Stacked Borrows, an operational semantics for memory accesses in Rust.  Stacked Borrows defines an aliasing discipline and declares programs violating it to have undefined behavior, meaning the compiler does not have to consider such programs when performing optimizations.  We give formal proofs (mechanized in Coq) showing that this rules out enough programs to enable optimizations that reorder memory accesses around unknown code and function calls, based solely on intraprocedural reasoning.  We also implemented this operational model in an interpreter for Rust and ran large parts of the Rust standard library test suite in the interpreter to validate that the model permits enough real-world unsafe Rust code.
#+end_quote
