:PROPERTIES:
:ID:       1e24ab3e-fb4b-411e-acec-50ca551da7e1
:ROAM_REFS: https://practicaltypography.com/
:END:
#+title: (practicaltypography.com) Butterick’s Practical Typography
#+filetags: :books:website:

* (practicaltypography.com) Type composition | Butterick’s Practical Typography
:PROPERTIES:
:ID:       c644b8c1-1a34-4653-a340-ef4cfe22fbfe
:ROAM_REFS: https://practicaltypography.com/type-composition.html
:END:

#+begin_quote
  * Type composition

  Good typography starts with good typing.  This chapter is a tour of the nonalphabetic characters on the computer keyboard---some obscure, some underappreciated, and some well-known but misused.

  A text is a sequence of characters.  Every character is a tool.  Your goal: to always use the right tool for the job.

  Today's computer keyboards depict the available characters in almost the same way as a manual typewriter.  But this depiction is misleading.  The computer keyboard can produce many more characters than the ones visible on its keys.  These include [[https://practicaltypography.com/accented-characters.html][accented characters]], [[https://practicaltypography.com/math-symbols.html][math symbols]], and [[https://practicaltypography.com/white-space-characters.html][white-space characters]]---invisible markers that are useful for getting consistent typographic results.

  Beware.  This chapter is more difficult than it might seem.  Typing is second nature for most of us.  Habits are ingrained.  After years of doing things one way, it can be hard to learn a different way.

  But it's worth it.  By typing the right characters while writing and editing, you'll save time and effort later on when you're formatting and laying out your document.
#+end_quote
