:PROPERTIES:
:ID:       dfb9719d-6ed3-46ed-ae2e-50ba87e0eca2
:ROAM_REFS: https://projecteuler.net/
:END:
#+title: (projecteuler.net) About - Project Euler
#+filetags: :programming:algorithms:computer_science:mathematics:puzzles_and_challenges:website:

#+begin_quote
  ** About Project Euler

  *** What is Project Euler?

  Project Euler is a series of challenging mathematical/computer programming problems that will require more than just mathematical insights to solve.  Although mathematics will help you arrive at elegant and efficient methods, the use of a computer and programming skills will be required to solve most problems.

  The motivation for starting Project Euler, and its continuation, is to provide a platform for the inquiring mind to delve into unfamiliar areas and learn new concepts in a fun and recreational context.

  *** Who are the problems aimed at?

  The intended audience include students for whom the basic curriculum is not feeding their hunger to learn, adults whose background was not primarily mathematics but had an interest in things mathematical, and professionals who want to keep their problem solving and mathematics on the cutting edge.

  Currently we have 1336717 registered members who have solved at least one problem, representing 220 locations throughout the world, and collectively using 114 different programming languages to solve the problems.

  *** Can anyone solve the problems?

  The problems range in difficulty and for many the experience is inductive chain learning.  That is, by solving one problem it will expose you to a new concept that allows you to undertake a previously inaccessible problem.  So the determined participant will slowly but surely work his/her way through every problem.

  *** What next?

  In order to track your progress it is necessary to setup an account and have Cookies enabled.

  If you already have an account, then [[https://projecteuler.net/sign_in][Sign In]].  Otherwise, please [[https://projecteuler.net/register][Register]] -- it's completely free!

  However, as the problems are challenging, then you may wish to view the [[https://projecteuler.net/archives][Problems]] before registering.

  "Project Euler exists to encourage, challenge, and develop the skills and enjoyment of anyone with an interest in the fascinating world of mathematics."
#+end_quote
