:PROPERTIES:
:ID:       18e7a1f3-18eb-4c28-ada2-67c3e402a3f8
:ROAM_REFS: https://prometheusdesignwerx.com/
:END:
#+title: (prometheusdesignwerx.com) Prometheus Design Werx
#+filetags: :bushcraft:hardware:equipment:outdoors:store:website:

#+begin_quote
  * FIND A WAY OR MAKE ONE

  Superior goods for the adventurous, self-reliant, and those who make their own way.

  [[https://prometheusdesignwerx.com/collections/instock][See Instock Items]]

  ** We learn from the past, look to the future, and build for today.

  We believe in those who see themselves as being more than just capable.  You rise to the occasion, live well, and with each challenge and adventure that comes your way, you adapt, improvise, overcome, conquer...do it all your way, and with “True Grit.”  #virtutevera

  ** Our Design Principles

  Prometheus Design Werx's inherent passion for creating our exceptional products to be used in their intended contexts and environments means that we intrinsically stay authentic and true to our narrative, consumer, and community.  Every product we design and craft are ones we use ourselves everyday in the field or on the street.

  ** Simplicity and Sophistication

  We admire DaVinci's declaration regarding "simplicity and sophistication" and challenge ourselves to that design end.  We recognize that it can often be a complex process to arrive there.  Sometimes less is more, but everything present must function as it is intended.

  /"Better still, [good design] can make the product clearly express its function by making use of the user's intuition.  At best, it is self-explanatory."/
  — *Dieter Rams*

  ** Form Follows Function

  Our designs' aesthetic outcomes are a consequence of the objects' functions.  We don't do racing stripes, garish flourishments, or superfluous details in our designs.  Every part, component, and detail that goes into a design serves a purpose, and its whole is greater than the sum of its parts.

  ** Experience Insight Input

  We learn from the past, look to the future, and build for today.  Our design process is one which involves the empirical, years of field experience, the fulfillment of a need, and discussions with real world users who find themselves in challenging (and sometimes dangerous) environments and conditions all over the world.

  ** Special Projects Division

  The Prometheus Design Werx's “Special Projects Division” is tasked with creating experimental runs, limited production editions, collaborations, tackling unusual design challenges, and creating unexpected but useful results that may often change and/or improves the nature of things in a particular context.  #specialprojectsdivision

  ** Featured Products

  ** FT Insulated Water Bottles

  CAMP KITCHEN

  Ruggedized-design, highest performance, premium-grade, stainless steel, vacuum-insulated water bottles.  Our FT series water bottles feature a custom fluted body design which increases material stiffness and resistance to deformation, and improves tactile grip when wet.  The unique design of the FT water bottle series was inspired by vintage bicycle parts, deflective armor, industrial-tool handles, precision barrels, aircraft, and vintage bicycle racing bottles from the 40s-50s.  #ftwaterbottle

  [[https://prometheusdesignwerx.com/collections/camp-kitchen][Learn More]]

  ** ZCaB-AW-XL

  SOFT GOODS

  Built to last, and will be as versatile, tough and all terrain as the folks who choose to use them.  Sized to perfectly fit a day's worth of beach supplies, groceries, camping supplies, climbing gear, tools, recovery gear, and more.  Based on our popular ZCaB-AW, this XL version is wider and features the classic carry over and under handle.  Over built with a burly 1000D, waterproof tarpaulin material, lined in our signature Flame Orange interior, and a zippered top to secure whatever you choose to stow inside.  Undo the 2-way zippered top and the ZCaB-AW-XL opens up (similar to those old school vinyl coin purses from the 1970's) easily to get access to the inside.

  [[https://prometheusdesignwerx.com/collections/bags][Learn More]]

  Built to last, and will be as versatile, tough and all terrain as the folks who choose to use them.  Sized to perfectly fit a day's worth of beach supplies, groceries, camping supplies, climbing gear, tools, recovery gear, and more.  Based on our popular ZCaB-AW, this XL version is wider and features the classic carry over and under handle.  Over built with a burly 1000D, waterproof tarpaulin material, lined in our signature Flame Orange interior, and a zippered top to secure whatever you choose to stow inside.  Undo the 2-way zippered top and the ZCaB-AW-XL opens up (similar to those old school vinyl coin purses from the 1970's) easily to get access to the inside.

  ** S.H.A.D.O. Pack 24L

  SOFT GOODS

  A fully loaded, mid-size, adventure pack that effectively delivers a ruggedized, streamlined, best in class package designed to perform in a multitude of environments and use cases, both off and on the grid.  The dual zipper opening design allows for optimal storage access to two compartments, and includes numerous accessories for a high degree of user options to organize EDC items.  This updated Gen2 version now features a full volume main compartment tub, lowpro laptop/hydration bladder 2ndary pocket, improved stretch water bottle pocket fabric, and updated lumbar pad and retention system.  #shadopack

  [[https://prometheusdesignwerx.com/products/s-h-a-d-o-pack-24l-ranger-green-1][Learn More]]

  ** Watch Accessories

  ACCESSORIES

  PDW has been a long time fan of rugged, purpose driven timepieces.  These instruments have a long storied history with adventurers and those intrepid men and women who have stepped into dangerous places.  We have designed and created numerous next level [[https://prometheusdesignwerx.com/collections/watch-accessories][*accessories*]] to customize your favorite tool watch.  From a collection of watch straps, all featuring titanium hardware, to the original [[https://prometheusdesignwerx.com/collections/compasses][*Expedition Watch Band Compass Kit*]], which has set the high standard from beginning, and from where all others follow.

  [[https://prometheusdesignwerx.com/collections/watch-accessories][Learn More]]

  PDW has been a long time fan of rugged, purpose driven timepieces.  These instruments have a long storied history with adventurers and those intrepid men and women who have stepped into dangerous places.  We have designed and created numerous next level [[https://prometheusdesignwerx.com/collections/watch-accessories][*accessories*]] to customize your favorite tool watch.  From a collection of watch straps, all featuring titanium hardware, to the original [[https://prometheusdesignwerx.com/collections/compasses][*Expedition Watch Band Compass Kit*]], which has set the high standard from beginning, and from where all others follow.

  ** Ti-FST & Ti-1HSU

  EDC TOOLS

  The Ti-FST and Ti-1HSU are precision machined titanium EDC tools for wilderness survival.  Each is available separately or combined together for part of a compact, fully self-contained survival fire making kit.  The Ti-FST is a 2-compartment stash tube designed to store fire making materials and even a pencil sharpener for making tinder shavings.  The Ti-1HSU is a 1-handed sparking unit designed to light a life saving fire with only 1 hand if neccessary.  Both items are expertly made and thoughfully engineered.  #tifst #ti1hsu

  [[https://prometheusdesignwerx.com/collections/edc-tools][Learn More]]

  ** Versa Bear

  EDC ACCESSORIES

  The PDW Versa Bear™ is a happy, bear-shaped, re-usable, TSA carry-on approved 2.7oz/80ml volume, food grade, adventure & travel, silicone squeeze bottle.  Secure flip-top cap is label ready.  Comes in a handy 3-Pack.  These non-toxic squeeze bottles are perfect for your next backpacking trip or spontaneous weekend get-away.  Where in the world will you take Versa Bear™?  #versabear

  [[https://prometheusdesignwerx.com/products/versa-bear-2][Learn More]]

  The PDW Versa Bear™ is a happy, bear-shaped, re-usable, TSA carry-on approved 2.7oz/80ml volume, food grade, adventure & travel, silicone squeeze bottle.  Secure flip-top cap is label ready.  Comes in a handy 3-Pack.  These non-toxic squeeze bottles are perfect for your next backpacking trip or spontaneous weekend get-away.  Where in the world will you take Versa Bear™?  #versabear

  ** DRB Scout Knife RL

  EDC TOOLS

  Our newest DRB Scout Knife RL features a total of 8 tools, making this one versatile and capable multi-bladed slipjoint for the campsite and EDC. The addition of the wood saw makes this knife more bushcrafty in usability, and it even features a hobo fork for you know, just in case you want to eat that corned beef, baked beans, once you've opened the can, or a trailside slice of apple.  #drbscoutknife

  [[https://prometheusdesignwerx.com/collections/folders][Learn More]]

  ** Danger Ranger Bear: Adventure Is Out There

  [[https://prometheusdesignwerx.com/pages/danger-ranger-bear-1][Learn More]]

  Danger Ranger Bear is our resident, virtual campsite host, camp counsellor, and wilderness guide.  He is here to share the how to's, what's, why's, do's, and don'ts for your next outdoor adventure.  Danger Ranger Bear encourages you to be a friend to the wilderness when you get the call, and to the woodland creatures big or small.  He wants you to be prepared, be ready, face the challenges, plan for risks, thrill in the journey, and to not die dumb.  No adventure big or small was ever great, without a bit of danger.

  Look for the DRB logo on exclusive products in the PDW website to purchase, use or wear and show off that you're no longer an ignorant, doughy tenderfoot.  Take the moose by the horns (actually a really terrible idea, DRB does not suggest that you do this but it was a play on another ol' idiom), turn that hipster beard into mountainman scruff, lace up those hiking boots, hit the trail, walk as tall as Paul Bunyan, tune in with nature like John Muir, and be rough and ready as Jeremiah Johnson.  #dangerrangerbear
#+end_quote
