:PROPERTIES:
:ID:       e18e4d16-ba82-4646-a9dd-ff301921c924
:ROAM_REFS: https://srfi.schemers.org/srfi-216/
:END:
#+title: (srfi.schemers.org) SICP Prerequisites (Portable)
#+filetags: :website:

#+begin_quote
  * SRFI 216: SICP Prerequisites (Portable)

  by Vladimir Nikishkin

  status: /final/ (2021-01-21)

  keywords: [[https://srfi.schemers.org/?keywords=sicp][SICP]]

  See also [[https://srfi.schemers.org/srfi-203/][SRFI 203: A Simple Picture Language in the Style of SICP]].

  - [[https://srfi.schemers.org/srfi-216/srfi-216.html][The SRFI Document]]

  - [[https://srfi-email.schemers.org/srfi-216/][Discussion Archive]]

  - [[https://github.com/scheme-requests-for-implementation/srfi-216][Git repo (on GitHub)]]

  - [[mailto://srfi-216@srfi.schemers.org][srfi-216@nospamsrfi.schemers.org (subscribers only)]]

  ** Abstract

  This SRFI follows [[https://srfi.schemers.org/srfi-203/][SRFI 203]] in providing "out-of-the-box" support for hosting the exercises suggested by [[https://mitpress.mit.edu/sites/default/files/sicp/index.html][Structure and Interpretation of Computer Programs]] in portable Scheme.

  Whereas SRFI 203 focused on the necessarily non-portable aspects of the problem set (the graphics), this SRFI aims to provide support for the rest of the features, which are far more widespread, often already provided, and in reality mostly need just a common vocabulary.

  This SRFI provides procedures for working with time data, multi-threading, and streams, as well as SICP names for =true= and =false=.

  None of these procedures is fit for production use.  They are only designed for pedagogical purposes.

  Students, however, are expected to be able to just write

  #+begin_src scheme
    (include (srfi sicp))
  #+end_src

  and have the code from the book run without problems (apart from those intended by the book authors).
#+end_quote
