:PROPERTIES:
:ID:       0e402b5f-5ded-4174-8563-0535dac22351
:ROAM_REFS: https://startacomputer.club/
:END:
#+title: (startacomputer.club) START A COMPUTER CLUB
#+filetags: :social:website:

#+begin_quote
  * OU SHOULD START A COMPUTER CLUB IN THE PLACE THAT YOU LIVE

  #+begin_src notranslate :dir ltr :lang eo
                ,---------------------------,
                |  /--------------------- |
                | | LASTA NOVAĴO:         | |
                | | VI DEVUS ESTABLI      | |
                | | KOMPUTILAN KLUBON     | |
                | | EN LA LOKO,           | |
                | | KIE VI LOĜAS          | |
                |  _____________________/  |
                |___________________________|
              ,---_____     []     _______/------,
            /         /______________          /|
          /___________________________________ /  | ___
          |                                   |   |    )
          |  _ _ _                 [-------]  |   |   (
          |  o o o                 [-------]  |  /    _)_
          |__________________________________ |/     /  /
      /-------------------------------------/|      ( )/
    /-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/ /
  /-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/ /
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  #+end_src

  /i'm glad someone finally said it/

  ** WHAT IS A COMPUTER CLUB?

  a computer club is where a group of people hang out and do computer together

  ** WHAT IS "DOING COMPUTER"?

  doing computer is whatever you want...on computers, together. our bias is towards programming and diy shared computing infrastructure. but there's also art and music and open data science and circuit-bending and a million other things we don't know about

  ** WHY SHOULD I START A COMPUTER CLUB?

  the political economy of computing is awful. have you read [[https://bookwyrm.social/book/525851/s/palo-alto][palo alto]]? me neither. we should read it. we deserve better than the darpa-funded visions of xerox parc technologists

  make the political economy of computing less awful and bring it home to you and yours by starting a computer club in the place that you live

  ** RULES

  we can't make you do anything, so do whatever you want. but these are the things we think are really important

  - *hang out in real life:* online has rude vibes, real life has kinder vibes. hang out in real life for trust and strength and to ground your computer club in your actual local context
  - *reject corporate sponsorship:* corporate sponsorship constrains behavior and undermines collective ownership. computer club isn't yours if a corporate sponsor might get upset by something you do
  - *computer club is a collective project:* you don't need a mission statement, but you might have an ethos that defines your computer club. computer club is beholden only to that ethos and the people who show up

  ** GUIDELINES

  we still can't make you do anything, so continue doing whatever you want. but these are things we think are important to think about

  - computing is political, so let computer club be political too
  - the [[https://www.recurse.com/social-rules][ recurse center social rules]] foster collaboration and psychological safety, consider using them
  - be inspired by permaculture
  - be inspired by small web
  - be inspired by diy culture
  - be inspired by computing as a medium through which better things are possible
  - try to host computer club's stuff on your own computers in the place that you live
  - be open to interdisciplinary computing
  - be open to different histories and "skill levels" with computing

  ** HOW SHOULD I START THE COMPUTER CLUB

  there are lots of ways to start a computer club; how you start will be unique to yours. but you could try

  - talk about what used to excite you about doing computer. talk about how the political economy of computing could be better. talk about these things publicly. the computer club might already be breathing in the communities you're in
  - attend preexisting computing meetups and find like-minded people. meetups about "how to node.js apolitically" are sidelining people who want "how to node.js pro-socially." don't try to be a recruiter -- just be excited at events and find people who are also excited
  - does your city have a food coop? food coops and computer clubs have a similar ethos; and food coops are a great place to get your food for the same reasons that a computer club is a great place to do computer. make friends at your food coop and find the computer-doers
  - join a project or start a project and talk to people there about starting a computer club. are you or someone you know doing
    - web design for a diy venue? work together!
    - technical support for a cool local project? work together!
    - communications for your neighborhood's nascent mesh network? work together!
    - analysis for local open data projects? work together!
  - talk to existing computer clubs!

  ** COMPUTER CLUBS AND SIMILAR THINGS THAT WE KNOW OF

  - [[https://cyberia.club/][cyberia computer club]]
  - [[https://www.ccc.de/][chaos computer club]]
  - [[https://bunk.computer/][bunk computer club]] (now co-op)
  - [[https://deuxfleurs.fr/][deuxfleurs]]
  - [[https://lurk.org/][LURK]]
  - [[https://plover.digital/][plover digital]]
  - [[https://sdf.org/][SDF]]
  - computer clubs are inspired by [[https://en.m.wikipedia.org/wiki/Category:Hackerspaces][hackerspaces]]
  - [coming soon] your computer club!

  ** TOOLS THAT ARE USEFUL FOR A COMPUTER CLUB

  - computers (personal computers)
  - computers (servers)
  - computers (people doing computer)
  - *chat:* delta chat, matrix, zulip, mattermost, signal, discord
  - love and trust!
  - the [[https://www.recurse.com/social-rules][ recurse center social rules]]
  - a git forge (we like forgejo)
  - a physical tilde server (it can motivate everyone to create something together)
  - *locations:* living rooms, libraries, a cool local bookstore
  - *mob programming:* a big monitor, tv, or a projector. computing together is fun and contributes to your computer club's culture!
  - [[https://awesome-selfhosted.net/][a very thorough resource for collective computing infrastructure]]
  - connections to other local projects
  - /connections to other local projects/
  - /*connections to other local projects*/

  ** WHAT NOW?

  go! find the computer club! make the computer club! tell us about it!
#+end_quote
