:PROPERTIES:
:ID:       794059b6-fb27-4ef1-9fc0-3bbd2701f523
:ROAM_REFS: https://store.steampowered.com/app/1859280/7_Days_to_End_with_You/
:END:
#+title: (store.steampowered.com) 7 Days to End with You on Steam
#+filetags: :store:software:games:website:

#+begin_quote
  ** About This Game

  You don't know a single word in the language of this world.
  Deduce the meanings of words the person before you uses to communicate with you.
  Then try to understand them like a puzzle, one piece at a time.
  You are free to perceive the meaning of the words you read.

  The relationship between the two characters is built on the words you interpret.
  And their story is also built on the words you interpret.

  Their world changes according to your understanding.
  Maybe their story is a short, ordinary story, or maybe it's a long, peculiar story.
  Or both stories could exist at the same time.  There's nothing wrong with that.

  The story is only complete with your interpretation.
  So certainly, every story your interpretation results in is correct.
  Even if you don't understand the story at first, you have the opportunity to repeat it over and over again.

  This is a short and long story, of only seven days.
#+end_quote
