:PROPERTIES:
:ID:       32777110-8e41-4669-8641-464844058e8c
:ROAM_REFS: https://susam.github.io/devil/
:END:
#+title: (susam.github.io) Devil Mode
#+filetags: :lisp:emacs:software:website:

#+begin_quote
  Devil mode trades your comma key in exchange for a modifier-free editing experience in [[id:aca1324c-b142-4e34-a121-a8bb0a79ddf8][Emacs]].  Yes, the comma key!  The key you would normally wield for punctuation in nearly every corner of text.  Yes, this is twisted!  It would not be called the Devil otherwise, would it?  If it were any more rational, we might call it something divine, like, uh, the [[id:b5d3b275-82a8-4906-b87f-a83c31e64c5a][God mode]]?  But alas, there is nothing divine to be found here.  Welcome, instead, to the realm of the Devil!  You will be granted the occasional use of the comma key for punctuation, but only if you can charm the Devil.  But beware, for in this sinister domain, you must relinquish your comma key and embrace an editing experience that whispers wicked secrets into your fingertips!
#+end_quote
