:PROPERTIES:
:ID:       91423fd6-9107-4e98-a427-44029f026891
:ROAM_REFS: https://systemd.io/
:END:
#+title: (systemd.io) System and Service Manager
#+filetags: :linux:unix:operating_systems:software:website:

#+begin_quote
  System and Service Manager

  [[id:c45f0bda-cf14-42d4-b777-895fa0d43e49][systemd]] is a suite of basic building blocks for a [[id:bf0bc2d7-17df-413c-823b-93904faffc58][Linux]] system.  It provides a system and service manager that runs as PID 1 and starts the rest of the system.
  systemd provides aggressive parallelization capabilities, uses socket and D-Bus activation for starting services, offers on-demand starting of daemons, keeps track of processes using Linux control groups, maintains mount and automount points, and implements an elaborate transactional dependency-based service control logic.  systemd supports SysV and LSB init scripts and works as a replacement for sysvinit.
  Other parts include a logging daemon, utilities to control basic system configuration like the hostname, date, locale, maintain a list of logged-in users and running containers and virtual machines, system accounts, runtime directories and settings, and daemons to manage simple network configuration, network time synchronization, log forwarding, and name resolution.
#+end_quote
