:PROPERTIES:
:ID:       4ead5528-8859-449a-8cd0-9dea20bdadcd
:ROAM_REFS: https://turingcomplete.game/
:END:
#+title: (turingcomplete.game) Turing Complete
#+filetags: :computer_science:games:website:

#+begin_quote
  ** About this game

  Turing Complete is a game about computer science.  If you enjoy the thrill of figuring things out and those moments where a deeper perspective is revealed about something you thought you understood, this game is for you.

  [[https://store.steampowered.com/app/1444480/Turing_Complete/][Play Turing Complete]]

  ** What you learn

  *** LOGIC GATES

  Logic gates are the fundamental building blocks of computation.  Given only a *nand gate* you create the rest.

  *** COMPONENTS

  Building on logic gates and introducing memory, more complex constructions are possible.

  *** ARCHITECTURE

  Assemble your components into real computers.  *Turing complete* computers are the gold standard, Turing complete meaning a computer that is capable of computing the same algorithms as a Turing machine.

  *** ASSEMBLY

  Computers are programmed with binary codes.  Create assembly instructions to simplify this and solve programming puzzles on your own hardware.
#+end_quote
