:PROPERTIES:
:ID:       d10ae902-ab0e-4971-a4a9-d10faac1c0f4
:ROAM_REFS: https://wiki.c2.com/
:END:
#+title: (wiki.c2.com) Welcome Visitors
#+filetags: :programming:software_development:www:website:

WikiWikiWeb, the original [[id:b99c6a7c-958b-4d70-8900-9162b935c574][Wiki]].

#+begin_quote
  Welcome to the WikiWikiWeb, also known as "Wiki".  A lot of people had their first wiki experience here.  This community has been around since 1995 and consists of many people.  We always accept newcomers with valuable contributions.  If you haven't used a wiki before, be prepared for a bit of CultureShock.  The usefulness of Wiki is in the freedom, simplicity, and power it offers.
  This site's primary focus is PeopleProjectsAndPatterns in SoftwareDevelopment.  However, it is more than just an InformalHistoryOfProgrammingIdeas.  It started there, but the theme has created a culture and DramaticIdentity all its own.  All Wiki content is WorkInProgress.  Most of all, this is a forum where people share ideas!  It changes as people come and go.  Much of the information here is subjective.  If you are looking for a dedicated reference site, try WikiPedia; WikiIsNotWikipedia!
#+end_quote
