:PROPERTIES:
:ID:       0e3f16ad-33a5-42ce-9d4c-210e96359d56
:ROAM_REFS: http://wiki.c2.com/?WikiHistory
:END:
#+title: (wiki.c2.com) Wiki History
#+filetags: :information_management:www:website:

#+begin_quote
  * Wiki History

  This began on March 25, 1995.  A little later (May 1, 1995), an [[http://wiki.c2.com/?InvitationToThePatternsList][InvitationToThePatternsList]] caused an increase in participation.  Growth has continued since then, to the point where the average number of new pages ranges between 5 and 12 per day.

  [[http://wiki.c2.com/?WardsWikiTenthAnniversary][WardsWikiTenthAnniversary]] occurred on March 25, 2005.  At that time, we had about 30690 pages.

  This is the first ever wiki site, founded as an automated supplement to the [[http://wiki.c2.com/?PortlandPatternRepository][PortlandPatternRepository]].  The site was immediately popular within the pattern community, largely due to the newness of the Internet and a good slate of [[http://wiki.c2.com/?InvitedAuthors][InvitedAuthors]].  The site was, and remains, dedicated to [[http://wiki.c2.com/?PeopleProjectsAndPatterns][PeopleProjectsAndPatterns]].

  I created the site and the [[http://wiki.c2.com/?WikiWikiWeb][WikiWikiWeb]] machinery that operates it.  I chose wiki-wiki as an alliterative substitute for quick and thereby avoided naming this stuff quick-web.  Read more about etymology here: [[http://c2.com/doc/etymology.html]].  An early page, [[http://wiki.c2.com/?WikiWikiHyperCard][WikiWikiHyperCard]], traces wiki ideas back to a [[http://wiki.c2.com/?HyperCard][HyperCard]] stack I wrote in the late 80's.  This same stack, by the way, spawned [[http://wiki.c2.com/?CrcCards][CrcCards]].  I've reconstructed the [[http://wiki.c2.com/?WikiDesignPrinciples][WikiDesignPrinciples]] I applied at the time.  Read more on the name here: [[http://c2.com/doc/etymology.html]].

  [[http://wiki.c2.com/?PatrickMueller][PatrickMueller]] wrote probably the first [[http://wiki.c2.com/?WikiWikiClone][WikiWikiClone]], choosing the [[http://wiki.c2.com/?RexxLanguage][RexxLanguage]] as a convenient vehicle for a night's work.  I soon wrote a version of wiki that could host its own source code and announced [[http://wiki.c2.com/?WikiWikiGoesPublic][WikiWikiGoesPublic]].  Rather than fold changes back into my editable version, implementers chose to distribute their modifications on their own sites and boast of the many features they had added, accepting raw HTML being the most common one.

  It has been claimed by some that the ideas that led to the Wiki concept have their origins (see: [[http://wiki.c2.com/?WikiWikiOrigin][WikiWikiOrigin]]) in the ZOG database system effort, first materialized at Carnegie-Mellon University in 1972.
#+end_quote
