:PROPERTIES:
:ID:       57a86978-a3b1-42c6-a36a-9df4bf34076e
:ROAM_REFS: https://www.pcgamer.com/seasoned-rpg-devs-from-obsidian-and-bioware-blame-the-temporary-death-of-the-isometric-crpg-on-vibes-based-forecasting-from-retailers/
:END:
#+title: (www.pcgamer.com) Seasoned RPG devs from Obsidian and BioWare blame the temporary death of the isometric CRPG on 'vibes-based forecasting' from retailers | PC Gamer
#+filetags: :opinion:games:news:website:

#+begin_quote
  "I can't stress enough how often I'd hear a retail rep declare a genre/style/look was dead with zero supporting data."

  [[id:1fb5644a-e77c-43b0-82af-4f2a4c0c852d][Game]] developer veterans from RPG companies like Obsidian and BioWare say that the temporary death of the CRPG in the early 2000s was down to retailer meddling, as outlined in a series of tweets made just before the holidays.
  As spotted by GamesRadar, a conversation between Nathaniel Chapman and Josh Sawyer began to discuss the former role that retail giants played in the life and death of game genres.  Chapman is a designer at Timberline with former credits at Blizzard and Obsidian, while Sawyer is a studio design director at Obsidian—having worked on games like Pillars of Eternity and Icewind Dale.
  "I completely forgot how big a deal it was for Best Buy/Walmart/etc. buyers to see your game which determined your shelf space and thus your sales," wrote Chapman, to which Sawyer noted that Walmart had been "prudish" about content in the past—while hypocritically clearing the shelves for GTA.
  Chapman added: "I think the worst thing was the self-fulfilling vibes about a certain genre or mechanic or whatever not selling well, so the retailers wouldn't stock games with it."  Eventually, a commenter asked Sawyer for specifics—which he outlined in a follow-up thread.
#+end_quote
⋮
#+begin_quote
  According to Sawyer, it was a snake-eating-its-own-tail situation: "I can't stress enough how often I'd hear a retail rep declare a genre/style/look was dead with zero supporting data.  Truly vibes-based forecasting, which resulted in self-fulfilling prophecies."
#+end_quote
⋮
#+begin_quote
  David Gaider chimed in with something to this effect.  Gaider is the co-founder and Creative Director at Summerfall Games—and a former narrative designer at BioWare who worked extensively on the Dragon Age series as its lead writer.
  "It wasn't just retailers," Gaider wrote.  "There's an 'industry wisdom' which creeps into dev teams where some things are simply declared dead or too old-fashioned, and there's no opposing this certainty up until someone else comes along and proves it's 100% untrue."
#+end_quote
