:PROPERTIES:
:ID:       a8c474b7-74c8-408e-a3fb-0d1571f5aa51
:ROAM_REFS: https://www.vim.org/scripts/script.php?script_id=2531
:END:
#+title: (www.vim.org) slimv.vim - Superior Lisp Interaction Mode for Vim ('SLIME for Vim') : vim online
#+filetags: :development_environment:software_development:lisp:vim:website:

#+begin_quote
  slimv.vim : Superior Lisp Interaction Mode for Vim ('SLIME for Vim')

  *script karma* | Rating *996/284*, Downloaded by 19776 | *Comments, bugs, improvements* | [[http://vim.wikia.com/wiki/Script:2531][Vim wiki]]

  created by
  Tamas Kovacs

  script type
  utility

  description
  Slimv is a SWANK client for Vim, similarly to SLIME for Emacs.  SWANK is a TCP server for Emacs, which runs a Common Lisp, Clojure or Scheme REPL and provides a socket interface for evaluating, compiling, debugging, profiling lisp code.  The SWANK server is embedded in Slimv, but you can also use your own SWANK installation.

  Slimv opens the lisp REPL (Read-Eval-Print Loop) inside a Vim buffer.  Lisp commands may be entered and executed in the REPL buffer, just as in a regular REPL.

  Slimv supports SLIME's debugger, inspector, profiler, cross reference, arglist, indentation, symbol name completion functions.  The script also has a Common Lisp Hyperspec lookup feature and it is able to lookup symbols in the Clojure API, as well as in JavaDoc.

  Slimv comes with Paredit Mode, which is similar to the functionality of paredit.el in Emacs.  Paredit Mode tries to maintain the balanced state of matched characters (parenthesis marks, square and curly braces, double quotes). Matched characters are inserted and removed in pairs, also when working with a block of text (well, mostly). Slimv also implements many paredit.el s-expression handling functions, like Split/Join/Wrap/Splice/Raise.  Slurpage and Barfage known from Emacs is also possible but in a different fashion: you don't move the list element in or out of the list, rather you move the opening or closing parenthesis over the element or sub-list.

  Please visit the Slimv Tutorial for a more complete introduction:
  [[https://kovisoft.bitbucket.io/tutorial.html]]

  Please find the most recent development version in the repository:
  [[https://github.com/kovisoft/slimv]]
#+end_quote
