:PROPERTIES:
:ID:       18cf776a-0540-4561-9e6d-03eef416fe2f
:ROAM_REFS: https://www.amazon.com/dp/0262019345
:END:
#+title: (www.amazon.com) Functional Differential Geometry (Mit Press): Sussman, Gerald Jay, Wisdom, Jack, Farr, Will: 9780262019347: Amazon.com: Books
#+filetags: :physics:mathematics:books:website:

#+begin_quote
  * Functional Differential Geometry (Mit Press) Illustrated Edition

  by [[https://www.amazon.com/Gerald-Jay-Sussman/e/B000APF94M/ref=dp_byline_cont_book_1][Gerald Jay Sussman]] (Author), [[https://www.amazon.com/s/ref=dp_byline_sr_book_2?ie=UTF8&field-author=Jack+Wisdom&text=Jack+Wisdom&sort=relevancerank&search-alias=books][Jack Wisdom]] (Author), [[https://www.amazon.com/s/ref=dp_byline_sr_book_3?ie=UTF8&field-author=Will+Farr&text=Will+Farr&sort=relevancerank&search-alias=books][Will Farr]] (Contributor) [[https://www.amazon.com/dp/0262019345][& 0 more]]

  An explanation of the mathematics needed as a foundation for a deep understanding of general relativity or quantum field theory.

  Physics is naturally expressed in mathematical language.  Students new to the subject must simultaneously learn an idiomatic mathematical language and the content that is expressed in that language.  It is as if they were asked to read Les Misérables while struggling with French grammar.  This book offers an innovative way to learn the differential geometry needed as a foundation for a deep understanding of general relativity or quantum field theory as taught at the college level.

  The approach taken by the authors (and used in their classes at MIT for many years) differs from the conventional one in several ways, including an emphasis on the development of the covariant derivative and an avoidance of the use of traditional index notation for tensors in favor of a semantically richer language of vector fields and differential forms.  But the biggest single difference is the authors' integration of computer programming into their explanations.  By programming a computer to interpret a formula, the student soon learns whether or not a formula is correct.  Students are led to improve their program, and as a result improve their understanding.
#+end_quote
