:PROPERTIES:
:ID:       80d8d42d-e264-43d3-bda1-3904cd2263cd
:ROAM_REFS: https://www.amazon.com/dp/0262545748
:END:
#+title: (www.amazon.com) Certified Programming with Dependent Types: A Pragmatic Introduction to the Coq Proof Assistant: Chlipala, Adam: 9780262545747: Amazon.com: Books
#+filetags: :mathematics:rocq_lang:documentation:books:website:

#+begin_quote
  A handbook to the Coq software for writing and checking mathematical proofs, with a practical engineering focus.

  The technology of mechanized program verification can play a supporting role in many kinds of research projects in computer science, and related tools for formal proof-checking are seeing increasing adoption in mathematics and engineering.  This book provides an introduction to the Coq software for writing and checking mathematical proofs.  It takes a practical engineering focus throughout, emphasizing techniques that will help users to build, understand, and maintain large Coq developments and minimize the cost of code change over time.

  Two topics, rarely discussed elsewhere, are covered in detail: effective dependently typed programming (making productive use of a feature at the heart of the Coq system) and construction of domain-specific proof tactics.  Almost every subject covered is also relevant to interactive computer theorem proving in general, not just program verification, demonstrated through examples of verified programs applied in many different sorts of formalizations.  The book develops a unique automated proof style and applies it throughout; even experienced Coq users may benefit from reading about basic Coq concepts from this novel perspective.  The book also offers a library of tactics, or programs that find proofs, designed for use with examples in the book.  Readers will acquire the necessary skills to reimplement these tactics in other settings by the end of the book.  All of the code appearing in the book is freely available online.
#+end_quote
