:PROPERTIES:
:ID:       ef64daf8-97be-427a-ad7b-03794125df9a
:ROAM_REFS: https://www.johnsymons.net/wp-content/uploads/2018/09/Understanding-error-rates-.pdf
:END:
#+title: (www.johnsymons.net) Microsoft Word - Understanding error rates submitted version .docx - Understanding-error-rates-.pdf
#+filetags: :programming:software_development:science_paper:article:mime_type_application_pdf:website:

#+begin_quote
  * Understanding error rates in software engineering: Conceptual, empirical, and experimental approaches

  Jack K Horner and John Symons

  University of Kansas

  ** Abstract

  Software-intensive systems are ubiquitous in the industrialized world.  The reliability of software has implications for how we understand scientific knowledge produced using software-intensive systems and for our understanding of the ethical and political status of technology.  The reliability of a software system is largely determined by the distribution of errors and by the consequences of those errors in the usage of that system.  Here we argue that even in software that is developed in accordance with the best practices of contemporary software engineering, various kinds of error in software occur at the empirically observed average rate of about one error per hundred lines of code.  We compare the taxonomies of empirically observed software error rates reported in the published literature with Giuseppe Primiero's (2014) taxonomy of error in information systems.  The goal of such comparisons is to discover taxonomies that help to reduce the software error rate in practice.
#+end_quote
