:PROPERTIES:
:ID:       f7bc6c13-2f78-41f2-b8fa-c89b7b333f79
:ROAM_REFS: https://www.pearson.com/en-us/subject-catalog/p/introduction-to-robotics-mechanics-and-control/P200000003304/9780137848744
:END:
#+title: (www.pearson.com) Introduction to Robotics: Mechanics and Control
#+filetags: :robotics:engineering:books:website:

#+begin_quote
  For senior-year undergraduate and first-year graduate courses in robotics.
  *An intuitive introduction to robotic theory and application*
  Since its original publication in 1986, Craig’s Introduction to Robotics: Mechanics and Control has been the leading textbook for teaching robotics at the university level.  Blending traditional mechanical engineering material with computer science and control theoretical concepts, the text covers a range of topics, including rigid-body transformations, forward and inverse positional kinematics, velocities and Jacobians of linkages, dynamics, linear and non-linear control, force control methodologies, mechanical design aspects, and robotic programming.
  The 4th Edition features a balance of application and theory, introducing the science and engineering of mechanical manipulation—establishing and building on foundational understanding of mechanics, control theory, and computer science.  With an emphasis on computational aspects of problems, the text aims to present material in a simple, intuitive way.
#+end_quote
