:PROPERTIES:
:ID:       00505f70-0918-4cda-b24e-0eebcd2a8371
:ROAM_REFS: https://www.amazon.com/dp/173210221X
:END:
#+title: (www.amazon.com) A Philosophy of Software Design, 2nd Edition: Ousterhout, John: 9781732102217: Amazon.com: Books
#+filetags: :textbooks:software_development:programming:computer_science:books:website:

#+begin_quote
  * A Philosophy of Software Design, 2nd Edition Paperback -- July 26, 2021

  by [[https://www.amazon.com/John-Ousterhout/e/B000APICQY/ref=dp_byline_cont_book_1][John Ousterhout]] (Author)

  This book addresses the topic of software design: how to decompose complex software systems into modules (such as classes and methods) that can be implemented relatively independently.  The book first introduces the fundamental problem in software design, which is managing complexity.  It then discusses philosophical issues about how to approach the software design process and it presents a collection of design principles to apply during software design.  The book also introduces a set of red flags that identify design problems.  You can apply the ideas in this book to minimize the complexity of large software systems, so that you can write software more quickly and cheaply.
#+end_quote
