:PROPERTIES:
:ID:       3b9138c4-07ae-4742-a7f5-9d52c27c29ab
:ROAM_REFS: https://www.minetest.net/
:END:
#+title: (www.minetest.net) Minetest | Open source voxel game engine
#+filetags: :open_source:games:minecraft:software:website:

#+begin_quote
  An open source voxel game engine.  Play one of our many games, mod a game to your liking, make your own game, or play on a multiplayer server.
#+end_quote
* See Also
** (en.wikipedia.org) Minetest - Wikipedia :games:open_source:software:minecraft:website:
:PROPERTIES:
:ID:       ecf4f908-a407-480f-a30f-cbcd0938766e
:ROAM_REFS: https://en.wikipedia.org/wiki/Minetest
:END:

#+begin_quote
  Minetest is a free and open-source voxel game creation system.  It is written primarily in C++ and makes use of the Irrlicht Engine.  Minetest provides a Lua API allowing users to write their own games and mods.  It is cross-platform, being available for Microsoft Windows, macOS, Linux, some BSD descendants, some GNU variants and Android.
  An in-game browser lets users download games and modifications from the ContentDB website.  The five most popular games by downloads are VoxeLibre, Minetest Game, NodeCore, Tutorial and Subway Miner.
  Over a decade of active development Minetest has garnered critical acclaim and gained in popularity; the games, mods and texturepacks on ContentDB have over 12 million downloads combined, and the Android version of Minetest has over a million downloads on the Google Play store.
#+end_quote
