:PROPERTIES:
:ID:       f1ccd506-3a34-48b8-aa11-2e3cbf6dde42
:ROAM_REFS: https://www.wired.com/2016/03/doug-lenat-artificial-intelligence-common-sense-engine/
:END:
#+title: (www.wired.com) One Genius' Lonely Crusade to Teach a Computer Common Sense | WIRED
#+filetags: :artificial_intelligence:article:news:website:

#+begin_quote
  * One Genius' Lonely Crusade to Teach a Computer Common Sense

  For decades, as the tech world passed him by, Doug Lenat has fed computers millions of rules for daily life.  Is this the way to artificial common sense?

  Mary Shepherd and Doug LenatBrent Humphries for WIRED

  Over July 4th weekend in 1981, several hundred game nerds gathered at a banquet hall in San Mateo, California.  Personal computing was still in its infancy, and the tournament was decidedly low-tech.  Each match played out on a rectangular table filled with paper game pieces, and a March Madness-style tournament bracket hung on the wall.  The game was called [[https://en.wikipedia.org/wiki/Traveller_(role-playing_game)][Traveller Trillion Credit Squadron]], a role-playing pastime of baroque complexity.  Contestants did battle using vast fleets of imaginary warships, each player guided by an equally imaginary trillion-dollar budget and a set of rules that spanned several printed volumes.  If they won, they advanced to the next round of war games---until only one fleet remained.

  Doug Lenat, then a 29-year-old computer science professor at nearby Stanford University, was among the players.  But he didn't compete alone.  He entered the tournament alongside [[https://en.wikipedia.org/wiki/Eurisko][Eurisko]], the [[https://www.wired.com/tag/artificial-intelligence][artificially intelligent]] system he built as part of his academic research.  Eurisko ran on dozens of machines inside Xerox PARC---the computer research lab just down the road from Stanford that gave rise to the graphical user interface, the laser printer, and so many other technologies that would come to define the future of computing.  That year, Lenat taught Eurisko to play Traveller.
#+end_quote
