:PROPERTIES:
:ID:       eeb5e745-09aa-4492-9b2e-8620d69e1ec3
:ROAM_REFS: https://www.pcjs.org/blog/2015/09/21/
:END:
#+title: (www.pcjs.org) Windows 95 In Your Web Browser | PCjs Machines
#+filetags: :emulator:microsoft_windows:blog_post:website:

#+begin_quote
  *** Windows 95 In Your Web Browser

  Today, the last serious bug preventing a successful boot of Windows 95 was fixed.  I won't bore you with the details.

  OK, I will: three arithmetic instructions (specifically, *AND*, *OR* and *XOR*) include a variation that converts an immediate signed byte into a signed word.  Those variations were failing to truncate the result when a 16-bit operand size was in effect, and if the destination was a register, the upper 16 bits of that register could become corrupted.

  The [[https://www.pcjs.org/software/pcx86/sys/windows/win95/4.00.950/][Windows 95 Test Machine]] hard disk has been updated with a complete set of Windows 95 files from a “Compact” installation, and first boot has finished, so instead of the initial “Getting ready to run Windows 95 for the first time...” splash screen, you'll see the normal Windows 95 startup screen.

  The machine is still a bit finicky.  It easily gets confused about the state of its shift keys if you switch away from the browser and then back again.  And Explorer windows don't open in the correct view; for example, both *My Computer* and *Recycle Bin* open the same (incorrect) view.  In short, there are still some serious bugs to be resolved, but booting has been achieved.

  The adventure continues.

  [[https://github.com/jeffpar][Jeff Parsons]]

  Sep 21, 2015
#+end_quote
* See Also
** [[id:536b9bc0-81a9-4e8e-a241-bdb8012edac4][(www.pcjs.org) Microsoft Windows 95: First Retail Release | PCjs Machines]]
