:PROPERTIES:
:ID:       30ee9bcc-e7a1-4bf5-8288-9214aa227b2b
:ROAM_REFS: https://www.healthygamer.gg/about/guide
:END:
#+title: (www.healthygamer.gg) Dr. K's Guide to Mental Health
#+filetags: :psychology:mental_health:website:

#+begin_quote
  * Dr. K's Guide to Mental Health

  A tailored learning experience designed by Dr. K with over 180 videos, worksheets, glossaries and more.

  [[https://coaching.healthygamer.gg/checkout?source=products_services&module=bundle&ref=products_services][✨ Get the Guide ✨]]

  ** 180+ videos on Trauma, ADHD, Meditation, Anxiety, and Depression to empower your mental health journey.

  *** What's Included

  ** Trauma

  40+ videos

  Learn how past experiences shape us, the effects of trauma, and strategies for moving forward.

  ** ADHD & Doing Stuff

  40+ videos

  Understand the origins of thought, attention, and motivation, and how they influence action.

  ** Meditation

  20+ videos

  Explore 30+ practices, and the history, science, and metaphysics behind meditation.

  ** Anxiety

  30+ videos

  Understand the different origins of anxiety, its impacts, and how to manage it.

  ** Depression

  30+ videos

  Discover clinical and spiritual approaches to depression, sadness, and negative emotions.

  ** An Experience Tailored to You

  *** Recommended Videos

  Get personalized video recommendations based on your needs and interests.

  *** Learning Paths

  Explore curated paths on specific topics to deepen your understanding.

  *** Worksheets

  Use practical worksheets to enhance your learning and apply concepts IRL.

  [[https://coaching.healthygamer.gg/checkout?source=products_services&module=bundle&ref=products_services][✨ Get the Guide ✨]]

  ** Enhanced Learning Features


  *** Meditation Library

  *** Optimized for Mobile

  *** Chromecast Support

  *** Picture-in-Picture Mode

  *** Spanish Subtitles

  *** Skill Tree Mode

  [[https://coaching.healthygamer.gg/guide/index][Preview the Guide]]

  ** Start your journey

  FULL BUNDLE

  *** Dr. K's Guide to Mental Health

  All 180+ video chapters for a comprehensive approach to Trauma, ADHD, Meditation, Anxiety, and Depression

  +$150+ $120 USD

  ✨ Get the Guide ✨

  *** Trauma Module

  $30 USD

  *** ADHD Module

  $30 USD

  *** Meditation Module

  $30 USD

  *** Anxiety Module

  $30 USD

  *** Depression Module

  $30 USD

  *** Refund Policy

  If for any reason you are dissatisfied with Dr. K's Guide to Mental Health and would like a refund on your purchase, feel free to send an email to [[mailto://support@guide.healthygamer.gg][support@guide.healthygamer.gg]] with the subject line “Dr. K's Guide Refund” within 7 days of your purchase.  Please include a copy of your receipt, the Discord account name (Username#1234) and email that the purchase is associated with, and any comments or feedback about what was unsatisfactory.  Your refund will be credited back to your original form of payment.  Please note that donated amounts to the Healthy Gamer Foundation are NOT refundable.  Refunds take 5 - 7 business days to be processed.

  ** About Dr. K

  Alok Kanojia, MD, MPH, also known as “Dr. K,” is the world's foremost authority on mental health for the gaming community.  He is a graduate of Tufts University School of Medicine and did his psychiatric residency at Massachusetts General Hospital in Boston and McLean Hospital in Cambridge, Massachusetts.  A former Harvard Medical School instructor specializing in mental health for the gaming community, he is the president and cofounder of Healthy Gamer, a mental health platform that provides content, coaching, and community resources to help young people take control of their mental health and their lives.  A highly sought-after speaker and esports performance coach, he and his wife live in Texas, with their two young daughters who love video games.
#+end_quote
