:PROPERTIES:
:ID:       bbf8fd2c-1035-4a51-8389-4c472cd7c304
:ROAM_REFS: https://www.oreilly.com/library/view/information-architecture-4th/9781491913529/
:END:
#+title: (www.oreilly.com) Information Architecture, 4th Edition[Book]
#+filetags: :design:books:website:

#+begin_quote
  Information architecture (IA) is far more challenging—and necessary—than ever.  With the glut of information available today, anything your organization wants to share should be easy to find, navigate, and understand.  But the experience you provide has to be familiar and coherent across multiple interaction channels, from the Web to smartphones, smartwatches, and beyond.
  To guide you through this broad ecosystem, this popular guide—now in its fourth edition—provides essential concepts, methods, and techniques for digital design that have withstood the test of time.  UX designers, product managers, developers, and anyone involved in digital design will learn how to create semantic structures that will help people engage with your message.
#+end_quote
