:PROPERTIES:
:ID:       31db2bed-2f48-43fa-ae60-625b2e52e780
:ROAM_REFS: https://www.pcgamer.com/software/ai/microsoft-co-authored-paper-suggests-the-regular-use-of-gen-ai-can-leave-users-with-a-diminished-skill-for-independent-problem-solving-and-at-least-one-ai-model-seems-to-agree/
:END:
#+title: (www.pcgamer.com) Microsoft co-authored paper suggests the regular use of gen-AI can leave users with a 'diminished skill for independent problem-solving' and at least one AI model seems to agree | PC Gamer
#+filetags: :website:

#+begin_quote
  * Microsoft co-authored paper suggests the regular use of gen-AI can leave users with a 'diminished skill for independent problem-solving' and at least one AI model seems to agree

  By [[https://www.pcgamer.com/author/james-bentley/][James Bentley]] published March 14, 2025

  'Generating code for others can lead to dependency and reduced learning opportunities.'

  If you think that workers heavily reliant on generative AI may be less prepared to tackle questions that can't be succinctly answered by the machine, you may just be right.

  A [[https://www.microsoft.com/en-us/research/wp-content/uploads/2025/01/lee_2025_ai_critical_thinking_survey.pdf][recent paper]] from Microsoft and Carnegie researchers attempted to study generative AI's effects on "cognitive effort" from workers in a recent self-reported study.  In it, that paper says, "Used improperly, technologies can and do result in the deterioration of cognitive faculties that ought to be preserved"

  From 319 total workers who use generative AI tools like ChatGPT or Copilot for work at least once a week, studying 936 applicable "real-world GenAI tool use examples", participants share how they perform their work.  The study verified that critical thinking was primarily deployed to verify the quality of work, and as confidence in AI tools went up, critical thinking efforts went down alongside it.
#+end_quote
