:PROPERTIES:
:ID:       3621975c-4fda-4492-992f-5c61579001fd
:ROAM_REFS: https://www.system7.pl/easrfid-dual-frequency-abs-anti-theft-tag/?lang=en
:END:
#+title: (www.system7.pl) EAS+RFID Dual-Frequency ABS anti-theft tag - Tagi RFID NFC System 7
#+filetags: :hardware:electronics:inventory_management:security:store:website:

#+begin_quote
  * EAS+RFID Dual-Frequency ABS anti-theft tag

  1 June 2022

  *UHF RFID anti-theft clips available immediately.*

  RFID anti-theft clips in our offer.  We have expanded our warehouse range with interesting UHF RFID tags that also act as anti-theft clips.

  As you might expect, in the future, the traditional “blind” anti-theft (EAS) gates operating at 58kHz or 8.2MHz will be replaced by integrated RFID systems operating at UHF frequencies.

  This is due to many additional possibilities offered by the use of RFID tags also for this purpose.  Thanks to radio frequency identification, you can, for example, determine where in the supervised room a specific item is located, or whether it returned from the changing room to its place at a certain time.  In addition, you will check whether, after being taken from the shelf, it reached the cash register within a reasonable time, whether someone tries to take it out without paying, whether it is not necessary to deliver another item from the warehouse to the shelf or hanger, etc.

  And all this can be done discreetly, without stressing honest customers with “surveillance” elements of anti-theft systems of the old type.

  ** RFID anti-theft clips with UHF R6P and EAS chip – supervise and protect in a new way.

  This tag's designation is S5697E5-70x31x21.\\
  It is equipped with a modern UHF integrated circuit by Impinij, symbol R6P. This chip allows the identification of UHF RFID in the frequency range 860-925MHz.\\
  In addition, the “clip” has a built-in antenna for traditional EAS 58kHz anti-theft systems.\\
  Dimensions of the ABS housing: 70mm x 31mm x 21mm.\\
  The retail price of these tags is PLN 3.40 net / pc.\\
  Unit package 100 pcs.

  Anti-theft clips and detecting gates have dominated the anti-theft protection market for years, especially in the case of retail outlets.  If you enrich the traditional solution with new possibilities offered by RFID technology, you will open up completely new perspectives.  Admittedly, the built-in, additional RFID tag makes their price slightly higher.  However, thanks to this, you can take advantage of new and useful functions that make such a solution more attractive.  Especially if you are creating a completely new system and you do not have to use old EAS anti-theft gates.

  *To sum up, if you need wholesale supplies of any RFID / NFC tags, we can deliver them immediately from our warehouse in Bielsko-Biała.  We can also design and produce unusual tags especially for you.  [[https://www.system7.pl/contact/?lang=en][Contact us]].*
#+end_quote
