:PROPERTIES:
:ID:       bd814b4e-f8bd-49a3-8b8f-2dc0798ad3f2
:ROAM_REFS: https://www.caloes.ca.gov/office-of-the-director/operations/planning-preparedness-prevention/planning-preparedness/
:END:
#+title: (www.caloes.ca.gov) Planning & Preparedness | California Governor's Office of Emergency Services
#+filetags: :emergency_resource:government_site:website:

#+begin_quote
  Emergency planning and preparedness is the process of systematically preparing for future events such as major incidents or disasters. Plans are needed for responding to the impacts of disasters and to maintain business continuity while managing the crisis.

  Preparedness is a shared responsibility. It calls for the involvement of everyone — not just the government — in preparedness efforts. By working together, everyone can help keep California safe and help keep it resilient when disasters strike.

  The Cal OES Planning and Preparedness Branch develops and maintains state-level emergency plans and planning guidance for state and local agencies. We do this by working with the whole community including:

  - State Agencies
  - Local and Tribal Governments
  - Businesses and the Private Sector
  - Non-governmental Organizations
  - Federal Government
  - Members of the Public
#+end_quote
* (www.caloes.ca.gov) Family Readiness Guide - Cal_OES_Family_Readiness_GuideENG.pdf :mime_type_application_pdf:ATTACH:
:PROPERTIES:
:ID:       74d98317-237f-4afb-9409-33e47c581281
:ROAM_REFS: https://www.caloes.ca.gov/wp-content/uploads/Preparedness/Documents/Cal_OES_Family_Readiness_GuideENG.pdf
:END:
