:PROPERTIES:
:ID:       89421267-26f7-4f14-af99-a5f57c632157
:ROAM_REFS: https://www.gap-system.org/
:END:
#+title: (www.gap-system.org) GAP System for Computational Discrete Algebra
#+filetags: :software:computer_science:mathematics:website:

#+begin_quote
  GAP is a system for computational discrete algebra, with particular emphasis on Computational Group Theory.  GAP provides a [[id:b24601aa-09df-41e1-aa7e-25ead342db34][programming language]], a library of thousands of functions implementing algebraic algorithms written in the GAP language as well as large data libraries of algebraic objects.  See also the overview and the description of the mathematical capabilities.  GAP is used in research and teaching for studying groups and their representations, rings, vector spaces, algebras, combinatorial structures, and more.  The system, including source, is distributed freely.  You can study and easily modify or extend it for your special use.
  In July 2008, GAP was awarded the ACM/SIGSAM Richard Dimick Jenks Memorial Prize for Excellence in Software Engineering applied to Computer Algebra.
#+end_quote
