:PROPERTIES:
:ID:       d2006277-9ee5-47fa-8a47-749e4cb1e152
:ROAM_REFS: https://www.theverge.com/23316220/transcription-ai-otter-temi-how-to
:END:
#+title: (www.theverge.com) Find the best AI-powered app to transcribe your audio | The Verge
#+filetags: :artificial_intelligence:software:transcription:lists:reviews:website:

#+begin_quote
  * Find the best AI-powered app to transcribe your audio

  by [[https://www.theverge.com/authors/barbara-krasnoff][Barbara Krasnoff]]

  Updated Aug 28, 2024, 10:36 AM PDT

  [[https://www.theverge.com/authors/barbara-krasnoff][Barbara Krasnoff]] is a reviews editor who manages how-tos and various projects.  She's worked as an editor and writer (and occasional sci-fi author) for more years than she cares to admit to.  She can be found on Threads as @barbarask.

  Transcription apps have become an extremely useful way of keeping records.  These apps record and make text transcriptions of important conversations.  So, for example, when you're having an important conversation with a lawyer, a doctor, or your insurance company, it's really handy to be able to check exactly what was said later.  And, of course, it's vital for writers and journalists, who need to keep records of their interviews.

  For many years, there have been two types of transcription services available online: ones that use an AI engine and ones that use human transcribers.  The latter are usually much more accurate but are also considerably more expensive.  Recently, as AI transcriptions have become more precise, they have become more popular and available.

  What follows are short looks at some of the AI-powered transcription services available.  We've concentrated on apps that have a free version (or, at least, a free trial for new users) and that are priced for the individual rather than for organizations.

  But first, a note: the quality of transcription supplied by these apps can vary widely depending not only on the AI engine the app is using but also on the quality of your audio.  If there are a lot of voices talking at once, if there is a lot of background noise, if the speakers have accents unfamiliar to the AI tool — those can all serve to degrade the accuracy of the transcription.  So, a good idea is to try out a transcription service with a free or trial version first to see which works best for your particular needs.
#+end_quote
