:PROPERTIES:
:ID:       c1f3464c-5fc6-4685-b1ef-37dd95ad7597
:ROAM_REFS: https://www.socallinuxexpo.org/scale/17x/presentations/your-suite-open-source-security-linters
:END:
#+title: (www.socallinuxexpo.org) Your Suite of Open Source Security Linters | 17x
#+filetags: :programming:software_development:security:presentation:website:

#+begin_quote
  * Your Suite of Open Source Security Linters

  [[https://www.socallinuxexpo.org/scale/17x/speakers/eric-brown][Eric Brown]]

  Audience: [[https://www.socallinuxexpo.org/scale/17x/audience-level/developer][Developer]]

  Topic: [[https://www.socallinuxexpo.org/scale/17x/track/security][Security]]

  Ensuring code is secure is a difficult task.  Minimizing the security issues in software is a primary focus of most companies.  Many tools help assist in the testing of software to ensure security issues are flushed out.  This includes, but is not limited to, linters, API scanners, fuzzers, penetration testers, etc.  This presentation focuses on security linters that are open source, found on GitHub, and highly recommended to aid in development.  Finding bugs (security related or not) earliest in the development life-cycle is essential.  This talk will cover how easy it is to use these linters and how to integrate into your favorite IDE and build system.

  Presentation: [[https://www.socallinuxexpo.org/sites/default/files/presentations/YourSuiteofOpenSourceSecurityLinters-compressed.pdf][YourSuiteofOpenSourceSecurityLinters-compressed.pdf]]

  Room: Room 106

  Time: Sunday, March 10, 2019 - 11:30 to 12:30
#+end_quote
* (www.socallinuxexpo.org) YourSuiteofOpenSourceSecurityLinters-compressed.pdf :mime_type_application_pdf:ATTACH:
:PROPERTIES:
:ID:       8f0cf19f-a79e-4ecb-9a13-a6bf2a7ac6db
:ROAM_REFS: https://www.socallinuxexpo.org/sites/default/files/presentations/YourSuiteofOpenSourceSecurityLinters-compressed.pdf
:END:
* (www.youtube.com) Room 106 Sunday Mar. 10 - SCaLE 17x - YouTube     :video:
:PROPERTIES:
:ID:       9bafff0e-3265-4888-85a3-84b35c85f7e8
:ROAM_REFS: https://www.youtube.com/watch?v=Uc11xp9Pawc https://youtu.be/Uc11xp9Pawc
:END:

#+begin_quote
  * Room 106 Sunday Mar. 10 - SCaLE 17x

  [[https://www.youtube.com/@socallinuxexpo][Southern California Linux Expo]]

  **** License

  [[https://www.youtube.com/t/creative_commons][Creative Commons Attribution license (reuse allowed)]]

  SCaLE is the largest community-run open-source and free software conference in North America.  It is held annually in Pasadena.

  11:30 AM to 12:30 PM PDT: [[https://www.youtube.com/redirect?event=video_description&redir_token=QUFFLUhqbjViVUMydk9Wa2VlTkdGT0stRGFDTGVxODFZUXxBQ3Jtc0tsUVR0WUxxemxJR1ltdTJ3UHNXZkt0ZnpubUNoVWdwNFdZcms2VUpxU1RGTGZVeExqeE5jdUVnY1dnVWNJcmRjbGx1aWJfcmZES21kcm5tVmRUQnV5NWNJNGpHQTNBYnh0SmdGcllCbHNoNlBKUzJvUQ&q=https://www.socallinuxexpo.org/scale/17x/presentations/your-suite-open-source-security-linters&v=Uc11xp9Pawc][https://www.socallinuxexpo.org/scale/...]]\\
  01:30 PM to 02:30 PM PDT: [[https://www.youtube.com/redirect?event=video_description&redir_token=QUFFLUhqa21vTHdRM01QdGU0bWx0Z1NMOEVXaFlveFZDUXxBQ3Jtc0ttQkNNWlltWXJibUdjdUwxNUZwTzhoaWgycUdBeXZCWmdlcjBLQ1B3Z0N3QTBSa0FQRE5DSFlIalJvaWJzX1NUaVlCUkhjaVE4UnRJU252VG5uYlItSllqM3RfUU9NTmlyOV9wZUpTa0hQTGxNaUNPNA&q=https://www.socallinuxexpo.org/scale/17x/presentations/device-and-personal-privacy-technology-roundup&v=Uc11xp9Pawc][https://www.socallinuxexpo.org/scale/...]]\\
  03:00 PM to 04:00 PM PDT: [[https://www.youtube.com/redirect?event=video_description&redir_token=QUFFLUhqa28taHg5SWIyS01iT3pzS2VnNU05djZfZ05iUXxBQ3Jtc0tta2F5WFNYaGdpN3Nfd2RuQnBOSGZJbkhMcEotWnppU29PMTJvWWRJOVhmcDZIZUFnalVIN1N4eDVZNXh4SzdKcG1MaGtWbmJrZnBnYkVtWjF2TjNWTW15NkNWbl9LTUNTWFZjaU44N2kxejRZVTl1UQ&q=https://www.socallinuxexpo.org/scale/17x/presentations/adding-security-your-workflow-inspec&v=Uc11xp9Pawc][https://www.socallinuxexpo.org/scale/...]]\\
  04:30 PM to 05:30 PM PDT: [[https://www.youtube.com/redirect?event=video_description&redir_token=QUFFLUhqblduSzdjNjV3ZVRNT2c4aGcwMDE2RUZ2RmtnZ3xBQ3Jtc0trdkFkd0lmdnloRFJ6NC1DeG01VTc2c0VRbDJIOFoway0zT2FXNHVVSjFOdGdGYU5sNExwXzcydXJHZmtFdEZRTUJJc25zOTBUU0VBTjd2cDAzTE4tMU8tb2dPM0tyZ3JmMHlSSlFSc0pwTGgyX3JZaw&q=https://www.socallinuxexpo.org/scale/17x/presentations/anatomy-secure-java-web-app-using-apache-fortress&v=Uc11xp9Pawc][https://www.socallinuxexpo.org/scale/...]]

  Southern California Linux Expo: [[https://www.youtube.com/redirect?event=video_description&redir_token=QUFFLUhqbU1HN012TXdCQkJGZmdkMlFELXpFVFhUZWxLZ3xBQ3Jtc0ttZDhXa091MDRkaVJLV2JtcFlNN1g1eFd2UEFCUFZrRjdFaVN2M0VidFdQS1NzQU9HTEpUbElDNVpvbGdQenAtVXZlLXEwczFkNFB2aFh2cDVrRjJLZDQ2UjlRZlh3R0JmaUdjZWtNajhYWERPZ0oyNA&q=https://www.socallinuxexpo.org/scale/17x&v=Uc11xp9Pawc][https://www.socallinuxexpo.org/scale/17x]]
#+end_quote
