:PROPERTIES:
:ID:       9a26860d-0ea9-448a-84d4-d21d1f949d9d
:ROAM_REFS: https://zzamboni.org/post/my-emacs-configuration-with-commentary/
:END:
#+title: (zzamboni.org) zzamboni.org | My Emacs Configuration, With Commentary
#+filetags: :configuration:information_management:emacs:blog_post:website:

#+begin_quote
  * My Emacs Configuration, With Commentary

  December 17, 2017

  Last update: *October 30, 2024*

  I have enjoyed slowly converting my configuration files to [[http://www.howardism.org/Technical/Emacs/literate-programming-tutorial.html][literate programming]] style style using org-mode in Emacs.  I previously posted my [[https://zzamboni.org/post/my-elvish-configuration-with-commentary/][Elvish configuration]], and now it's the turn of my Emacs configuration file.  The text below is included directly from my [[https://github.com/zzamboni/dot_emacs/blob/master/init.org][init.org]] file.  Please note that the text below is a snapshot as the file stands as of the date shown above, but it is always evolving.  See the [[https://github.com/zzamboni/dot_emacs/blob/master/init.org][init.org file in GitHub]] for my current, live configuration, and the generated file at [[https://github.com/zzamboni/dot_emacs/blob/master/init.el][init.el]].

  If you are interested in writing your own Literate Config files, check out my new book [[https://leanpub.com/lit-config][Literate Config]] on Leanpub!

  *Note:* I no longer maintain this configuration (though I frequently refer to it when I need to remember how to do something).  I now use [[https://github.com/hlissner/doom-emacs][Doom Emacs]], you can find my current Emacs config at [[https://github.com/zzamboni/dot-doom/blob/master/doom.org]].
#+end_quote
